// frontend/admin/react/src/pages/app/system/monitor_alert/index.tsx
import { useRef, useState } from 'react';
import type { ActionType, ProColumns } from '@ant-design/pro-components';
import ListTable from '@/components/common/ListTable';
import {
  ModalForm,
  ProFormDependency,
  ProFormText,
  ProFormTextArea,
  ProFormSelect,
  ProFormDigit,
  ProFormSwitch,
} from '@ant-design/pro-components';
import { App, Button, Popconfirm, Tag, Tooltip } from 'antd';
import {
  CaretRightOutlined,
  DeleteOutlined,
  EditOutlined,
  PlusOutlined,
} from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import type {
  monitor_alertservicev1_CreateMonitorAlertRuleRequest,
  monitor_alertservicev1_MonitorAlertRule as MonitorAlertRule,
  monitor_alertservicev1_UpdateMonitorAlertRuleRequest,
} from '@/api/generated/admin/service/v1';
import { PaginationQuery } from '@/core';
import { TABLE } from '@/config/constants';
import {
  fetchListMonitorAlertRules,
  useCreateMonitorAlertRule,
  useDeleteMonitorAlertRule,
  useEvaluateMonitorAlerts,
  useUpdateMonitorAlertRule,
} from '@/api/hooks/monitor-alert';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

/**
 * 监控告警规则：指标阈值 → 触发通知（联动通知域）。
 *
 * 渠道与目标显式写在规则上（不经路由表）：告警是"点对点"的运营配置。
 * 评估每 5 分钟自动跑一轮（系统级常驻任务），「立即评估」手动触发同一内核；
 * 告警→恢复成对通知，持续越限按冷却间隔重发。
 */

const metricOptions = (t: (key: string) => string) =>
  (
    [
      'GO_GOROUTINES',
      'GO_MEM_ALLOC_MB',
      'DB_OPEN_CONNECTIONS',
      'DB_PING_FAIL',
      'REDIS_DB_SIZE',
    ] as const
  ).map((value) => ({ value, label: t(`metricMap.${value}`) }));

const opOptions = (t: (key: string) => string) =>
  (['GE', 'LE'] as const).map((value) => ({ value, label: t(`opMap.${value}`) }));

const channelOptions = (t: (key: string) => string) =>
  (['EMAIL', 'WEBHOOK'] as const).map((value) => ({ value, label: t(`channelMap.${value}`) }));

const MonitorAlertPage = () => {
  const { t } = useTranslation('monitor-alert');
  const actionRef = useRef<ActionType>(null);
  const { message, modal } = App.useApp();
  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);

  const [formOpen, setFormOpen] = useState(false);
  const [formMode, setFormMode] = useState<'create' | 'edit'>('create');
  const [selected, setSelected] = useState<MonitorAlertRule | undefined>();

  const refresh = () => actionRef.current?.reload();

  const createMutation = useCreateMonitorAlertRule();
  const updateMutation = useUpdateMonitorAlertRule();
  const deleteMutation = useDeleteMonitorAlertRule();
  const evaluateMutation = useEvaluateMonitorAlerts();

  const handleDelete = async (record: MonitorAlertRule) => {
    if (!record.id) return;
    try {
      await deleteMutation.mutateAsync({ id: record.id });
      message.success(t('deleteSuccess'));
      refresh();
    } catch (error: any) {
      console.error('delete monitor alert rule failed', error);
      message.error(error.message || t('deleteFailed'));
    }
  };

  const handleEvaluate = async () => {
    try {
      const resp = await evaluateMutation.mutateAsync({});
      const lines = (resp.outcomes ?? []).map((o) => {
        const value = o.currentValue != null ? o.currentValue.toFixed(2) : '-';
        const state = o.firing ? t('outcomeFiring') : t('outcomeNormal');
        const extra = o.notified
          ? ` · ${t('outcomeNotified')}`
          : o.reason
            ? ` · ${o.reason}`
            : '';
        return `${o.name}: ${state} (${value}${extra})`;
      });
      modal.info({
        title: t('evaluateResultTitle'),
        content: <div style={{ whiteSpace: 'pre-wrap' }}>{lines.join('\n') || t('evaluateEmpty')}</div>,
        width: 560,
      });
    } catch (error: any) {
      console.error('evaluate monitor alerts failed', error);
      message.error(error.message || t('evaluateFailed'));
    }
  };

  const handleSubmit = async (values: Record<string, any>) => {
    const isPingFail = values.metric === 'DB_PING_FAIL';
    const data = {
      name: values.name,
      metric: values.metric,
      // DB_PING_FAIL 是布尔指标，op/threshold 无意义不给
      op: isPingFail ? undefined : values.op,
      threshold: isPingFail ? undefined : values.threshold,
      cooldownMinutes: values.cooldownMinutes ?? 30,
      channel: values.channel,
      target: values.target,
      isEnabled: !!values.isEnabled,
      remark: values.remark,
    };
    try {
      if (formMode === 'create') {
        const req: monitor_alertservicev1_CreateMonitorAlertRuleRequest = { data };
        await createMutation.mutateAsync(req);
        message.success(t('createSuccess'));
      } else if (selected?.id) {
        const req: monitor_alertservicev1_UpdateMonitorAlertRuleRequest = {
          id: selected.id,
          data,
          updateMask: 'name,metric,op,threshold,cooldownMinutes,channel,target,isEnabled,remark',
        };
        await updateMutation.mutateAsync(req);
        message.success(t('updateSuccess'));
      }
      setFormOpen(false);
      refresh();
      return true;
    } catch (error: any) {
      console.error('save monitor alert rule failed', error);
      message.error(error.message || t('saveFailed'));
      return false;
    }
  };

  const columns: ProColumns<MonitorAlertRule>[] = [
    { title: t('name'), dataIndex: 'name', width: 160 },
    {
      title: t('metric'),
      dataIndex: 'metric',
      width: 180,
      valueType: 'select',
      fieldProps: { options: metricOptions(t) },
      render: (_, record) =>
        record.metric ? <Tag color="geekblue">{t(`metricMap.${record.metric}`)}</Tag> : '-',
    },
    {
      title: t('condition'),
      width: 150,
      hideInSearch: true,
      render: (_, record) =>
        record.metric === 'DB_PING_FAIL'
          ? t('pingFailCondition')
          : `${t(`opMap.${record.op}`)} ${record.threshold ?? '-'}`,
    },
    {
      title: t('cooldownMinutes'),
      dataIndex: 'cooldownMinutes',
      width: 110,
      hideInSearch: true,
      render: (_, record) => `${record.cooldownMinutes ?? 30} min`,
    },
    {
      title: t('channel'),
      dataIndex: 'channel',
      width: 100,
      valueType: 'select',
      fieldProps: { options: channelOptions(t) },
      render: (_, record) => (record.channel ? <Tag>{t(`channelMap.${record.channel}`)}</Tag> : '-'),
    },
    {
      title: t('target'),
      dataIndex: 'target',
      width: 220,
      ellipsis: true,
      copyable: true,
    },
    {
      title: t('lastFiring'),
      width: 110,
      hideInSearch: true,
      tooltip: t('lastFiringHint'),
      render: (_, record) =>
        record.lastFiring ? (
          <Tag color="error">{t('firingNow')}</Tag>
        ) : (
          <Tag color="success">{t('firingNo')}</Tag>
        ),
    },
    {
      title: t('lastAlertedAt'),
      dataIndex: 'lastAlertedAt',
      width: 170,
      valueType: 'dateTime',
      hideInSearch: true,
    },
    {
      title: t('isEnabled'),
      dataIndex: 'isEnabled',
      width: 90,
      render: (_, record) =>
        record.isEnabled ? (
          <Tag color="success">{t('enabledOn')}</Tag>
        ) : (
          <Tag>{t('enabledOff')}</Tag>
        ),
    },
    {
      title: t('actions'),
      valueType: 'option',
      width: 180,
      fixed: 'right',
      render: (_, record) => [
        <Button
          key="edit"
          type="link"
          size="small"
          icon={<EditOutlined />}
          onClick={() => {
            setFormMode('edit');
            setSelected(record);
            setFormOpen(true);
          }}
        >
          {t('edit')}
        </Button>,
        <Popconfirm key="delete" title={t('deleteConfirm')} onConfirm={() => handleDelete(record)}>
          <Button danger type="link" size="small" icon={<DeleteOutlined />}>
            {t('delete')}
          </Button>
        </Popconfirm>,
      ],
    },
  ];

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      <div ref={containerRef} className="page-container-content">
        <ListTable<MonitorAlertRule>
          actionRef={actionRef}
          columns={columns}
          request={async (params) => {
            const query = new PaginationQuery({
              paging: { page: params.current || 1, pageSize: params.pageSize || 20 },
              formValues: Object.fromEntries(
                Object.entries(params).filter(([key]) => !['current', 'pageSize'].includes(key)),
              ),
            });
            const response = await fetchListMonitorAlertRules(query);
            return { data: response.items || [], total: response.total || 0, success: true };
          }}
          rowKey="id"
          search={{ labelWidth: 'auto', defaultCollapsed: false }}
          pagination={{
            defaultPageSize: TABLE.DEFAULT_PAGE_SIZE,
            showSizeChanger: true,
          }}
          options={{ density: true, fullScreen: true, setting: true, reload: true }}
          toolBarRender={() => [
            <Tooltip key="evaluate-tip" title={t('evaluateHint')}>
              <Button
                key="evaluate"
                icon={<CaretRightOutlined />}
                loading={evaluateMutation.isPending}
                onClick={handleEvaluate}
              >
                {t('evaluateNow')}
              </Button>
            </Tooltip>,
            <Button
              key="create"
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setFormMode('create');
                setSelected(undefined);
                setFormOpen(true);
              }}
            >
              {t('create')}
            </Button>,
          ]}
          size="middle"
          bordered
          scroll={{ y: tableScrollY, x: 1300 }}
        />
      </div>

      <ModalForm
        title={formMode === 'create' ? t('create') : t('edit')}
        width={560}
        open={formOpen}
        onOpenChange={setFormOpen}
        modalProps={{ destroyOnHidden: true, mask: { closable: false } }}
        submitTimeout={3000}
        onFinish={handleSubmit}
        initialValues={
          formMode === 'create'
            ? { cooldownMinutes: 30, channel: 'EMAIL', isEnabled: true }
            : { ...selected }
        }
      >
        <ProFormText
          name="name"
          label={t('name')}
          rules={[{ required: true, message: t('requiredName') }, { max: 100, message: t('maxChars', { max: 100 }) }]}
        />
        <ProFormSelect
          name="metric"
          label={t('metric')}
          options={metricOptions(t)}
          rules={[{ required: true, message: t('requiredMetric') }]}
        />
        <ProFormDependency name={['metric']}>
          {({ metric }) =>
            metric === 'DB_PING_FAIL' ? null : (
              <>
                <ProFormSelect
                  name="op"
                  label={t('op')}
                  options={opOptions(t)}
                  rules={[{ required: true, message: t('requiredOp') }]}
                />
                <ProFormDigit
                  name="threshold"
                  label={t('threshold')}
                  fieldProps={{ precision: 2, step: 1 }}
                  rules={[{ required: true, message: t('requiredThreshold') }]}
                />
              </>
            )
          }
        </ProFormDependency>
        <ProFormDigit
          name="cooldownMinutes"
          label={t('cooldownMinutes')}
          tooltip={t('cooldownHint')}
          min={1}
          max={1440}
          fieldProps={{ precision: 0 }}
          initialValue={30}
        />
        <ProFormSelect
          name="channel"
          label={t('channel')}
          options={channelOptions(t)}
          rules={[{ required: true, message: t('requiredChannel') }]}
        />
        <ProFormText
          name="target"
          label={t('target')}
          tooltip={t('targetHint')}
          rules={[{ required: true, message: t('requiredTarget') }, { max: 500, message: t('maxChars', { max: 500 }) }]}
        />
        <ProFormSwitch name="isEnabled" label={t('isEnabled')} />
        <ProFormTextArea name="remark" label={t('remark')} fieldProps={{ rows: 2 }} />
      </ModalForm>
    </ContentContainer>
  );
};

export default MonitorAlertPage;

// frontend/admin/vue-element/src/pages/app/system/monitor_alert/index.vue
<template>
  <div class="app-container h-full flex flex-1 flex-col">
    <ProPage
      ref="pageRef"
      :config="pageConfig"
      @add="handleAdd"
      @edit="handleEdit"
      @operate="handleOperate"
    >
      <!-- 指标 -->
      <template #metric="scope: any">
        <ElTag v-if="scope.row.metric" size="small" round effect="plain">
          {{ t(`pages.monitor_alert.metricMap.${scope.row.metric}`) }}
        </ElTag>
        <span v-else>-</span>
      </template>

      <!-- 触发条件：布尔指标单独说人话 -->
      <template #condition="scope: any">
        <span v-if="scope.row.metric === 'DB_PING_FAIL'">
          {{ t("pages.monitor_alert.pingFailCondition") }}
        </span>
        <span v-else>
          {{ t(`pages.monitor_alert.opMap.${scope.row.op}`) }} {{ scope.row.threshold ?? "-" }}
        </span>
      </template>

      <!-- 当前状态：来自最近一轮自动评估（每 5 分钟） -->
      <template #lastFiring="scope: any">
        <ElTag v-if="scope.row.lastFiring" size="small" round type="danger">
          {{ t("pages.monitor_alert.firingNow") }}
        </ElTag>
        <ElTag v-else size="small" round type="success">
          {{ t("pages.monitor_alert.firingNo") }}
        </ElTag>
      </template>

      <!-- 渠道 -->
      <template #channel="scope: any">
        <ElTag v-if="scope.row.channel" size="small" round>
          {{ t(`pages.monitor_alert.channelMap.${scope.row.channel}`) }}
        </ElTag>
        <span v-else>-</span>
      </template>

      <!-- 启用：停用不是删除，是不再评估 -->
      <template #isEnabled="scope: any">
        <ElTag v-if="scope.row.isEnabled" size="small" round type="success">
          {{ t("pages.monitor_alert.enabledOn") }}
        </ElTag>
        <ElTag v-else size="small" round type="info">
          {{ t("pages.monitor_alert.enabledOff") }}
        </ElTag>
      </template>
    </ProPage>

    <!-- 创建/编辑抽屉 -->
    <MonitorAlertDrawer ref="drawerRef" @success="handleSuccess" />

    <!-- 立即评估：与后台每 5 分钟的自动扫描同一内核，结果逐规则展示 -->
    <ElDialog
      v-model="evaluateVisible"
      :title="t('pages.monitor_alert.evaluateResultTitle')"
      width="640px"
      align-center
      :close-on-click-modal="false"
    >
      <div v-if="evaluateOutcomes.length === 0" class="evaluate-empty">
        {{ t("pages.monitor_alert.evaluateEmpty") }}
      </div>
      <ElTable v-else :data="evaluateOutcomes" size="small" border max-height="420">
        <ElTableColumn prop="name" :label="t('pages.monitor_alert.name')" min-width="140" />
        <ElTableColumn :label="t('pages.monitor_alert.evaluateState')" width="90">
          <template #default="{ row }">
            <ElTag v-if="row.firing" size="small" type="danger">
              {{ t("pages.monitor_alert.firingNow") }}
            </ElTag>
            <ElTag v-else size="small" type="success">
              {{ t("pages.monitor_alert.firingNo") }}
            </ElTag>
          </template>
        </ElTableColumn>
        <ElTableColumn :label="t('pages.monitor_alert.evaluateValue')" width="110">
          <template #default="{ row }">
            {{ row.currentValue != null ? Number(row.currentValue).toFixed(2) : "-" }}
          </template>
        </ElTableColumn>
        <ElTableColumn :label="t('pages.monitor_alert.evaluateNotified')" width="90">
          <template #default="{ row }">
            {{ row.notified ? t("pages.monitor_alert.notifiedYes") : "-" }}
          </template>
        </ElTableColumn>
        <ElTableColumn
          prop="reason"
          :label="t('pages.monitor_alert.evaluateReason')"
          min-width="180"
          show-overflow-tooltip
        />
      </ElTable>
      <template #footer>
        <ElButton @click="evaluateVisible = false">{{ $t("common.button.cancel") }}</ElButton>
        <ElButton type="primary" :loading="evaluating" @click="handleEvaluate">
          {{ t("pages.monitor_alert.evaluateNow") }}
        </ElButton>
      </template>
    </ElDialog>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import {
  ElButton,
  ElDialog,
  ElMessage,
  ElMessageBox,
  ElTable,
  ElTableColumn,
  ElTag,
} from "element-plus";

import ProPage from "@/components/Pro/ProPage/index.vue";
import type { ProPageConfig } from "@/components/Pro/ProPage/types";
import MonitorAlertDrawer from "./monitor-alert-drawer.vue";
import type { monitor_alertservicev1_MonitorAlertRule as MonitorAlertRule } from "@/api/generated/admin/service/v1";
import {
  fetchListMonitorAlertRules,
  useDeleteMonitorAlertRule,
  useEvaluateMonitorAlerts,
} from "@/api/composables";
import { PaginationQuery } from "@/core/transport/rest";
import { useI18n } from "@/core/i18n";

const { t } = useI18n();

const pageRef = ref();
const drawerRef = ref();

const { mutateAsync: deleteRule } = useDeleteMonitorAlertRule();
const { mutateAsync: evaluateAlerts } = useEvaluateMonitorAlerts();

const evaluateVisible = ref(false);
const evaluating = ref(false);
const evaluateOutcomes = ref<any[]>([]);

const pageConfig = computed<ProPageConfig>(() => ({
  skeleton: true,
  search: {
    grid: true,
    fields: [
      {
        type: "input",
        label: t("pages.monitor_alert.name"),
        field: "name",
        attrs: { placeholder: t("common.placeholder.input"), clearable: true },
      },
    ],
  },
  table: {
    listAction: async (query: any) => {
      const { page, pageSize, ...queryParams } = query;
      const result = await fetchListMonitorAlertRules(
        new PaginationQuery({
          paging: { page: page || 1, pageSize: pageSize || 20 },
          formValues: {
            name: queryParams.name,
          },
        })
      );
      return { items: result.items || [], total: result.total || 0 };
    },
    toolbar: [
      // 自定义工具栏按钮：走 @operate 分发（name !== edit/delete/view/add 即透传）
      {
        name: "evaluate",
        label: t("pages.monitor_alert.evaluateNow"),
        icon: "lucide:play",
      },
    ],
    toolbarRight: ["add"],
    defaultToolbar: ["refresh", "filter"],
    tableAttrs: { border: true, stripe: true },
    emptyActionText: "common.button.add",
    columns: [
      {
        prop: "name",
        label: t("pages.monitor_alert.name"),
        minWidth: 150,
      },
      {
        prop: "metric",
        label: t("pages.monitor_alert.metric"),
        width: 150,
        slotName: "metric",
      },
      {
        prop: "condition",
        label: t("pages.monitor_alert.condition"),
        width: 140,
        slotName: "condition",
      },
      {
        prop: "cooldownMinutes",
        label: t("pages.monitor_alert.cooldownMinutes"),
        width: 100,
        formatter: (row: MonitorAlertRule) => `${row.cooldownMinutes ?? 30} min`,
      },
      {
        prop: "channel",
        label: t("pages.monitor_alert.channel"),
        width: 90,
        slotName: "channel",
      },
      {
        prop: "target",
        label: t("pages.monitor_alert.target"),
        minWidth: 200,
        formatter: (row: MonitorAlertRule) => row.target || "-",
      },
      {
        prop: "lastFiring",
        label: t("pages.monitor_alert.lastFiring"),
        width: 90,
        slotName: "lastFiring",
      },
      {
        prop: "lastAlertedAt",
        label: t("pages.monitor_alert.lastAlertedAt"),
        width: 170,
        cellType: "date",
        dateFormat: "YYYY-MM-DD HH:mm:ss",
      },
      {
        prop: "isEnabled",
        label: t("pages.monitor_alert.isEnabled"),
        width: 80,
        slotName: "isEnabled",
      },
      {
        prop: "action",
        label: t("common.table.action"),
        fixed: "right",
        width: 160,
        cellType: "tool",
        buttons: [
          { name: "edit", label: t("common.button.edit"), icon: "lucide:pen-line" },
          // 删除按钮刻意不叫 "delete"：删掉的规则不再评估，后果必须说清
          {
            name: "remove",
            label: t("common.button.delete"),
            icon: "lucide:trash-2",
            attrs: { type: "danger" },
          },
        ],
      },
    ],
  },
}));

function handleAdd() {
  drawerRef.value?.open({ create: true });
}

function handleEdit(row: MonitorAlertRule) {
  drawerRef.value?.open({ create: false, row });
}

function handleSuccess() {
  pageRef.value?.refresh();
}

async function handleOperate(data: { name: string; row?: MonitorAlertRule }) {
  if (data.name === "evaluate") {
    evaluateVisible.value = true;
    evaluateOutcomes.value = [];
    await handleEvaluate();
    return;
  }
  if (data.name !== "remove") return;

  const row = data.row;
  if (!row?.id) return;

  try {
    await ElMessageBox.confirm(
      t("pages.monitor_alert.deleteConfirm"),
      t("common.title.confirm"),
      {
        confirmButtonText: t("common.button.confirm"),
        cancelButtonText: t("common.button.cancel"),
        type: "warning",
        lockScroll: false,
      }
    );
  } catch (error) {
    // 取消是 ElMessageBox 的 reject("cancel")，属正常路径；其余形态（API 误用等）留痕
    if (error !== "cancel" && error !== "close") {
      console.error("delete confirm dialog rejected unexpectedly", error);
    }
    return;
  }

  try {
    await deleteRule({ id: row.id });
    ElMessage.success(t("pages.monitor_alert.deleteSuccess"));
    pageRef.value?.refresh();
  } catch (error: any) {
    // 用户看到的那句翻译不含服务端原因，原始错误必须留在控制台
    console.error("delete monitor alert rule failed", error);
    ElMessage.error(error?.message || t("pages.monitor_alert.deleteFailed"));
  }
}

// === 立即评估 ===
async function handleEvaluate() {
  evaluating.value = true;
  try {
    // body:"*" 自定义路由，请求体扁平：包一层 { data } 会被 protojson 当未知字段丢掉
    const resp = await evaluateAlerts({});
    evaluateOutcomes.value = resp.outcomes ?? [];
  } catch (error: any) {
    console.error("evaluate monitor alerts failed", error);
    ElMessage.error(error?.message || t("pages.monitor_alert.evaluateFailed"));
  } finally {
    evaluating.value = false;
  }
}
</script>

<style lang="scss" scoped>
.app-container {
  padding: 20px;
  width: 100%;
  min-width: 0;
  flex-shrink: 0;
}

.evaluate-empty {
  padding: 24px 0;
  text-align: center;
  font-size: 13px;
  color: var(--el-text-color-secondary);
}
</style>
