// frontend/admin/react/src/pages/app/opm/position/index.tsx
import { useRef, useState } from 'react';
import type { ProColumns, ActionType } from '@ant-design/pro-components';
import { ProTable } from '@ant-design/pro-components';
import { Button, Popconfirm, Tag, App } from 'antd';
import {
  EditOutlined,
  DeleteOutlined,
  PlusOutlined,
  UploadOutlined,
} from '@ant-design/icons';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import type { identityservicev1_Position as Position } from '@/api/generated/admin/service/v1';
import { PaginationQuery } from '@/core';
import { fetchListPositions, useCreatePosition, useDeletePosition } from '@/api/hooks/position';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';
import ImportModal from '@/components/common/ImportModal';
import type { ImportField } from '@/utils/import';
import {
  getStatusMap,
  getStatusOptions,
  getPositionTypeMap,
  getPositionTypeOptions,
} from './constants';
import PositionDrawer from './components/PositionDrawer';

/**
 * 职位管理页面
 */
const PositionManagement = () => {
  const { t } = useTranslation('position');
  const actionRef = useRef<ActionType>(null);
  const queryClient = useQueryClient();
  const { message } = App.useApp();

  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);

  // Drawer 状态管理
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [drawerMode, setDrawerMode] = useState<'create' | 'edit'>('create');
  const [selectedPosition, setSelectedPosition] = useState<Position | undefined>();

  // Excel 导入：字段与创建表单一致，唯排除 orgUnitId（外键需名称解析，属后续演进）
  const [importOpen, setImportOpen] = useState(false);
  const createMutation = useCreatePosition();
  const importFields: ImportField[] = [
    { label: t('name'), prop: 'name' },
    { label: t('code'), prop: 'code' },
    { label: t('type'), prop: 'type' },
    { label: t('status'), prop: 'status' },
    { label: t('headcount'), prop: 'headcount' },
    { label: t('sortOrder'), prop: 'sortOrder' },
    { label: t('description'), prop: 'description' },
    { label: t('remark'), prop: 'remark' },
  ];

  const statusMap = getStatusMap(t);
  const positionTypeMap = getPositionTypeMap(t);

  // 删除操作
  const deleteMutation = useDeletePosition({
    onSuccess: () => {
      message.success(t('deleteSuccess'));
      actionRef.current?.reload();
      queryClient.invalidateQueries({ queryKey: ['listPositions'] });
    },
    onError: (error: Error) => {
      message.error(error.message || t('deleteFailed'));
    },
  });

  // 列配置
  const columns: ProColumns<Position>[] = [
    {
      title: t('name'),
      dataIndex: 'name',
    },
    {
      title: t('code'),
      dataIndex: 'code',
    },
    {
      title: t('type'),
      dataIndex: 'type',
      width: 95,
      valueType: 'select',
      fieldProps: {
        options: getPositionTypeOptions(t),
      },
      render: (_, record) => {
        const type = record.type as keyof typeof positionTypeMap;
        const config = positionTypeMap[type] || { text: type, color: 'default' };
        return <Tag color={config.color}>{config.text}</Tag>;
      },
    },
    {
      title: t('description'),
      dataIndex: 'description',
      hideInSearch: true,
      ellipsis: true,
    },
    {
      title: t('orgUnitName'),
      dataIndex: 'orgUnitName',
      width: 150,
      hideInSearch: true,
    },
    {
      title: t('headcount'),
      dataIndex: 'headcount',
      width: 80,
      hideInSearch: true,
    },
    {
      title: t('status'),
      dataIndex: 'status',
      width: 95,
      valueType: 'select',
      fieldProps: {
        options: getStatusOptions(t),
      },
      render: (_, record) => {
        const status = record.status as keyof typeof statusMap;
        const config = statusMap[status] || { text: status, color: 'default' };
        return <Tag color={config.color}>{config.text}</Tag>;
      },
    },
    {
      title: t('sortOrder'),
      dataIndex: 'sortOrder',
      width: 70,
      hideInSearch: true,
    },
    {
      title: t('createdAt'),
      dataIndex: 'createdAt',
      width: 180,
      valueType: 'dateTime',
      hideInSearch: true,
    },
    {
      title: t('remark'),
      dataIndex: 'remark',
      hideInSearch: true,
      ellipsis: true,
    },
    {
      title: t('action'),
      valueType: 'option',
      width: 90,
      render: (_, record) => [
        <a
          key="edit"
          onClick={() => {
            setDrawerMode('edit');
            setSelectedPosition(record);
            setDrawerOpen(true);
          }}
        >
          <EditOutlined />
        </a>,
        <Popconfirm
          key="delete"
          title={t('deleteConfirmTitle')}
          description={t('deleteConfirmDesc', { moduleName: t('moduleName') })}
          onConfirm={() => record.id && deleteMutation.mutate({ id: record.id })}
          okText={t('common:button.ok')}
          cancelText={t('common:button.cancel')}
        >
          <a style={{ color: 'var(--ant-color-error)' }}><DeleteOutlined /></a>
        </Popconfirm>,
      ],
    },
  ];

  return (
    <>
      <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
        <div ref={containerRef} className="page-container-content">
          <ProTable<Position>
            actionRef={actionRef}
            columns={columns}
            request={async (params, _sorter, _filter) => {
              try {
                const query = new PaginationQuery({
                  paging: {
                    page: params.current || 1,
                    pageSize: params.pageSize || 20,
                  },
                  formValues: Object.fromEntries(
                    Object.entries(params).filter(
                      ([key]) => !['current', 'pageSize'].includes(key),
                    ),
                  ),
                });

                const response = await fetchListPositions(query);

                return {
                  data: response.items || [],
                  total: response.total || 0,
                  success: true,
                };
              } catch (error: any) {
                message.error(error.message || t('fetchFailed'));
                return { data: [], total: 0, success: false };
              }
            }}
            rowKey="id"
            search={{
              labelWidth: 'auto',
              defaultCollapsed: false,
            }}
            pagination={{
              defaultPageSize: 20,
              showSizeChanger: true,
              showQuickJumper: true,
            }}
            toolBarRender={() => [
              <Button
                key="create"
                type="primary"
                icon={<PlusOutlined />}
                onClick={() => {
                  setDrawerMode('create');
                  setSelectedPosition(undefined);
                  setDrawerOpen(true);
                }}
              >
                {t('create')}
              </Button>,
              <Button
                key="import"
                icon={<UploadOutlined />}
                onClick={() => setImportOpen(true)}
              >
                {t('common:import.title')}
              </Button>,
            ]}
            options={{
              density: true,
              fullScreen: true,
              setting: true,
              reload: true,
            }}
            size="middle"
            bordered
            cardBordered={false}
            scroll={{ y: tableScrollY }}
          />
        </div>
      </ContentContainer>

      {/* 职位编辑/创建 Drawer */}
      <PositionDrawer
        open={drawerOpen}
        mode={drawerMode}
        data={selectedPosition}
        onClose={() => {
          setDrawerOpen(false);
          setSelectedPosition(undefined);
        }}
        onSuccess={() => {
          actionRef.current?.reload();
        }}
      />

      {/* Excel 导入 */}
      <ImportModal
        open={importOpen}
        fields={importFields}
        createRow={(values) => createMutation.mutateAsync({ data: values })}
        onClose={() => setImportOpen(false)}
        onSuccess={() => {
          actionRef.current?.reload();
          queryClient.invalidateQueries({ queryKey: ['listPositions'] });
        }}
      />
    </>
  );
};

export default PositionManagement;

// frontend/admin/vue-vben/apps/admin/src/views/app/opm/position/index.vue
﻿<script lang="ts" setup>
import type { VxeGridProps } from '#/adapter/vxe-table';

import { h, ref } from 'vue';

import { Page, useVbenDrawer, type VbenFormProps } from '@vben/common-ui';
import { LucideFilePenLine, LucideTrash2 } from '@vben/icons';

import { notification } from 'ant-design-vue';

import { useVbenVxeGrid } from '#/adapter/vxe-table';
import {
  fetchListOrgUnits,
  fetchListPositions,
  PaginationQuery,
  positionTypeList,
  positionTypeToColor,
  positionTypeToName,
  statusList,
  statusToColor,
  statusToName,
  useCreatePosition,
  useDeletePosition,
} from '#/api';
import { type identityservicev1_Position as Position } from '#/api';
import ImportModal from '#/components/ImportModal.vue';
import type { ImportField } from '#/utils/import';
import { $t } from '#/locales';

import PositionDrawer from './position-drawer.vue';

const { mutateAsync: deletePosition } = useDeletePosition();

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: false,
  // 控制表单是否显示折叠按钮
  showCollapseButton: false,
  // 按下回车时是否提交表单
  submitOnEnter: true,
  schema: [
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('page.position.name'),
      componentProps: {
        placeholder: $t('ui.placeholder.input'),
        allowClear: true,
      },
    },
    {
      component: 'Input',
      fieldName: 'code',
      label: $t('page.position.code'),
      componentProps: {
        placeholder: $t('ui.placeholder.input'),
        allowClear: true,
      },
    },
    {
      component: 'Select',
      fieldName: 'status',
      label: $t('ui.table.status'),
      componentProps: {
        options: statusList,
        placeholder: $t('ui.placeholder.select'),
        filterOption: (input: string, option: any) =>
          option.label.toLowerCase().includes(input.toLowerCase()),
        allowClear: true,
        showSearch: true,
      },
    },
    {
      component: 'Select',
      fieldName: 'type',
      label: $t('page.position.type'),
      componentProps: {
        options: positionTypeList,
        placeholder: $t('ui.placeholder.select'),
        filterOption: (input: string, option: any) =>
          option.label.toLowerCase().includes(input.toLowerCase()),
        allowClear: true,
        showSearch: true,
      },
    },
    {
      component: 'ApiTreeSelect',
      fieldName: 'orgUnitId',
      label: $t('page.position.orgUnit'),
      componentProps: {
        placeholder: $t('ui.placeholder.select'),
        numberToString: true,
        showSearch: true,
        treeDefaultExpandAll: true,
        allowClear: true,
        childrenField: 'children',
        labelField: 'name',
        valueField: 'id',
        treeNodeFilterProp: 'label',
        api: async () => {
          const result = await fetchListOrgUnits(
            new PaginationQuery({
              formValues: { status: 'ON' },
            }),
          );
          return result.items;
        },
      },
    },
  ],
};

const gridOptions: VxeGridProps<Position> = {
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
  exportConfig: {},
  pagerConfig: {},
  rowConfig: {
    isHover: true,
  },
  height: 'auto',
  stripe: true,

  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {

        return await fetchListPositions(
          new PaginationQuery({
            paging: { page: page.currentPage, pageSize: page.pageSize },
            formValues,
          }),
        );
      },
    },
  },

  columns: [
    { title: $t('page.position.name'), field: 'name' },
    { title: $t('page.position.code'), field: 'code' },
    {
      title: $t('page.position.type'),
      field: 'type',
      slots: { default: 'type' },
      width: 95,
    },
    { title: $t('page.position.description'), field: 'description' },
    {
      title: $t('page.position.orgUnitName'),
      field: 'orgUnitName',
      width: 150,
    },
    { title: $t('page.position.headcount'), field: 'headcount', width: 80 },
    {
      title: $t('ui.table.status'),
      field: 'status',
      slots: { default: 'status' },
      width: 95,
    },
    { title: $t('ui.table.sortOrder'), field: 'sortOrder', width: 70 },
    {
      title: $t('ui.table.createdAt'),
      field: 'createdAt',
      formatter: 'formatDateTime',
      width: 140,
    },
    { title: $t('ui.table.remark'), field: 'remark' },
    {
      title: $t('ui.table.action'),
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      width: 90,
    },
  ],
};

const [Grid, gridApi] = useVbenVxeGrid({ gridOptions, formOptions });

// Excel 导入：字段与创建表单一致，唯排除 orgUnitId（外键需名称解析，属后续演进）
const { mutateAsync: createPosition } = useCreatePosition();
const importOpen = ref(false);
const importFields: ImportField[] = [
  { label: $t('page.position.name'), prop: 'name' },
  { label: $t('page.position.code'), prop: 'code' },
  { label: $t('page.position.type'), prop: 'type' },
  { label: $t('ui.table.status'), prop: 'status' },
  { label: $t('page.position.headcount'), prop: 'headcount' },
  { label: $t('ui.table.sortOrder'), prop: 'sortOrder' },
  { label: $t('page.position.description'), prop: 'description' },
  { label: $t('ui.table.remark'), prop: 'remark' },
];

function handleImportSuccess() {
  gridApi.reload();
}

const [Drawer, drawerApi] = useVbenDrawer({
  // 连接抽离的组件
  connectedComponent: PositionDrawer,

  onOpenChange(isOpen: boolean) {
    if (!isOpen) {
      // 关闭时，重载表格数据
      gridApi.reload();
    }
  },
});

function openDrawer(create: boolean, row?: any) {
  drawerApi.setData({
    create,
    row,
  });
  drawerApi.open();
}

/* 创建 */
function handleCreate() {

  openDrawer(true);
}

/* 编辑 */
function handleEdit(row: any) {
  openDrawer(false, row);
}

/* 删除 */
async function handleDelete(row: any) {

  try {
    await deletePosition({ id: row.id });

    notification.success({
      message: $t('ui.notification.delete_success'),
    });

    await gridApi.reload();
  } catch {
    notification.error({
      message: $t('ui.notification.delete_failed'),
    });
  }
}
</script>

<template>
  <Page auto-content-height>
    <Grid :table-title="$t('menu.opm.position')">
      <template #toolbar-tools>
        <a-button class="mr-2" type="primary" @click="handleCreate">
          {{ $t('page.position.button.create') }}
        </a-button>
        <a-button class="mr-2" @click="importOpen = true">
          {{ $t('ui.import.title') }}
        </a-button>
      </template>
      <template #status="{ row }">
        <a-tag :color="statusToColor(row.status)">
          {{ statusToName(row.status) }}
        </a-tag>
      </template>
      <template #type="{ row }">
        <a-tag :color="positionTypeToColor(row.type)">
          {{ positionTypeToName(row.type) }}
        </a-tag>
      </template>
      <template #action="{ row }">
        <a-button
          type="link"
          :icon="h(LucideFilePenLine)"
          @click.stop="handleEdit(row)"
        />
        <a-popconfirm
          :cancel-text="$t('ui.button.cancel')"
          :ok-text="$t('ui.button.ok')"
          :title="
            $t('ui.text.do_you_want_delete', {
              moduleName: $t('page.position.moduleName'),
            })
          "
          @confirm="handleDelete(row)"
        >
          <a-button danger type="link" :icon="h(LucideTrash2)" />
        </a-popconfirm>
      </template>
    </Grid>
    <Drawer />
    <ImportModal
      :open="importOpen"
      :fields="importFields"
      :create-row="(values: Record<string, any>) => createPosition(values)"
      @close="importOpen = false"
      @success="handleImportSuccess"
    />
  </Page>
</template>
