// frontend/admin/react/src/pages/core/auth/sso-callback/index.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Result, Spin, Typography } from 'antd';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';
import { completeSsoLogin } from '@/api/hooks/sso';

const { Text } = Typography;

/**
 * OIDC SSO 回调页：IdP 授权后重定向回 /auth/sso/callback?code=...&state=...，
 * 本页把 code+state 提交后端换本系统 JWT，成功后进首页；失败展示原因并给返回入口。
 */
const SsoCallback: React.FC = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const ranRef = useRef(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // StrictMode 下 effect 双跑：登录是幂等的（state 单次有效），
    // 但二次调用必然因 state 失效而报错，故用 ref 保证只提交一次
    if (ranRef.current) return;
    ranRef.current = true;

    const code = searchParams.get('code') || '';
    const state = searchParams.get('state') || '';

    if (!code || !state) {
      setError('missing code or state');
      return;
    }

    completeSsoLogin(code, state, () => {
      navigate('/', { replace: true });
    }).catch((err: any) => {
      // 原始错误必须留在控制台：展示给用户的是归一化文案
      console.error('sso callback login failed', err);
      setError(err?.message || 'SSO login failed');
    });
  }, [searchParams, navigate]);

  if (error) {
    return (
      <ContentContainer heightMode="auto" padding="24px">
        <Result
          status="error"
          title="SSO 登录失败"
          subTitle={
            <Text type="secondary">{error}</Text>
          }
          extra={
            <a onClick={() => navigate('/auth/login', { replace: true })}>
              返回登录页
            </a>
          }
        />
      </ContentContainer>
    );
  }

  return (
    <ContentContainer heightMode="auto" padding="24px">
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: 80, gap: 16 }}>
        <Spin size="large" />
        <Text type="secondary">SSO 登录中，即将跳转…</Text>
      </div>
    </ContentContainer>
  );
};

export default SsoCallback;

// frontend/admin/vue-element/src/pages/core/login/sso-callback.vue
<template>
  <div class="sso-callback-page">
    <ElResult v-if="error" status="error" :title="t('core.sso.failed')" :sub-title="error">
      <template #extra>
        <ElButton type="primary" @click="router.replace('/login')">
          {{ t("core.sso.backToLogin") }}
        </ElButton>
      </template>
    </ElResult>
    <div v-else class="sso-callback-loading">
      <ElIcon class="is-loading" :size="36"><Loading /></ElIcon>
      <p>{{ t("core.sso.redirecting") }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ElButton, ElIcon, ElMessage, ElResult } from "element-plus";
import { Loading } from "@element-plus/icons-vue";
import { useAuth } from "@/composables/use-auth";
import { useI18n } from "@/core/i18n";
import { DEFAULT_HOME_PATH } from "@/constants";

/**
 * OIDC SSO 回调页：IdP 授权后重定向回 /auth/sso/callback?code=...&state=...，
 * 本页把 code+state 提交后端换本系统 JWT，成功后进首页；失败展示原因并给返回入口。
 */
const route = useRoute();
const router = useRouter();
const { completeSsoLogin } = useAuth();
const { t } = useI18n();

const error = ref("");

onMounted(async () => {
  const code = (route.query.code as string) || "";
  const state = (route.query.state as string) || "";

  if (!code || !state) {
    error.value = t("core.sso.missingParams");
    return;
  }

  try {
    await completeSsoLogin(code, state, async () => {
      await router.replace(DEFAULT_HOME_PATH);
    });
  } catch (err: any) {
    // 原始错误必须留在控制台：展示给用户的是归一化文案
    console.error("sso callback login failed", err);
    error.value = err?.message || t("core.sso.failed");
    ElMessage.error(error.value);
  }
});
</script>

<style lang="scss" scoped>
.sso-callback-page {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  padding: 24px;
}

.sso-callback-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  color: var(--el-text-color-secondary);
}
</style>
