// frontend/admin/vue-vben/apps/admin/src/views/_core/authentication/login.vue
<script lang="ts" setup>
import type { VbenFormSchema } from '@vben/common-ui';

import { computed, h, onMounted, ref } from 'vue';

import { AuthenticationLogin, z } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { message } from 'ant-design-vue';

import { useAuthStore } from '#/stores';
import { fetchGenerateCaptcha } from '#/api/composables';
import { ssoEnabled, startSsoLogin } from '#/api/composables/sso';

defineOptions({ name: 'Login' });

const authStore = useAuthStore();

// 验证码状态
const captchaId = ref('');
const captchaImage = ref('');
const captchaLoading = ref(false);

// SSO 开关（后端未配置 OIDC 时按钮不渲染）
const ssoOn = ref(false);

async function refreshCaptcha() {
  captchaLoading.value = true;
  try {
    const resp = await fetchGenerateCaptcha();
    captchaId.value = resp.captchaId ?? '';
    captchaImage.value = resp.imageBase64 ?? '';
  } catch {
    // 验证码获取失败不阻断页面
  } finally {
    captchaLoading.value = false;
  }
}

onMounted(() => {
  refreshCaptcha();
  // SSO 开关探测：失败/未配置都不显示按钮（非关键路径，静默降级）
  ssoEnabled()
    .then((v) => (ssoOn.value = v))
    .catch(() => (ssoOn.value = false));
});

async function handleSsoLogin() {
  try {
    await startSsoLogin();
  } catch (err: any) {
    // 原始错误必须留在控制台：展示给用户的是归一化文案
    console.error('start sso login failed', err);
    message.error(err?.message || $t('page.sso.failed'));
  }
}

// 验证码图片渲染函数（响应式读取 captchaImage / captchaLoading）
// 作为函数式组件传入 suffix，由 VbenRenderContent 通过 h() 渲染
const renderCaptchaImage = () =>
  h(
    'div',
    {
      title: $t('authentication.captchaRefresh'),
      onClick: () => {
        if (!captchaLoading.value) refreshCaptcha();
      },
      style: {
        height: '36px',
        width: '110px',
        flexShrink: '0',
        cursor: 'pointer',
        borderRadius: '6px',
        overflow: 'hidden',
        border: '1px solid hsl(var(--border))',
        background: 'hsl(var(--input))',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      },
    },
    captchaImage.value
      ? [
          h('img', {
            src: captchaImage.value,
            alt: 'captcha',
            style: {
              height: '100%',
              width: '100%',
              objectFit: 'cover',
            },
          }),
        ]
      : [
          h(
            'span',
            { style: { color: 'var(--muted-foreground)', fontSize: '12px' } },
            captchaLoading.value ? '...' : $t('authentication.captchaRefresh'),
          ),
        ],
  );

const formSchema = computed((): VbenFormSchema[] => {
  return [
    {
      component: 'VbenInput',
      componentProps: {
        placeholder: $t('authentication.tenantCode'),
        autocomplete: 'off',
      },
      fieldName: 'tenant_code',
      label: $t('authentication.tenantCode'),
      rules: z.optional(z.string()),
    },
    {
      component: 'VbenInput',
      componentProps: {
        placeholder: $t('authentication.usernameTip'),
        autocomplete: 'username',
      },
      dependencies: {
        trigger(values) {
          if (values.selectAccount) {
          }
        },
        triggerFields: ['selectAccount'],
      },
      fieldName: 'username',
      label: $t('authentication.username'),
      rules: z.string().min(1, { message: $t('authentication.usernameTip') }),
    },
    {
      component: 'VbenInputPassword',
      componentProps: {
        placeholder: $t('authentication.password'),
        autocomplete: 'current-password',
      },
      fieldName: 'password',
      label: $t('authentication.password'),
      rules: z.string().min(1, { message: $t('authentication.passwordTip') }),
    },
    {
      component: 'VbenInput',
      componentProps: {
        placeholder: $t('authentication.captchaTip'),
        autocomplete: 'off',
        class: 'w-auto flex-1 min-w-0',
      },
      fieldName: 'captchaValue',
      label: $t('authentication.captcha'),
      rules: z.string().min(1, { message: $t('authentication.captchaTip') }),
      suffix: renderCaptchaImage,
    },
  ];
});

// 包装 authLogin：提交时把 captchaId 一并传入
async function handleSubmit(values: Record<string, any>) {
  const result = await authStore.authLogin({
    ...values,
    captchaId: captchaId.value,
  });
  // 登录失败时刷新验证码
  if (!result?.userInfo) {
    refreshCaptcha();
  }
}
</script>

<template>
  <!-- 对齐 react：标题/描述在卡片外，登录表单包一张 24px 圆角卡片（边框 + 主色柔影） -->
  <div>
    <div class="mb-7">
      <h2
        class="text-foreground mb-3 text-3xl font-bold leading-9 tracking-tight lg:text-4xl"
      >
        {{ $t('authentication.welcomeBack') }} 👋🏻
      </h2>
      <p class="text-muted-foreground text-sm lg:text-md">
        {{ $t('authentication.loginSubtitle') }}
      </p>
    </div>

    <div
      class="rounded-3xl border border-border bg-card p-8 shadow-[0_12px_40px_-8px_rgba(0,107,230,0.18)]"
    >
      <AuthenticationLogin
        :form-schema="formSchema"
        :loading="authStore.loginLoading"
        :show-code-login="false"
        :show-forget-password="false"
        :show-qrcode-login="false"
        :show-register="false"
        :show-third-party-login="false"
        @submit="handleSubmit"
      >
        <!-- 内置标题已移到卡片外，置空默认标题块 -->
        <template #title><span class="hidden"></span></template>
      </AuthenticationLogin>

      <template v-if="ssoOn">
        <div class="my-4 flex items-center gap-3">
          <div class="h-px flex-1 bg-border"></div>
          <span class="text-muted-foreground text-xs">{{ $t('page.sso.or') }}</span>
          <div class="h-px flex-1 bg-border"></div>
        </div>
        <a-button block size="large" @click="handleSsoLogin">
          {{ $t('page.sso.button') }}
        </a-button>
      </template>
    </div>
  </div>
</template>

// frontend/admin/react/src/pages/core/auth/login/index.tsx
import React, { useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Form, Input, Button, Checkbox, App } from 'antd';
import { UserOutlined, LockOutlined, SafetyOutlined } from '@ant-design/icons';
import { useAuthStore } from '@/stores';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { fetchGenerateCaptcha } from '@/api';
import { ssoEnabled, startSsoLogin } from '@/api/hooks/sso';

const Login: React.FC = () => {
  const { t } = useTranslation('auth');
  const { login, loginLoading } = useAuthStore();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { message } = App.useApp();

  // 验证码状态
  const [captchaId, setCaptchaId] = useState<string>('');
  const [captchaImage, setCaptchaImage] = useState<string>('');
  const [captchaLoading, setCaptchaLoading] = useState(false);

  // SSO 开关（后端未配置 OIDC 时按钮不渲染）
  const [ssoOn, setSsoOn] = useState(false);

  // 获取验证码
  const refreshCaptcha = useCallback(async () => {
    setCaptchaLoading(true);
    try {
      const resp = await fetchGenerateCaptcha();
      setCaptchaId(resp.captchaId ?? '');
      setCaptchaImage(resp.imageBase64 ?? '');
    } catch {
      // 验证码获取失败不阻断页面，登录时会再次校验
    } finally {
      setCaptchaLoading(false);
    }
  }, []);

  useEffect(() => {
    // React 18 StrictMode 下 effect 会执行两次，导致两个并发的
    // fetchGenerateCaptcha 请求；后到的响应会覆盖先到的 captchaId，
    // 而后端通常一次性消费 captcha，登录时用的 captchaId 可能对应已被
    // 先到请求作废的 captcha。这里用 cancelled 标志位丢弃首次（被 double-invoke
    // 的第一次）请求的结果，确保 state 始终是最后一次请求的值。
    let cancelled = false;
    const run = async () => {
      setCaptchaLoading(true);
      try {
        const resp = await fetchGenerateCaptcha();
        if (cancelled) return;
        setCaptchaId(resp.captchaId ?? '');
        setCaptchaImage(resp.imageBase64 ?? '');
      } catch {
        // 验证码获取失败不阻断页面，登录时会再次校验
      } finally {
        if (!cancelled) setCaptchaLoading(false);
      }
    };
    run();
    return () => {
      cancelled = true;
    };
  }, []);

  // SSO 开关探测：失败/未配置都不显示按钮（非关键路径，静默降级）
  useEffect(() => {
    ssoEnabled().then(setSsoOn).catch(() => setSsoOn(false));
  }, []);

  const handleSubmit = async (values: {
    username: string;
    password: string;
    tenant_code?: string;
    remember?: boolean;
    captcha?: string;
  }) => {
    try {
      // 跳转目标：redirect 参数 → 用户 homePath → 首页。
      // 同源相对路径校验保留，防开放重定向（如 ?redirect=https://evil.com 或 //evil.com）
      const resolveSafeRedirect = () => {
        const rawRedirect =
          searchParams.get('redirect') || useAuthStore.getState().userInfo?.homePath || '/';
        return typeof rawRedirect === 'string' &&
          rawRedirect.startsWith('/') &&
          !rawRedirect.startsWith('//')
          ? rawRedirect
          : '/';
      };

      await login(
        {
          username: values.username,
          password: values.password,
          tenant_code: values.tenant_code,
          grant_type: 'password',
        },
        // 传 onSuccess 后 store 跳过 window.location.href 整页跳转。必须在此同步
        // 导航、赶在 router 重建读取地址之前：isAuthenticated 翻转会让 AppRouter
        // effect 重建 createBrowserRouter（以当时 window.location 为初始地址），
        // 若像旧实现那样 setTimeout 后用旧 router 实例 navigate，只剩一次无感知的
        // pushState——地址栏落在 redirect、页面却渲染 homePath，两边劈叉。
        () => navigate(resolveSafeRedirect()),
        { id: captchaId, value: values.captcha ?? '' },
      );

      message.success(t('loginSuccess'));
    } catch (error: any) {
      // 登录失败后刷新验证码
      refreshCaptcha();
      // 弹出错误提示（与 CRUD 页面统一模式：优先用后端 message，兜底走 i18n）
      message.error(error?.message || t('loginFailed'));
    }
  };

  /**
   * 验证码图片组件，与输入框水平对齐（flex items-center space-x-2）。
   * 点击刷新验证码。高度与输入框统一（h-11）。
   */
  const captchaImageEl = (
    <div
      className="flex items-center justify-center overflow-hidden w-[110px] h-11 shrink-0 rounded-lg cursor-pointer border border-solid bg-white light:border-black/10 light:bg-black/[0.03]"
      title={t('captchaRefresh')}
      onClick={() => !captchaLoading && refreshCaptcha()}
    >
      {captchaImage ? (
        <img
          src={captchaImage}
          alt="captcha"
          className="h-full w-full object-contain"
        />
      ) : (
        <span className="text-slate-400 text-xs">
          {captchaLoading ? '...' : t('captchaRefresh')}
        </span>
      )}
    </div>
  );

  return (
    <div className="w-full max-w-[420px]">
      {/* 标题 */}
      <div className="mb-11">
        <h2 className="text-[34px] font-extrabold tracking-[-0.5px] mb-2.5 text-[color:var(--ant-color-text)]">
          {t('welcomeBack')}
        </h2>
        <p className="text-[15px] leading-relaxed text-[color:var(--ant-color-text-tertiary)]">
          {t('loginDescription')}
        </p>
      </div>

      {/* 登录表单卡片 —— 实底表面色 + 24px 大圆角 + 主色柔影（对齐 vben 认证面板） */}
      <div className="rounded-3xl border border-[color:var(--ant-color-border-secondary)] bg-[color:var(--ant-color-bg-container)] p-8 shadow-[0_12px_40px_-8px_rgba(0,107,230,0.18)]">
        <Form
          name="login"
          onFinish={handleSubmit}
          size="large"
          initialValues={{ remember: true }}
          className="login-form"
        >
          <Form.Item name="tenant_code" className="login-form-item">
            <Input
              prefix={<UserOutlined />}
              placeholder={t('tenantCodePlaceholder')}
              autoComplete="off"
            />
          </Form.Item>

          <Form.Item
            name="username"
            className="login-form-item"
            rules={[
              {
                required: true,
                message: t('usernameRequired'),
              },
            ]}
          >
            <Input
              prefix={<UserOutlined />}
              placeholder={t('usernamePlaceholder')}
              autoComplete="username"
            />
          </Form.Item>

          <Form.Item
            name="password"
            className="login-form-item"
            rules={[
              {
                required: true,
                message: t('passwordRequired'),
              },
            ]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder={t('passwordPlaceholder')}
              autoComplete="current-password"
            />
          </Form.Item>

          {/* 验证码 —— 输入框与图片水平对齐，等高 h-11，flex 布局。
              name 必须挂在直接包裹 Input 的 Form.Item 上：antd 只向唯一子元素注入
              value/onChange，中间隔一层 div 会让验证码值永远进不了表单状态 */}
          <Form.Item className="login-form-item" style={{ marginBottom: 0 }}>
            <div className="flex items-center space-x-2">
              <Form.Item
                name="captcha"
                rules={[
                  {
                    required: true,
                    message: t('captchaRequired'),
                  },
                ]}
                className="flex-1"
                style={{ marginBottom: 0 }}
              >
                <Input
                  prefix={<SafetyOutlined />}
                  placeholder={t('captchaPlaceholder')}
                  autoComplete="off"
                />
              </Form.Item>
              {captchaImageEl}
            </div>
          </Form.Item>

          <Form.Item className="login-remember-item">
            <div className="flex items-center justify-between">
              <Form.Item name="remember" valuePropName="checked" noStyle>
                <Checkbox>{t('rememberAccount')}</Checkbox>
              </Form.Item>
            </div>
          </Form.Item>

          <Form.Item className="login-form-item">
            <Button
              type="primary"
              htmlType="submit"
              loading={loginLoading}
              block
              className="login-submit-btn"
            >
              {loginLoading ? t('loggingIn') : t('loginButton')}
            </Button>
          </Form.Item>
        </Form>

        {ssoOn && (
          <>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, margin: '16px 0' }}>
              <div style={{ flex: 1, height: 1, background: 'var(--ant-color-split)' }} />
              <span style={{ fontSize: 12, color: 'var(--ant-color-text-secondary)' }}>或</span>
              <div style={{ flex: 1, height: 1, background: 'var(--ant-color-split)' }} />
            </div>
            <Button
              block
              size="large"
              onClick={() => {
                startSsoLogin().catch((err: any) => {
                  console.error('start sso login failed', err);
                  message.error(err?.message || t('ssoLoginFailed'));
                });
              }}
            >
              {t('ssoButton')}
            </Button>
          </>
        )}
      </div>

      {/* 底部链接 */}
      <div className="mt-6 text-center text-[13px]">
        <span className="text-[color:var(--ant-color-text-secondary)]">
          {t('noAccount')}{' '}
        </span>
        <a
          href="/auth/forgot-password"
          className="text-[color:var(--ant-color-primary)] hover:opacity-80"
          style={{ fontSize: 13 }}
        >
          {t('forgotPassword')}
        </a>
        
      </div>
    </div>
  );
};

export default Login;
