// frontend/admin/react/src/pages/app/permission/role/components/RoleDrawer.tsx
import { useRef, useState, useEffect } from 'react';
import type { ProFormInstance } from '@ant-design/pro-components';
import {
  DrawerForm,
  ProFormText,
  ProFormDigit,
  ProFormTextArea,
  ProFormRadio,
  ProFormSelect,
  ProFormDependency,
} from '@ant-design/pro-components';
import { App, Tree, Spin, Checkbox } from 'antd';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import type { permissionservicev1_Role as Role } from '@/api/generated/admin/service/v1';
import { useCreateRole, useUpdateRole } from '@/api/hooks/role';
import { fetchListPermissionGroups } from '@/api/hooks/permission-group';
import { fetchListPermissions } from '@/api/hooks/permission';
import { fetchListOrgUnits } from '@/api/hooks/org-unit';
import { PaginationQuery } from '@/core';
import { getStatusOptions, getDataScopeOptions, buildPermissionTree, extractLeafIds, buildOrgUnitTree, getUserFieldPermissionOptions } from '../constants';
import AiGenerateButton from '@/components/common/AiGenerateButton';

interface RoleDrawerProps {
  open: boolean;
  mode: 'create' | 'edit';
  data?: Role;
  onClose: () => void;
  onSuccess: () => void;
}

/**
 * 角色编辑/创建抽屉组件
 */
const RoleDrawer: React.FC<RoleDrawerProps> = ({ open, mode, data, onClose, onSuccess }) => {
  const { t } = useTranslation('role');
  const formRef = useRef<ProFormInstance>(null);
  const queryClient = useQueryClient();
  const { message } = App.useApp();

  const [confirmLoading, setConfirmLoading] = useState(false);
  const [treeData, setTreeData] = useState<any[]>([]);
  const [checkedKeys, setCheckedKeys] = useState<number[]>([]);
  const [treeVersion, setTreeVersion] = useState(0);
  const [treeLoading, setTreeLoading] = useState(false);
  const [unitTreeData, setUnitTreeData] = useState<any[]>([]);
  const [unitCheckedKeys, setUnitCheckedKeys] = useState<number[]>([]);
  const [unitTreeVersion, setUnitTreeVersion] = useState(0);
  // 字段权限：User 资源上勾选隐藏的字段（json_name）
  const [userHiddenFields, setUserHiddenFields] = useState<string[]>([]);

  // 加载权限树数据
  useEffect(() => {
    if (open) {
      setTreeLoading(true);
      Promise.all([
        fetchListPermissionGroups(new PaginationQuery({ formValues: { status: 'ON' } })),
        fetchListPermissions(new PaginationQuery({ formValues: { status: 'ON' } })),
      ])
        .then(([groupRes, permRes]) => {
          const groups = groupRes?.items || [];
          const permissions = permRes?.items || [];
          if (groups.length === 0 && permissions.length > 0) {
            // 无权限组时，直接罗列权限（平铺，不嵌套）
            setTreeData(permissions.map((p) => ({
              key: Number(p.id),
              title: p.name || p.code || String(p.id),
            })));
          } else {
            setTreeData(buildPermissionTree(groups, permissions));
          }
          setTreeVersion((v) => v + 1);
        })
        .catch(() => setTreeData([]))
        .finally(() => setTreeLoading(false));
    }
  }, [open]);

  // 加载组织单元树（SELECTED_UNITS 自定义授权集配置用）
  useEffect(() => {
    if (open) {
      fetchListOrgUnits(new PaginationQuery({ formValues: { status: 'ON' } }))
        .then((res) => {
          setUnitTreeData(buildOrgUnitTree((res?.items || []) as any[]));
          setUnitTreeVersion((v) => v + 1);
        })
        .catch(() => setUnitTreeData([]));
    }
  }, [open]);

  // 编辑模式填充表单
  useEffect(() => {
    if (open && mode === 'edit' && data) {
      setTimeout(() => {
        formRef.current?.setFieldsValue({
          name: data.name || '',
          code: data.code || '',
          sortOrder: (data as any).sortOrder ?? 1,
          status: data.status || 'ON',
          dataScope: data.dataScope || 'ALL',
          description: (data as any).description || '',
        });
      }, 0);
      // 设置已勾选的权限
      const perms = (data as any).permissions;
      if (Array.isArray(perms)) {
        setCheckedKeys(perms.filter((v: any) => typeof v === 'number'));
      }
      // SELECTED_UNITS 时回填已配置的授权单元集
      if (data.dataScope === 'SELECTED_UNITS') {
        const units = (data as any).orgUnits;
        if (Array.isArray(units)) {
          setUnitCheckedKeys(units.filter((v: any) => typeof v === 'number'));
        }
      }
      // 回填字段权限（User 资源的隐藏字段集）
      const fpEntry = Array.isArray((data as any).fieldPermissions)
        ? (data as any).fieldPermissions.find((e: any) => e?.resource === 'User')
        : undefined;
      setUserHiddenFields(
        Array.isArray(fpEntry?.hiddenFields)
          ? fpEntry.hiddenFields.filter((v: any) => typeof v === 'string')
          : [],
      );
    }
  }, [open, mode, data]);

  const createMutation = useCreateRole({
    onSuccess: () => {
      message.success(t('createSuccess'));
      onSuccess();
      onClose();
      queryClient.invalidateQueries({ queryKey: ['listRoles'] });
    },
    onError: (error: Error) => {
      message.error(error.message || t('createFailed'));
    },
  });

  const updateMutation = useUpdateRole({
    onSuccess: () => {
      message.success(t('updateSuccess'));
      onSuccess();
      onClose();
      queryClient.invalidateQueries({ queryKey: ['listRoles'] });
    },
    onError: (error: Error) => {
      message.error(error.message || t('updateFailed'));
    },
  });

  const handleSubmit = async (values: any) => {
    setConfirmLoading(true);
    try {
      const payload = {
        ...values,
        // 用叶子交集剥离权限组父节点 ID（父子联动会自动勾选父节点，
        // 组 ID 混入提交会被后端当作权限 ID，可能越权绑定）。
        permissions: extractLeafIds(checkedKeys, treeData),
      };

      // 仅 SELECTED_UNITS 档提交授权单元集（含清空场景）；
      // 其余档位不携带该字段，后端维持既有集不替换。
      if (values.dataScope === 'SELECTED_UNITS') {
        payload.orgUnits = unitCheckedKeys.filter((v) => typeof v === 'number');
      }

      // 字段权限始终随表单提交（含清空场景）：抽屉所见即保存后的最终态。
      payload.fieldPermissions = userHiddenFields.length > 0
        ? [{ resource: 'User', hiddenFields: userHiddenFields }]
        : [];

      if (mode === 'create') {
        await createMutation.mutateAsync({ data: payload });
      } else if (data?.id) {
        await updateMutation.mutateAsync({ id: data.id, values: payload });
      }
    } finally {
      setConfirmLoading(false);
    }
  };

  return (
    <DrawerForm
      formRef={formRef}
      title={mode === 'create' ? t('create') : t('edit')}
      open={open}
      onOpenChange={(visible) => {
        if (!visible) {
          formRef.current?.resetFields();
          setCheckedKeys([]);
          setUnitCheckedKeys([]);
          setUserHiddenFields([]);
          onClose();
        }
      }}
      initialValues={{
        sortOrder: 1,
        status: 'ON',
        dataScope: 'ALL',
      }}
      onFinish={handleSubmit}
      submitter={{
        searchConfig: {
          submitText: t('common:button.submit'),
          resetText: t('common:button.cancel'),
        },
        submitButtonProps: {
          loading: confirmLoading || createMutation.isPending || updateMutation.isPending,
        },
        resetButtonProps: { onClick: onClose },
      }}
      drawerProps={{ destroyOnHidden: true, onClose, size: 600 }}
    >
      <ProFormText
        name="name"
        label={t('name')}
        placeholder={t('namePlaceholder')}
        rules={[{ required: true, message: t('requiredName') }]}
        fieldProps={{ allowClear: true }}
      />

      <ProFormText
        name="code"
        label={t('code')}
        placeholder={t('codePlaceholder')}
        rules={[{ required: true, message: t('requiredCode') }]}
        fieldProps={{ allowClear: true }}
      />

      <ProFormDigit
        name="sortOrder"
        label={t('sortOrder')}
        placeholder={t('sortOrderPlaceholder')}
        rules={[{ required: true }]}
        fieldProps={{ precision: 0, min: 0 }}
      />

      <ProFormRadio.Group
        name="status"
        label={t('status')}
        rules={[{ required: true, message: t('requiredStatus') }]}
        options={getStatusOptions(t)}
        fieldProps={{ optionType: 'button', buttonStyle: 'solid' }}
      />

      <ProFormSelect
        name="dataScope"
        label={t('dataScope')}
        placeholder={t('dataScopePlaceholder')}
        options={getDataScopeOptions(t)}
        rules={[{ required: true, message: t('requiredDataScope') }]}
        fieldProps={{ allowClear: false }}
      />

      <ProFormDependency name={['dataScope']}>
        {({ dataScope }) =>
          dataScope === 'SELECTED_UNITS' ? (
            <div className="mb-6">
              <label className="block mb-2 text-sm font-medium text-[color:var(--ant-color-text)]">
                {t('orgUnits')}
              </label>
              {unitTreeData.length > 0 ? (
                <div className="rounded-lg border border-white/10 bg-white/5 p-2.5 dark:border-white/8 dark:bg-zinc-800/40">
                  <Tree
                    checkable
                    checkedKeys={unitCheckedKeys}
                    onCheck={(checked) => {
                      setUnitCheckedKeys(checked as number[]);
                    }}
                    treeData={unitTreeData}
                    defaultExpandAll
                    key={unitTreeVersion}
                    className="max-h-80 overflow-auto"
                  />
                </div>
              ) : (
                <div className="rounded-lg border border-dashed border-[color:var(--ant-color-border)] py-4 text-center text-sm text-[color:var(--ant-color-text-quaternary)]">
                  {t('noOrgUnitData')}
                </div>
              )}
            </div>
          ) : null
        }
      </ProFormDependency>

      <ProFormTextArea
        name="description"
        label={
          <span className="inline-flex items-center gap-2">
            {t('description')}
            <AiGenerateButton
              scene="DESCRIPTION"
              size="small"
              onGenerate={(content) => {
                formRef.current?.setFieldValue('description', content);
              }}
            />
          </span>
        }
        placeholder={t('descriptionPlaceholder')}
        fieldProps={{ allowClear: true, rows: 2 }}
      />

      {/* 权限树 */}
      <div className="mb-6">
        <label className="block mb-2 text-sm font-medium text-[color:var(--ant-color-text)]">
          {t('permissions')}
        </label>
        <Spin spinning={treeLoading}>
          {treeData.length > 0 ? (
            <div className="rounded-lg border border-white/10 bg-white/5 p-2.5 dark:border-white/8 dark:bg-zinc-800/40">
              <Tree
                checkable
                checkedKeys={checkedKeys}
                onCheck={(checked) => {
                  setCheckedKeys(checked as number[]);
                }}
                treeData={treeData}
                defaultExpandAll
                key={treeVersion}
                className="max-h-80 overflow-auto"
              />
            </div>
          ) : (
            <div className="rounded-lg border border-dashed border-[color:var(--ant-color-border)] py-4 text-center text-sm text-[color:var(--ant-color-text-quaternary)]">
              {treeLoading ? '' : 'No permission data'}
            </div>
          )}
        </Spin>
      </div>

      {/* 字段权限：勾选 = 对该角色用户隐藏（黑名单语义，User 资源试点） */}
      <div className="mb-6">
        <label className="block mb-2 text-sm font-medium text-[color:var(--ant-color-text)]">
          {t('fieldPerm.title')}
        </label>
        <div className="rounded-lg border border-white/10 bg-white/5 p-2.5 dark:border-white/8 dark:bg-zinc-800/40">
          <p className="mb-2 text-xs text-[color:var(--ant-color-text-quaternary)]">
            {t('fieldPerm.hint')}
          </p>
          <Checkbox.Group
            value={userHiddenFields}
            onChange={(vals) => setUserHiddenFields(vals as string[])}
            options={getUserFieldPermissionOptions(t)}
            className="flex flex-col gap-2"
          />
        </div>
      </div>
    </DrawerForm>
  );
};

export default RoleDrawer;

// frontend/admin/vue-element/src/pages/app/permission/role/role-drawer.vue
<template>
  <ProModal
    v-model:visible="visible"
    :title="title"
    :loading="pageLoading"
    :config="{
      component: 'drawer',
      drawer: { size: DRAWER_WIDTH, closeOnClickModal: false },
    }"
  >
    <ElForm
      ref="formRef"
      v-loading="pageLoading"
      :model="formData"
      :rules="formRules"
      label-width="120px"
      class="drawer-form"
    >
      <!-- 基本信息 -->
      <ElDivider content-position="left">{{ $t("common.section.basic") }}</ElDivider>

      <ElFormItem :label="$t('pages.role.name')" prop="name">
        <ElInput v-model="formData.name" :placeholder="$t('common.placeholder.input')" clearable />
      </ElFormItem>

      <ElFormItem :label="$t('pages.role.code')" prop="code">
        <ElInput v-model="formData.code" :placeholder="$t('common.placeholder.input')" clearable />
      </ElFormItem>

      <ElFormItem :label="$t('common.table.sortOrder')" prop="sortOrder">
        <ElInputNumber
          v-model="formData.sortOrder"
          :min="1"
          :placeholder="$t('common.placeholder.input')"
          style="width: 100%"
        />
      </ElFormItem>

      <ElFormItem :label="$t('common.table.status')" prop="status">
        <ElRadioGroup v-model="formData.status">
          <ElRadioButton v-for="item in statusList" :key="item.value" :value="item.value">
            {{ item.label }}
          </ElRadioButton>
        </ElRadioGroup>
      </ElFormItem>

      <ElFormItem :label="$t('pages.role.dataScope')" prop="dataScope">
        <ElSelect v-model="formData.dataScope" :placeholder="$t('common.placeholder.select')" style="width: 100%">
          <ElOption
            v-for="item in roleDataScopeList"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
        </ElSelect>
      </ElFormItem>

      <!-- SELECTED_UNITS 档位的自定义授权单元集 -->
      <ElFormItem v-if="formData.dataScope === 'SELECTED_UNITS'" :label="$t('pages.role.orgUnits')">
        <template v-if="orgUnitTreeData.length > 0">
          <ElTree
            ref="unitTreeRef"
            :data="orgUnitTreeData"
            node-key="id"
            show-checkbox
            default-expand-all
            :props="{ label: 'name', children: 'children' }"
            style="max-height: 400px; overflow-y: auto"
          />
        </template>
        <div v-else class="org-unit-empty">{{ $t("pages.role.noOrgUnitData") }}</div>
      </ElFormItem>

      <ElFormItem prop="description">
        <template #label>
          <span class="inline-flex items-center">
            {{ $t("common.table.description") }}
            <AiGenerateButton
              scene="DESCRIPTION"
              @generate="(content: string) => (formData.description = content)"
            />
          </span>
        </template>
        <ElInput
          v-model="formData.description"
          type="textarea"
          :rows="3"
          :placeholder="$t('common.placeholder.input')"
        />
      </ElFormItem>

      <!-- 权限配置 -->
      <ElDivider content-position="left">{{ $t("pages.role.permissions") }}</ElDivider>

      <ElFormItem prop="permissions">
        <ElTree
          ref="permissionTreeRef"
          :data="permissionTreeData"
          node-key="key"
          show-checkbox
          default-expand-all
          :props="{ label: 'title', children: 'children' }"
          :filter-node-method="filterPermissionNode"
          style="max-height: 400px; overflow-y: auto"
        >
          <template #default="{ node, data }">
            <span class="custom-tree-node">
              <span>{{ node.label }}</span>
              <span v-if="data.key" class="text-xs text-gray-400 ml-2">{{ data.key }}</span>
            </span>
          </template>
        </ElTree>
      </ElFormItem>

      <!-- 字段权限：勾选 = 对该角色用户隐藏（黑名单语义，User 资源试点） -->
      <ElFormItem :label="$t('pages.role.fieldPerm.title')">
        <div class="field-perm-box">
          <div class="field-perm-hint">{{ $t("pages.role.fieldPerm.hint") }}</div>
          <ElCheckboxGroup v-model="userHiddenFields">
            <ElCheckbox v-for="item in fieldPermOptions" :key="item.value" :value="item.value">
              {{ item.label }}
            </ElCheckbox>
          </ElCheckboxGroup>
        </div>
      </ElFormItem>
    </ElForm>

    <template #footer>
      <div class="drawer-footer">
        <ElButton @click="handleClose">{{ $t("common.button.cancel") }}</ElButton>
        <ElButton type="primary" :loading="submitLoading" @click="handleSubmit">
          {{ $t("common.button.confirm") }}
        </ElButton>
      </div>
    </template>
  </ProModal>
</template>

<script lang="ts" setup>
import { computed, reactive, ref, nextTick } from "vue";
import { ElMessage } from "element-plus";
import type { TreeInstance } from "element-plus";

import ProModal from "@/components/Pro/ProModal/index.vue";
import AiGenerateButton from "@/components/AiGenerateButton/index.vue";

import {
  useCreateRole,
  useUpdateRole,
  fetchListPermissionGroups,
  fetchListPermissions,
  fetchListOrgUnits,
  statusList,
  roleDataScopeList,
  buildPermissionTree,
} from "@/api/composables";
import { PaginationQuery } from "@/core/transport/rest";
import { $t } from "@/core/i18n";
import { DRAWER_WIDTH } from "@/constants";

const emit = defineEmits<{
  success: [];
}>();

const { mutateAsync: createRole } = useCreateRole();
const { mutateAsync: updateRole } = useUpdateRole();

const visible = ref(false);
const submitLoading = ref(false);
const pageLoading = ref(false);
const isCreate = ref(true);
const currentId = ref<number>();
const formRef = ref();
const permissionTreeRef = ref<TreeInstance>();
const unitTreeRef = ref<TreeInstance>();

// 表单数据
const formData = reactive({
  name: "",
  code: "",
  sortOrder: 1,
  status: "ON",
  dataScope: "ALL",
  description: "",
  permissions: [] as number[],
});

// 组织单元树数据（SELECTED_UNITS 档位的自定义授权集）
const orgUnitTreeData = ref<any[]>([]);

// 字段权限：User 资源上勾选隐藏的字段（proto 字段 json_name）
const userHiddenFields = ref<string[]>([]);

// 可勾选字段：value 与后端 identity User proto 字段 json_name 逐字一致，
// 提交后经登录聚合写入令牌，命中字段在响应侧被裁剪。
const fieldPermOptions = [
  { value: "email", label: $t("pages.role.fieldPerm.field.email") },
  { value: "mobile", label: $t("pages.role.fieldPerm.field.mobile") },
  { value: "telephone", label: $t("pages.role.fieldPerm.field.telephone") },
  { value: "address", label: $t("pages.role.fieldPerm.field.address") },
  { value: "region", label: $t("pages.role.fieldPerm.field.region") },
  { value: "lastLoginAt", label: $t("pages.role.fieldPerm.field.lastLoginAt") },
  { value: "lastLoginIp", label: $t("pages.role.fieldPerm.field.lastLoginIp") },
];

// 表单验证规则
const formRules = {
  name: [{ required: true, message: $t("common.validation.required"), trigger: "blur" }],
  code: [{ required: true, message: $t("common.validation.required"), trigger: "blur" }],
  sortOrder: [{ required: true, message: $t("common.validation.required"), trigger: "blur" }],
  status: [{ required: true, message: $t("common.validation.selectRequired"), trigger: "change" }],
  dataScope: [{ required: true, message: $t("common.validation.selectRequired"), trigger: "change" }],
};

// 标题
const title = computed(() =>
  isCreate.value
    ? $t("common.modal.create", { moduleName: $t("pages.role.moduleName") })
    : $t("common.modal.update", { moduleName: $t("pages.role.moduleName") })
);

// 权限树数据
const permissionTreeData = ref<any[]>([]);

// 加载权限树
async function loadPermissionTree() {
  try {
    const groupData = await fetchListPermissionGroups(
      new PaginationQuery({ formValues: { status: "ON" } })
    );
    const groups = groupData.items ?? [];

    const permissionData = await fetchListPermissions(
      new PaginationQuery({ formValues: { status: "ON" } })
    );

    permissionTreeData.value = buildPermissionTree(groups, permissionData.items || []);
  } catch (error) {
    console.error("Failed to load permission tree:", error);
  }
}

// 过滤权限节点
function filterPermissionNode(value: string, data: any) {
  if (!value) return true;
  return data.title?.toLowerCase().includes(value.toLowerCase());
}

// 加载组织单元树（SELECTED_UNITS 档位的自定义授权集配置用）
async function loadOrgUnitTree() {
  try {
    const result = await fetchListOrgUnits(new PaginationQuery({ formValues: { status: "ON" } }));
    orgUnitTreeData.value = result.items || [];
  } catch (error) {
    console.error("Failed to load org unit tree:", error);
  }
}

// 打开抽屉
async function open(data?: { create: boolean; row?: any }) {
  visible.value = true;
  isCreate.value = data?.create ?? true;
  currentId.value = data?.row?.id;

  // 重置表单
  resetForm();

  // 加载树数据（显示加载状态）
  pageLoading.value = true;
  try {
    await loadPermissionTree();
    await loadOrgUnitTree();

    // 如果是编辑模式，填充数据
    if (!isCreate.value && data?.row) {
      // 仅回填表单声明的字段，避免把 id/createdAt/tenantName/tenantId 等
      // 不可变字段灌入 formData，进而被 ...formData 带入提交载荷。
      // （permissions / orgUnits 由树勾选控制，由 setCheckedKeys 回填，不在此赋值）
      formData.name = data.row.name ?? "";
      formData.code = data.row.code ?? "";
      formData.sortOrder = data.row.sortOrder ?? 1;
      formData.status = data.row.status ?? "ON";
      formData.dataScope = data.row.dataScope ?? "ALL";
      formData.description = data.row.description ?? "";

      // 设置树的选中状态
      await nextTick();
      if (data.row.permissions && Array.isArray(data.row.permissions)) {
        permissionTreeRef.value?.setCheckedKeys(data.row.permissions);
      }
      if (formData.dataScope === "SELECTED_UNITS" && Array.isArray(data.row.orgUnits)) {
        unitTreeRef.value?.setCheckedKeys(data.row.orgUnits);
      }

      // 回填字段权限（User 资源的隐藏字段集）
      const fpEntry = Array.isArray(data.row.fieldPermissions)
        ? data.row.fieldPermissions.find((e: any) => e?.resource === "User")
        : undefined;
      userHiddenFields.value = Array.isArray(fpEntry?.hiddenFields)
        ? fpEntry.hiddenFields.filter((v: any) => typeof v === "string")
        : [];
    }
  } finally {
    pageLoading.value = false;
  }
}

// 关闭抽屉
function handleClose() {
  visible.value = false;
  resetForm();
}

// 重置表单
function resetForm() {
  // 先删除所有 formData 上可能被历史 Object.assign 残留的多余 key
  // （id/createdAt/tenantName/tenantId 等），再恢复声明字段的默认值，
  // 确保跨抽屉开启无脏数据残留。
  Object.keys(formData).forEach((k) => {
    delete (formData as any)[k];
  });
  formData.name = "";
  formData.code = "";
  formData.sortOrder = 1;
  formData.status = "ON";
  formData.dataScope = "ALL";
  formData.description = "";
  formData.permissions = [];

  formRef.value?.clearValidate();
  permissionTreeRef.value?.setCheckedKeys([]);
  unitTreeRef.value?.setCheckedKeys([]);
  orgUnitTreeData.value = [];
  userHiddenFields.value = [];
}

// 提交表单
async function handleSubmit() {
  if (!formRef.value) return;

  try {
    await formRef.value.validate();
    submitLoading.value = true;

    // 获取选中的权限ID（只保留数字类型的叶子节点）
    const checkedKeys = permissionTreeRef.value?.getCheckedKeys(false) || [];
    const permissions = checkedKeys.filter((key: any) => typeof key === "number");

    const values: Record<string, any> = {
      ...formData,
      permissions,
    };

    // 仅 SELECTED_UNITS 档提交授权单元集（含清空场景）；
    // 其余档位不携带该字段，后端维持既有集不替换。
    if (formData.dataScope === "SELECTED_UNITS") {
      const unitCheckedKeys = unitTreeRef.value?.getCheckedKeys(false) || [];
      values.orgUnits = unitCheckedKeys.filter((key: any) => typeof key === "number");
    }

    // 字段权限始终随表单提交（含清空场景）：抽屉所见即保存后的最终态。
    values.fieldPermissions =
      userHiddenFields.value.length > 0
        ? [{ resource: "User", hiddenFields: [...userHiddenFields.value] }]
        : [];

    if (isCreate.value) {
      await createRole(values);
      ElMessage.success($t("common.notification.createSuccess"));
    } else {
      await updateRole({ id: currentId.value!, values });
      ElMessage.success($t("common.notification.updateSuccess"));
    }

    emit("success");
    handleClose();
  } catch (error) {
    if (error !== false) {
      // 不是验证错误
      ElMessage.error(
        isCreate.value
          ? $t("common.notification.createFailed")
          : $t("common.notification.updateFailed")
      );
    }
  } finally {
    submitLoading.value = false;
  }
}

// 暴露方法给父组件
defineExpose({
  open,
});
</script>

<style lang="scss" scoped>
.drawer-form {
  padding-right: 10px;
}

.drawer-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

.custom-tree-node {
  display: flex;
  align-items: center;
  flex: 1;
}

.org-unit-empty {
  width: 100%;
  box-sizing: border-box;
  padding: 16px 0;
  text-align: center;
  font-size: 14px;
  border: 1px dashed var(--el-border-color);
  border-radius: var(--el-border-radius-base);
  color: var(--el-text-color-secondary);
}

.field-perm-box {
  width: 100%;
  padding: 10px 12px;
  border: 1px solid var(--el-border-color);
  border-radius: var(--el-border-radius-base);
}

.field-perm-hint {
  margin-bottom: 8px;
  font-size: 12px;
  line-height: 1.5;
  color: var(--el-text-color-secondary);
}
</style>
