// frontend/admin/vue-vben/apps/admin/src/views/app/system/notification_channel/index.vue
<script lang="ts" setup>
import type { VxeGridProps } from '#/adapter/vxe-table';

import { reactive, ref } from 'vue';

import { Page } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { message, notification } from 'ant-design-vue';

import { useVbenVxeGrid } from '#/adapter/vxe-table';
import {
  fetchListNotificationChannels,
  useCreateNotificationChannel,
  useDeleteNotificationChannel,
  useSendTestEmail,
  useUpdateNotificationChannel,
} from '#/api';
import type {
  notification_channelservicev1_NotificationChannel as NotificationChannel,
} from '#/api/generated/admin/service/v1';

const { mutateAsync: createChannel } = useCreateNotificationChannel();
const { mutateAsync: updateChannel } = useUpdateNotificationChannel();
const { mutateAsync: deleteChannel } = useDeleteNotificationChannel();
const { mutateAsync: sendTest } = useSendTestEmail();

const formOptions = {
  collapsed: false,
  showCollapseButton: false,
  submitOnEnter: true,
  schema: [
    {
      component: 'Input',
      fieldName: 'name',
      label: $t('page.notificationChannel.name'),
      componentProps: { allowClear: true },
    },
  ],
};

const gridOptions: VxeGridProps<NotificationChannel> = {
  toolbarConfig: {
    custom: true,
    refresh: true,
    zoom: true,
  },
  height: 'auto',
  pagerConfig: {},
  rowConfig: { isHover: true, keyField: 'id' },
  stripe: true,
  proxyConfig: {
    ajax: {
      query: async ({ page }) => {
        return await fetchListNotificationChannels({
          page: page.currentPage,
          pageSize: page.pageSize,
        });
      },
    },
  },
  columns: [
    { title: $t('ui.table.seq'), type: 'seq', width: 50 },
    { title: $t('page.notificationChannel.name'), field: 'name', minWidth: 140 },
    {
      title: $t('page.notificationChannel.type'),
      field: 'type',
      width: 110,
      slots: { default: 'type' },
    },
    { title: $t('page.notificationChannel.smtpHost'), field: 'smtpHost', minWidth: 150 },
    { title: $t('page.notificationChannel.smtpPort'), field: 'smtpPort', width: 80 },
    { title: $t('page.notificationChannel.smtpFrom'), field: 'smtpFrom', minWidth: 170 },
    {
      title: $t('page.notificationChannel.smtpTls'),
      field: 'smtpTls',
      width: 110,
      slots: { default: 'tls' },
    },
    {
      title: $t('page.notificationChannel.hasPassword'),
      field: 'hasPassword',
      width: 100,
      slots: { default: 'hasPassword' },
    },
    {
      title: $t('page.notificationChannel.enabled'),
      field: 'enabled',
      width: 90,
      slots: { default: 'enabled' },
    },
    {
      title: $t('ui.table.action'),
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      width: 230,
    },
  ],
};

const [Grid, gridApi] = useVbenVxeGrid({ gridOptions, formOptions });

function tlsLabel(mode?: string): string {
  const map: Record<string, string> = {
    NONE: $t('page.notificationChannel.tlsNone'),
    START_TLS: $t('page.notificationChannel.tlsStartTls'),
    SSL: $t('page.notificationChannel.tlsSsl'),
  };
  return (mode && map[mode]) || mode || '-';
}

// ============ 创建/编辑 ============
const editOpen = ref(false);
const editMode = ref<'create' | 'edit'>('create');
const editSaving = ref(false);
const editingId = ref<number>();
const form = reactive({
  name: '',
  type: 'EMAIL',
  smtpHost: '',
  smtpPort: 587,
  smtpUsername: '',
  password: '',
  smtpFrom: '',
  smtpTls: 'START_TLS',
  enabled: true,
  remark: '',
});

function openCreate() {
  editMode.value = 'create';
  editingId.value = undefined;
  Object.assign(form, {
    name: '', type: 'EMAIL', smtpHost: '', smtpPort: 587, smtpUsername: '',
    password: '', smtpFrom: '', smtpTls: 'START_TLS', enabled: true, remark: '',
  });
  editOpen.value = true;
}

function openEdit(row: NotificationChannel) {
  editMode.value = 'edit';
  editingId.value = row.id;
  Object.assign(form, {
    name: row.name || '',
    type: row.type || 'EMAIL',
    smtpHost: row.smtpHost || '',
    smtpPort: row.smtpPort ?? 587,
    smtpUsername: row.smtpUsername || '',
    password: '',
    smtpFrom: row.smtpFrom || '',
    smtpTls: row.smtpTls || 'START_TLS',
    enabled: !!row.enabled,
    remark: row.remark || '',
  });
  editOpen.value = true;
}

async function handleSave() {
  if (!form.name) {
    message.error($t('page.notificationChannel.requiredName'));
    return;
  }
  editSaving.value = true;
  try {
    const { password, ...data } = form as Record<string, any>;
    if (editMode.value === 'create') {
      if (!password) {
        message.error($t('page.notificationChannel.requiredPassword'));
        return;
      }
      await createChannel({ data, password });
      message.success($t('page.notificationChannel.createSuccess'));
    } else if (editingId.value) {
      await updateChannel({
        id: editingId.value,
        data,
        password: password || undefined,
        updateMask:
          'name,smtpHost,smtpPort,smtpUsername,smtpFrom,smtpTls,enabled,remark',
      });
      message.success($t('page.notificationChannel.updateSuccess'));
    }
    editOpen.value = false;
    await gridApi.reload();
  } catch (error: any) {
    message.error(error?.message || $t('page.notificationChannel.saveFailed'));
  } finally {
    editSaving.value = false;
  }
}

// ============ 删除 / 启停 / 测试发送 ============
async function handleDelete(row: NotificationChannel) {
  try {
    await deleteChannel({ id: row.id });
    notification.success({ message: $t('ui.notification.delete_success') });
    await gridApi.reload();
  } catch (error: any) {
    notification.error({ message: error?.message || $t('ui.notification.delete_failed') });
  }
}

async function handleToggleEnabled(row: NotificationChannel) {
  const next = !row.enabled;
  try {
    await updateChannel({
      id: row.id,
      data: { name: row.name, type: row.type, enabled: next },
      updateMask: 'enabled',
    });
    notification.success({ message: $t('ui.notification.update_success') });
    await gridApi.reload();
  } catch (error: any) {
    notification.error({ message: error?.message || $t('ui.notification.update_failed') });
  }
}

const testOpen = ref(false);
const testSaving = ref(false);
const testTarget = ref<NotificationChannel>();
const testRecipient = ref('');

function openTestSend(row: NotificationChannel) {
  testTarget.value = row;
  testRecipient.value = '';
  testOpen.value = true;
}

async function handleTestSend() {
  if (!testTarget.value?.id || !testRecipient.value) return;
  testSaving.value = true;
  try {
    await sendTest({ id: testTarget.value.id, recipient: testRecipient.value });
    notification.success({ message: $t('page.notificationChannel.testSendSuccess') });
    testOpen.value = false;
  } catch (error: any) {
    notification.error({
      message: error?.message || $t('page.notificationChannel.testSendFailed'),
    });
  } finally {
    testSaving.value = false;
  }
}
</script>

<template>
  <Page auto-content-height>
    <Grid :table-title="$t('page.notificationChannel.moduleName')">
      <template #toolbar-tools>
        <a-button type="primary" class="mr-2" @click="openCreate">
          {{ $t('page.notificationChannel.create') }}
        </a-button>
      </template>
      <template #type>
        <a-tag color="blue">{{ $t('page.notificationChannel.typeEmail') }}</a-tag>
      </template>
      <template #tls="{ row }">{{ tlsLabel(row.smtpTls) }}</template>
      <template #hasPassword="{ row }">
        <a-tag v-if="row.hasPassword" color="success">
          {{ $t('page.notificationChannel.passwordSet') }}
        </a-tag>
        <a-tag v-else>{{ $t('page.notificationChannel.passwordNotSet') }}</a-tag>
      </template>
      <template #enabled="{ row }">
        <a-switch
          :checked="row.enabled"
          :checked-children="$t('page.notificationChannel.enabledOn')"
          @click="handleToggleEnabled(row)"
        />
      </template>
      <template #action="{ row }">
        <a-button type="link" size="small" @click.stop="openEdit(row)">
          {{ $t('common.edit') }}
        </a-button>
        <a-button type="link" size="small" @click.stop="openTestSend(row)">
          {{ $t('page.notificationChannel.testSend') }}
        </a-button>
        <a-popconfirm
          :cancel-text="$t('ui.button.cancel')"
          :ok-text="$t('ui.button.ok')"
          :title="$t('page.notificationChannel.deleteConfirm')"
          @confirm="handleDelete(row)"
        >
          <a-button danger type="link" size="small">
            {{ $t('common.delete') }}
          </a-button>
        </a-popconfirm>
      </template>
    </Grid>

    <!-- 创建/编辑 -->
    <a-modal
      v-model:open="editOpen"
      :title="editMode === 'create' ? $t('page.notificationChannel.create') : $t('page.notificationChannel.edit')"
      :confirm-loading="editSaving"
      destroy-on-close
      @ok="handleSave"
    >
      <a-form layout="vertical" class="pt-2">
        <a-form-item :label="$t('page.notificationChannel.name')" required>
          <a-input v-model:value="form.name" />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.type')">
          <a-select v-model:value="form.type" :disabled="editMode === 'edit'">
            <a-select-option value="EMAIL">
              {{ $t('page.notificationChannel.typeEmail') }}
            </a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.smtpHost')">
          <a-input v-model:value="form.smtpHost" placeholder="smtp.example.com" />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.smtpPort')">
          <a-input-number v-model:value="form.smtpPort" :min="1" :max="65535" class="w-full" />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.smtpUsername')">
          <a-input v-model:value="form.smtpUsername" />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.password')">
          <a-input-password
            v-model:value="form.password"
            :placeholder="
              editMode === 'edit'
                ? $t('page.notificationChannel.passwordKeepHint')
                : $t('page.notificationChannel.passwordPlaceholder')
            "
          />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.smtpFrom')">
          <a-input v-model:value="form.smtpFrom" placeholder="noreply@example.com" />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.smtpTls')">
          <a-select v-model:value="form.smtpTls">
            <a-select-option value="NONE">
              {{ $t('page.notificationChannel.tlsNone') }}
            </a-select-option>
            <a-select-option value="START_TLS">
              {{ $t('page.notificationChannel.tlsStartTls') }}
            </a-select-option>
            <a-select-option value="SSL">
              {{ $t('page.notificationChannel.tlsSsl') }}
            </a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.enabled')">
          <a-switch v-model:checked="form.enabled" />
        </a-form-item>
        <a-form-item :label="$t('page.notificationChannel.remark')">
          <a-textarea v-model:value="form.remark" :rows="2" />
        </a-form-item>
      </a-form>
    </a-modal>

    <!-- 测试发送 -->
    <a-modal
      v-model:open="testOpen"
      :title="
        $t('page.notificationChannel.testSendTitle', { name: testTarget?.name || '' })
      "
      :confirm-loading="testSaving"
      @ok="handleTestSend"
    >
      <a-input
        v-model:value="testRecipient"
        class="mt-4"
        :placeholder="$t('page.notificationChannel.testRecipient')"
      />
    </a-modal>
  </Page>
</template>

// frontend/admin/react/src/pages/app/system/notification-channel/index.tsx
import { useRef, useState } from 'react';
import type { ProColumns, ActionType } from '@ant-design/pro-components';
import { ProTable, ModalForm, ProFormText, ProFormDigit, ProFormSelect, ProFormTextArea, ProFormSwitch } from '@ant-design/pro-components';
import { Button, Popconfirm, Tag, App } from 'antd';
import { EditOutlined, DeleteOutlined, PlusOutlined, SendOutlined } from '@ant-design/icons';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import type {
  notification_channelservicev1_NotificationChannel as NotificationChannel,
  notification_channelservicev1_SendTestEmailRequest,
  notification_channelservicev1_CreateNotificationChannelRequest,
  notification_channelservicev1_UpdateNotificationChannelRequest,
} from '@/api/generated/admin/service/v1';
import { PaginationQuery } from '@/core';
import { TABLE } from '@/config/constants';
import {
  fetchListNotificationChannels,
  useDeleteNotificationChannel,
  useSendTestEmail,
  useUpdateNotificationChannel,
  useCreateNotificationChannel,
} from '@/api/hooks/notification-channel';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

/**
 * 通知渠道管理页面（平台级配置）
 * 一期实现 EMAIL（SMTP）渠道：CRUD + 测试发送。
 */
const NotificationChannelManagement = () => {
  const { t } = useTranslation('notification-channel');
  const actionRef = useRef<ActionType>(null);
  const queryClient = useQueryClient();
  const { message } = App.useApp();
  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);

  const [drawerOpen, setDrawerOpen] = useState(false);
  const [drawerMode, setDrawerMode] = useState<'create' | 'edit'>('create');
  const [selected, setSelected] = useState<NotificationChannel | undefined>();
  const [testTarget, setTestTarget] = useState<NotificationChannel | undefined>();

  const refresh = () => {
    actionRef.current?.reload();
    queryClient.invalidateQueries({ queryKey: ['listNotificationChannels'] });
  };

  const deleteMutation = useDeleteNotificationChannel({
    onSuccess: () => {
      message.success(t('deleteSuccess'));
      refresh();
    },
  });

  const createMutation = useCreateNotificationChannel();
  const updateMutation = useUpdateNotificationChannel();
  const testMutation = useSendTestEmail();

  const handleDelete = async (record: NotificationChannel) => {
    if (!record.id) return;
    try {
      await deleteMutation.mutateAsync({ id: record.id });
    } catch (error: any) {
      message.error(error.message || t('deleteFailed'));
    }
  };

  const handleSubmit = async (values: Record<string, any>) => {
    const { password, ...data } = values;
    try {
      if (drawerMode === 'create') {
        const req: notification_channelservicev1_CreateNotificationChannelRequest = {
          data,
          password: password || undefined,
        };
        await createMutation.mutateAsync(req);
        message.success(t('createSuccess'));
      } else if (selected?.id) {
        const req: notification_channelservicev1_UpdateNotificationChannelRequest = {
          id: selected.id,
          data,
          password: password || undefined,
          updateMask:
            'name,type,smtpHost,smtpPort,smtpUsername,smtpFrom,smtpTls,enabled,remark',
        };
        await updateMutation.mutateAsync(req);
        message.success(t('updateSuccess'));
      }
      setDrawerOpen(false);
      refresh();
      return true;
    } catch (error: any) {
      message.error(error.message || t('saveFailed'));
      return false;
    }
  };

  const handleTestSend = async (values: { recipient: string }) => {
    if (!testTarget?.id) return false;
    const req: notification_channelservicev1_SendTestEmailRequest = {
      id: testTarget.id,
      recipient: values.recipient,
    };
    try {
      await testMutation.mutateAsync(req);
      message.success(t('testSendSuccess'));
      setTestTarget(undefined);
      return true;
    } catch (error: any) {
      message.error(error.message || t('testSendFailed'));
      return false;
    }
  };

  const columns: ProColumns<NotificationChannel>[] = [
    {
      title: t('name'),
      dataIndex: 'name',
      width: 150,
      ellipsis: true,
    },
    {
      title: t('type'),
      dataIndex: 'type',
      width: 100,
      render: () => <Tag color="blue">{t('typeEmail')}</Tag>,
    },
    {
      title: t('smtpHost'),
      dataIndex: 'smtpHost',
      width: 160,
      ellipsis: true,
      render: (_, record) => record.smtpHost || '-',
    },
    {
      title: t('smtpPort'),
      dataIndex: 'smtpPort',
      width: 90,
      render: (_, record) => record.smtpPort ?? '-',
    },
    {
      title: t('smtpFrom'),
      dataIndex: 'smtpFrom',
      width: 180,
      ellipsis: true,
      render: (_, record) => record.smtpFrom || '-',
    },
    {
      title: t('smtpTls'),
      dataIndex: 'smtpTls',
      width: 110,
      render: (_, record) => {
        const map: Record<string, string> = {
          NONE: t('tlsNone'),
          START_TLS: t('tlsStartTls'),
          SSL: t('tlsSsl'),
        };
        return map[record.smtpTls || ''] || record.smtpTls || '-';
      },
    },
    {
      title: t('hasPassword'),
      dataIndex: 'hasPassword',
      width: 100,
      render: (_, record) =>
        record.hasPassword ? (
          <Tag color="green">{t('passwordSet')}</Tag>
        ) : (
          <Tag>{t('passwordNotSet')}</Tag>
        ),
    },
    {
      title: t('enabled'),
      dataIndex: 'enabled',
      width: 90,
      render: (_, record) =>
        record.enabled ? <Tag color="success">{t('enabledOn')}</Tag> : <Tag>{t('enabledOff')}</Tag>,
    },
    {
      title: t('remark'),
      dataIndex: 'remark',
      width: 140,
      ellipsis: true,
      hideInTable: window.innerWidth < 1600,
      render: (_, record) => record.remark || '-',
    },
    {
      title: t('actions'),
      valueType: 'option',
      width: 220,
      fixed: 'right',
      render: (_, record) => [
        <Button
          key="edit"
          type="link"
          size="small"
          icon={<EditOutlined />}
          onClick={() => {
            setDrawerMode('edit');
            setSelected(record);
            setDrawerOpen(true);
          }}
        >
          {t('edit')}
        </Button>,
        <Button
          key="test"
          type="link"
          size="small"
          icon={<SendOutlined />}
          onClick={() => setTestTarget(record)}
        >
          {t('testSend')}
        </Button>,
        <Popconfirm key="delete" title={t('deleteConfirm')} onConfirm={() => handleDelete(record)}>
          <Button danger type="link" size="small" icon={<DeleteOutlined />}>
            {t('delete')}
          </Button>
        </Popconfirm>,
      ],
    },
  ];

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      <div ref={containerRef} className="page-container-content">
        <ProTable<NotificationChannel>
          actionRef={actionRef}
          columns={columns}
          request={async (params) => {
            try {
              const query = new PaginationQuery({
                paging: { page: params.current || 1, pageSize: params.pageSize || 20 },
                formValues: Object.fromEntries(
                  Object.entries(params).filter(([key]) => !['current', 'pageSize'].includes(key)),
                ),
              });
              const response = await fetchListNotificationChannels(query);
              return { data: response.items || [], total: response.total || 0, success: true };
            } catch (error: any) {
              message.error(error.message || t('fetchFailed'));
              return { data: [], total: 0, success: false };
            }
          }}
          rowKey="id"
          search={false}
          pagination={{
            defaultPageSize: TABLE.DEFAULT_PAGE_SIZE,
            showSizeChanger: true,
          }}
          options={{ density: true, fullScreen: true, setting: true, reload: true }}
          toolBarRender={() => [
            <Button
              key="create"
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setDrawerMode('create');
                setSelected(undefined);
                setDrawerOpen(true);
              }}
            >
              {t('create')}
            </Button>,
          ]}
          size="middle"
          bordered
          scroll={{ y: tableScrollY, x: 1200 }}
        />
      </div>

      <ModalForm
        title={drawerMode === 'create' ? t('create') : t('edit')}
        width={560}
        open={drawerOpen}
        onOpenChange={setDrawerOpen}
        modalProps={{ destroyOnHidden: true, mask: { closable: false } }}
        submitTimeout={3000}
        onFinish={handleSubmit}
        initialValues={
          drawerMode === 'create'
            ? { type: 'EMAIL', smtpTls: 'START_TLS', smtpPort: 587, enabled: true }
            : { ...selected, password: undefined }
        }
      >
        <ProFormText
          name="name"
          label={t('name')}
          rules={[{ required: true, message: t('requiredName') }]}
        />
        <ProFormSelect
          name="type"
          label={t('type')}
          options={[{ label: t('typeEmail'), value: 'EMAIL' }]}
          disabled={drawerMode === 'edit'}
          rules={[{ required: true }]}
        />
        <ProFormText name="smtpHost" label={t('smtpHost')} placeholder="smtp.example.com" />
        <ProFormDigit name="smtpPort" label={t('smtpPort')} min={1} max={65535} fieldProps={{ precision: 0 }} />
        <ProFormText name="smtpUsername" label={t('smtpUsername')} />
        <ProFormText.Password
          name="password"
          label={t('password')}
          placeholder={drawerMode === 'edit' ? t('passwordKeepHint') : t('passwordPlaceholder')}
          rules={drawerMode === 'create' ? [{ required: true, message: t('requiredPassword') }] : []}
        />
        <ProFormText name="smtpFrom" label={t('smtpFrom')} placeholder="noreply@example.com" />
        <ProFormSelect
          name="smtpTls"
          label={t('smtpTls')}
          options={[
            { label: t('tlsNone'), value: 'NONE' },
            { label: t('tlsStartTls'), value: 'START_TLS' },
            { label: t('tlsSsl'), value: 'SSL' },
          ]}
        />
        <ProFormSwitch name="enabled" label={t('enabled')} />
        <ProFormTextArea name="remark" label={t('remark')} fieldProps={{ rows: 2 }} />
      </ModalForm>

      <ModalForm<{ recipient: string }>
        title={t('testSendTitle', { name: testTarget?.name || '' })}
        width={440}
        open={!!testTarget}
        onOpenChange={(open) => {
          if (!open) setTestTarget(undefined);
        }}
        modalProps={{ destroyOnHidden: true }}
        submitTimeout={5000}
        onFinish={handleTestSend}
      >
        <ProFormText
          name="recipient"
          label={t('testRecipient')}
          rules={[
            { required: true, message: t('requiredRecipient') },
            { type: 'email', message: t('invalidEmail') },
          ]}
          placeholder="you@example.com"
        />
      </ModalForm>
    </ContentContainer>
  );
};

export default NotificationChannelManagement;
