// frontend/admin/vue-element/src/pages/app/system/notification_channel/index.vue
<template>
  <div class="app-container h-full flex flex-1 flex-col">
  <ProPage
    ref="pageRef"
    :config="pageConfig"
    @add="handleAdd"
    @edit="handleEdit"
    @operate="handleOperate"
  >
    <!-- 渠道类型 -->
    <template #type="scope: any">
      <ElTag size="small">{{ t("pages.notification_channel.typeEmail") }}</ElTag>
    </template>

    <!-- 密码配置状态 -->
    <template #hasPassword="scope: any">
      <ElTag v-if="scope.row.hasPassword" type="success" size="small">
        {{ t("pages.notification_channel.passwordSet") }}
      </ElTag>
      <ElTag v-else size="small">{{ t("pages.notification_channel.passwordNotSet") }}</ElTag>
    </template>

    <!-- 启用状态 -->
    <template #enabled="scope: any">
      <ElTag v-if="scope.row.enabled" type="success" size="small">
        {{ t("pages.notification_channel.enabledOn") }}
      </ElTag>
      <ElTag v-else size="small">{{ t("pages.notification_channel.enabledOff") }}</ElTag>
    </template>
  </ProPage>

  <!-- 创建/编辑抽屉 -->
  <NotificationChannelDrawer ref="drawerRef" @success="handleSuccess" />

  <!-- 测试发送对话框 -->
  <ElDialog
    v-model="testVisible"
    :title="t('pages.notification_channel.testSendTitle', { name: testTarget?.name || '' })"
    width="480px"
    align-center
    :close-on-click-modal="false"
    @closed="testTarget = undefined"
  >
    <ElForm ref="testFormRef" :model="testForm" :rules="testRules" label-width="120px">
      <ElFormItem :label="t('pages.notification_channel.testRecipient')" prop="recipient">
        <ElInput v-model="testForm.recipient" placeholder="you@example.com" clearable />
      </ElFormItem>
    </ElForm>
    <template #footer>
      <ElButton @click="testVisible = false">{{ $t("common.button.cancel") }}</ElButton>
      <ElButton type="primary" :loading="testing" @click="handleTestSend">
        {{ t("pages.notification_channel.testSend") }}
      </ElButton>
    </template>
  </ElDialog>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import {
  ElButton,
  ElDialog,
  ElForm,
  ElFormItem,
  ElInput,
  ElMessage,
  ElTag,
} from "element-plus";

import ProPage from "@/components/Pro/ProPage/index.vue";
import type { ProPageConfig } from "@/components/Pro/ProPage/types";
import NotificationChannelDrawer from "./notification-channel-drawer.vue";
import { useI18n } from "@/core/i18n";
import { PaginationQuery } from "@/core/transport/rest";
import type { notification_channelservicev1_NotificationChannel as NotificationChannel } from "@/api/generated/admin/service/v1";
import {
  createPagedExportAction,
  deleteNotificationChannel,
  fetchListNotificationChannels,
  sendTestEmail,
} from "@/api/composables";

const { t } = useI18n();

const pageRef = ref();
const drawerRef = ref();

const tlsLabels: Record<string, string> = {
  NONE: t("pages.notification_channel.tlsNone"),
  START_TLS: t("pages.notification_channel.tlsStartTls"),
  SSL: t("pages.notification_channel.tlsSsl"),
};

function tlsLabel(mode?: string): string {
  return (mode && tlsLabels[mode]) || mode || "-";
}

const pageConfig = computed<ProPageConfig>(() => ({
  skeleton: true,
  exportFilename: "notification-channels",

  table: {
    listAction: async (query: any) => {
      const { page, pageSize, ...rest } = query;
      const result = await fetchListNotificationChannels(
        new PaginationQuery({
          paging: { page: page || 1, pageSize: pageSize || 20 },
          formValues: Object.keys(rest).length > 0 ? rest : undefined,
        }),
      );
      return { items: result.items || [], total: result.total || 0 };
    },
    deleteAction: async (ids: string) => {
      await deleteNotificationChannel(Number(ids));
    },
    exportsAction: createPagedExportAction(fetchListNotificationChannels),
    toolbar: [],
    toolbarRight: ["add"],
    defaultToolbar: ["refresh", "exports", "filter"],
    tableAttrs: { border: true, stripe: true },
    emptyActionText: "common.button.add",
    columns: [
      { type: "index", label: t("common.table.seq"), width: 60 },
      { prop: "name", label: t("pages.notification_channel.name"), minWidth: 140 },
      { prop: "type", label: t("pages.notification_channel.type"), width: 120, slotName: "type" },
      { prop: "smtpHost", label: t("pages.notification_channel.smtpHost"), minWidth: 150 },
      { prop: "smtpPort", label: t("pages.notification_channel.smtpPort"), width: 90 },
      { prop: "smtpFrom", label: t("pages.notification_channel.smtpFrom"), minWidth: 170 },
      {
        prop: "smtpTls",
        label: t("pages.notification_channel.smtpTls"),
        width: 110,
        formatter: (row: any) => tlsLabel(row.smtpTls),
      },
      { prop: "hasPassword", label: t("pages.notification_channel.hasPassword"), width: 100, slotName: "hasPassword" },
      { prop: "enabled", label: t("pages.notification_channel.enabled"), width: 90, slotName: "enabled" },
      { prop: "remark", label: t("pages.notification_channel.remark"), minWidth: 140 },
      {
        prop: "action",
        label: t("common.table.action"),
        fixed: "right",
        width: 170,
        cellType: "tool",
        buttons: [
          { name: "edit", label: t("common.button.edit"), icon: "lucide:pen-line" },
          { name: "test", label: t("pages.notification_channel.testSend"), icon: "lucide:send" },
          {
            name: "delete",
            label: t("common.button.delete"),
            icon: "lucide:trash-2",
            attrs: { type: "danger" },
          },
        ],
      },
    ],
  },
}));

function handleAdd() {
  drawerRef.value?.open({ create: true });
}

function handleEdit(row: NotificationChannel) {
  drawerRef.value?.open({ create: false, row });
}

function handleSuccess() {
  pageRef.value?.refresh();
}

function handleOperate(data: { name: string; row: NotificationChannel }) {
  if (data.name !== "test") return;
  testTarget.value = data.row;
  testForm.value.recipient = "";
  testVisible.value = true;
}

// === 测试发送 ===
const testVisible = ref(false);
const testing = ref(false);
const testFormRef = ref();
const testTarget = ref<NotificationChannel>();
const testForm = ref({ recipient: "" });

const testRules = {
  recipient: [
    { required: true, message: t("pages.notification_channel.requiredRecipient"), trigger: "blur" },
    { type: "email" as const, message: t("pages.notification_channel.invalidEmail"), trigger: "blur" },
  ],
};

async function handleTestSend() {
  if (!testTarget.value?.id) return;
  const valid = await testFormRef.value
    ?.validate()
    .then(() => true, () => false);
  if (!valid) return;
  testing.value = true;
  try {
    await sendTestEmail(testTarget.value.id, testForm.value.recipient);
    ElMessage.success(t("pages.notification_channel.testSendSuccess"));
    testVisible.value = false;
  } catch (error: any) {
    console.error("send test email failed:", error);
    ElMessage.error(error?.message || t("pages.notification_channel.testSendFailed"));
  } finally {
    testing.value = false;
  }
}
</script>

<style lang="scss" scoped>
.app-container {
  padding: 20px;
  width: 100%;
  min-width: 0;
  flex-shrink: 0;
}
</style>

// frontend/admin/react/src/pages/app/system/notification-channel/index.tsx
import { useRef, useState } from 'react';
import type { ProColumns, ActionType } from '@ant-design/pro-components';
import { ProTable, ModalForm, ProFormText, ProFormDigit, ProFormSelect, ProFormTextArea, ProFormSwitch } from '@ant-design/pro-components';
import { Button, Popconfirm, Tag, App } from 'antd';
import { EditOutlined, DeleteOutlined, PlusOutlined, SendOutlined } from '@ant-design/icons';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import type {
  notification_channelservicev1_NotificationChannel as NotificationChannel,
  notification_channelservicev1_SendTestEmailRequest,
  notification_channelservicev1_CreateNotificationChannelRequest,
  notification_channelservicev1_UpdateNotificationChannelRequest,
} from '@/api/generated/admin/service/v1';
import { PaginationQuery } from '@/core';
import { TABLE } from '@/config/constants';
import {
  fetchListNotificationChannels,
  useDeleteNotificationChannel,
  useSendTestEmail,
  useUpdateNotificationChannel,
  useCreateNotificationChannel,
} from '@/api/hooks/notification-channel';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

/**
 * 通知渠道管理页面（平台级配置）
 * 一期实现 EMAIL（SMTP）渠道：CRUD + 测试发送。
 */
const NotificationChannelManagement = () => {
  const { t } = useTranslation('notification-channel');
  const actionRef = useRef<ActionType>(null);
  const queryClient = useQueryClient();
  const { message } = App.useApp();
  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);

  const [drawerOpen, setDrawerOpen] = useState(false);
  const [drawerMode, setDrawerMode] = useState<'create' | 'edit'>('create');
  const [selected, setSelected] = useState<NotificationChannel | undefined>();
  const [testTarget, setTestTarget] = useState<NotificationChannel | undefined>();

  const refresh = () => {
    actionRef.current?.reload();
    queryClient.invalidateQueries({ queryKey: ['listNotificationChannels'] });
  };

  const deleteMutation = useDeleteNotificationChannel({
    onSuccess: () => {
      message.success(t('deleteSuccess'));
      refresh();
    },
  });

  const createMutation = useCreateNotificationChannel();
  const updateMutation = useUpdateNotificationChannel();
  const testMutation = useSendTestEmail();

  const handleDelete = async (record: NotificationChannel) => {
    if (!record.id) return;
    try {
      await deleteMutation.mutateAsync({ id: record.id });
    } catch (error: any) {
      message.error(error.message || t('deleteFailed'));
    }
  };

  const handleSubmit = async (values: Record<string, any>) => {
    const { password, ...data } = values;
    try {
      if (drawerMode === 'create') {
        const req: notification_channelservicev1_CreateNotificationChannelRequest = {
          data,
          password: password || undefined,
        };
        await createMutation.mutateAsync(req);
        message.success(t('createSuccess'));
      } else if (selected?.id) {
        const req: notification_channelservicev1_UpdateNotificationChannelRequest = {
          id: selected.id,
          data,
          password: password || undefined,
        };
        await updateMutation.mutateAsync(req);
        message.success(t('updateSuccess'));
      }
      setDrawerOpen(false);
      refresh();
      return true;
    } catch (error: any) {
      message.error(error.message || t('saveFailed'));
      return false;
    }
  };

  const handleTestSend = async (values: { recipient: string }) => {
    if (!testTarget?.id) return false;
    const req: notification_channelservicev1_SendTestEmailRequest = {
      id: testTarget.id,
      recipient: values.recipient,
    };
    try {
      await testMutation.mutateAsync(req);
      message.success(t('testSendSuccess'));
      setTestTarget(undefined);
      return true;
    } catch (error: any) {
      message.error(error.message || t('testSendFailed'));
      return false;
    }
  };

  const columns: ProColumns<NotificationChannel>[] = [
    {
      title: t('name'),
      dataIndex: 'name',
      width: 150,
      ellipsis: true,
    },
    {
      title: t('type'),
      dataIndex: 'type',
      width: 100,
      render: () => <Tag color="blue">{t('typeEmail')}</Tag>,
    },
    {
      title: t('smtpHost'),
      dataIndex: 'smtpHost',
      width: 160,
      ellipsis: true,
      render: (_, record) => record.smtpHost || '-',
    },
    {
      title: t('smtpPort'),
      dataIndex: 'smtpPort',
      width: 90,
      render: (_, record) => record.smtpPort ?? '-',
    },
    {
      title: t('smtpFrom'),
      dataIndex: 'smtpFrom',
      width: 180,
      ellipsis: true,
      render: (_, record) => record.smtpFrom || '-',
    },
    {
      title: t('smtpTls'),
      dataIndex: 'smtpTls',
      width: 110,
      render: (_, record) => {
        const map: Record<string, string> = {
          NONE: t('tlsNone'),
          START_TLS: t('tlsStartTls'),
          SSL: t('tlsSsl'),
        };
        return map[record.smtpTls || ''] || record.smtpTls || '-';
      },
    },
    {
      title: t('hasPassword'),
      dataIndex: 'hasPassword',
      width: 100,
      render: (_, record) =>
        record.hasPassword ? (
          <Tag color="green">{t('passwordSet')}</Tag>
        ) : (
          <Tag>{t('passwordNotSet')}</Tag>
        ),
    },
    {
      title: t('enabled'),
      dataIndex: 'enabled',
      width: 90,
      render: (_, record) =>
        record.enabled ? <Tag color="success">{t('enabledOn')}</Tag> : <Tag>{t('enabledOff')}</Tag>,
    },
    {
      title: t('remark'),
      dataIndex: 'remark',
      width: 140,
      ellipsis: true,
      hideInTable: window.innerWidth < 1600,
      render: (_, record) => record.remark || '-',
    },
    {
      title: t('actions'),
      valueType: 'option',
      width: 220,
      fixed: 'right',
      render: (_, record) => [
        <Button
          key="edit"
          type="link"
          size="small"
          icon={<EditOutlined />}
          onClick={() => {
            setDrawerMode('edit');
            setSelected(record);
            setDrawerOpen(true);
          }}
        >
          {t('edit')}
        </Button>,
        <Button
          key="test"
          type="link"
          size="small"
          icon={<SendOutlined />}
          onClick={() => setTestTarget(record)}
        >
          {t('testSend')}
        </Button>,
        <Popconfirm key="delete" title={t('deleteConfirm')} onConfirm={() => handleDelete(record)}>
          <Button danger type="link" size="small" icon={<DeleteOutlined />}>
            {t('delete')}
          </Button>
        </Popconfirm>,
      ],
    },
  ];

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      <div ref={containerRef} className="page-container-content">
        <ProTable<NotificationChannel>
          actionRef={actionRef}
          columns={columns}
          request={async (params) => {
            try {
              const query = new PaginationQuery({
                paging: { page: params.current || 1, pageSize: params.pageSize || 20 },
                formValues: Object.fromEntries(
                  Object.entries(params).filter(([key]) => !['current', 'pageSize'].includes(key)),
                ),
              });
              const response = await fetchListNotificationChannels(query);
              return { data: response.items || [], total: response.total || 0, success: true };
            } catch (error: any) {
              message.error(error.message || t('fetchFailed'));
              return { data: [], total: 0, success: false };
            }
          }}
          rowKey="id"
          search={false}
          pagination={{
            defaultPageSize: TABLE.DEFAULT_PAGE_SIZE,
            showSizeChanger: true,
          }}
          options={{ density: true, fullScreen: true, setting: true, reload: true }}
          toolBarRender={() => [
            <Button
              key="create"
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setDrawerMode('create');
                setSelected(undefined);
                setDrawerOpen(true);
              }}
            >
              {t('create')}
            </Button>,
          ]}
          size="middle"
          bordered
          scroll={{ y: tableScrollY, x: 1200 }}
        />
      </div>

      <ModalForm
        title={drawerMode === 'create' ? t('create') : t('edit')}
        width={560}
        open={drawerOpen}
        onOpenChange={setDrawerOpen}
        modalProps={{ destroyOnClose: true, maskClosable: false }}
        submitTimeout={3000}
        onFinish={handleSubmit}
        initialValues={
          drawerMode === 'create'
            ? { type: 'EMAIL', smtpTls: 'START_TLS', smtpPort: 587, enabled: true }
            : { ...selected, password: undefined }
        }
      >
        <ProFormText
          name="name"
          label={t('name')}
          rules={[{ required: true, message: t('requiredName') }]}
        />
        <ProFormSelect
          name="type"
          label={t('type')}
          options={[{ label: t('typeEmail'), value: 'EMAIL' }]}
          disabled={drawerMode === 'edit'}
          rules={[{ required: true }]}
        />
        <ProFormText name="smtpHost" label={t('smtpHost')} placeholder="smtp.example.com" />
        <ProFormDigit name="smtpPort" label={t('smtpPort')} min={1} max={65535} fieldProps={{ precision: 0 }} />
        <ProFormText name="smtpUsername" label={t('smtpUsername')} />
        <ProFormText.Password
          name="password"
          label={t('password')}
          placeholder={drawerMode === 'edit' ? t('passwordKeepHint') : t('passwordPlaceholder')}
          rules={drawerMode === 'create' ? [{ required: true, message: t('requiredPassword') }] : []}
        />
        <ProFormText name="smtpFrom" label={t('smtpFrom')} placeholder="noreply@example.com" />
        <ProFormSelect
          name="smtpTls"
          label={t('smtpTls')}
          options={[
            { label: t('tlsNone'), value: 'NONE' },
            { label: t('tlsStartTls'), value: 'START_TLS' },
            { label: t('tlsSsl'), value: 'SSL' },
          ]}
        />
        <ProFormSwitch name="enabled" label={t('enabled')} />
        <ProFormTextArea name="remark" label={t('remark')} fieldProps={{ rows: 2 }} />
      </ModalForm>

      <ModalForm<{ recipient: string }>
        title={t('testSendTitle', { name: testTarget?.name || '' })}
        width={440}
        open={!!testTarget}
        onOpenChange={(open) => {
          if (!open) setTestTarget(undefined);
        }}
        modalProps={{ destroyOnClose: true }}
        submitTimeout={5000}
        onFinish={handleTestSend}
      >
        <ProFormText
          name="recipient"
          label={t('testRecipient')}
          rules={[
            { required: true, message: t('requiredRecipient') },
            { type: 'email', message: t('invalidEmail') },
          ]}
          placeholder="you@example.com"
        />
      </ModalForm>
    </ContentContainer>
  );
};

export default NotificationChannelManagement;
