// frontend/admin/react/src/pages/app/ai/usage/index.tsx
import { useRef } from 'react';
import type { ProColumns, ActionType } from '@ant-design/pro-components';
import { ProTable } from '@ant-design/pro-components';
import { Progress } from 'antd';
import { useTranslation } from 'react-i18next';
import { PaginationQuery } from '@/core';
import { useGetAiUsageSummary } from '@/api/hooks/ai-usage';
import { fetchListAiUsageLogs } from '@/api/hooks/ai-usage';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';
import { TABLE } from '@/config/constants';

interface UsageRow {
  id?: number;
  modelName?: string;
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  durationMs?: number;
  createdAt?: string;
}

/**
 * AI 用量页：当月汇总（tokens/调用次数/配额进度）+ 用量流水列表。
 * 平台用户见平台侧记录（tenant_id=0）；租户用户由后端租户隔离自动限定本租户。
 */
export default function AiUsagePage() {
  const { t } = useTranslation('aiUsage');
  const actionRef = useRef<ActionType>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);
  const summary = useGetAiUsageSummary();

  const columns: ProColumns<UsageRow>[] = [
    { title: t('model'), dataIndex: 'modelName', minWidth: 160 },
    { title: t('promptTokens'), dataIndex: 'promptTokens', width: 130, render: (v) => Number(v ?? 0).toLocaleString() },
    { title: t('completionTokens'), dataIndex: 'completionTokens', width: 140, render: (v) => Number(v ?? 0).toLocaleString() },
    { title: t('totalTokens'), dataIndex: 'totalTokens', width: 110, render: (v) => Number(v ?? 0).toLocaleString() },
    { title: t('duration'), dataIndex: 'durationMs', width: 100, render: (v) => `${v ?? 0} ms` },
    { title: t('time'), dataIndex: 'createdAt', width: 180, valueType: 'dateTime' },
  ];

  const summaryData = summary.data;
  const quotaPct =
    summaryData?.quotaConfigured && (summaryData.quotaLimit ?? 0) > 0
      ? Math.min(100, Math.round(((summaryData.monthTokens ?? 0) * 100) / (summaryData.quotaLimit || 1)))
      : 0;

  const cards = [
    {
      label: t('summary.monthTokens'),
      value: (summaryData?.monthTokens ?? 0).toLocaleString(),
      color: 'text-blue-500',
    },
    {
      label: t('summary.monthCalls'),
      value: (summaryData?.monthCalls ?? 0).toLocaleString(),
      color: 'text-cyan-500',
    },
  ];

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      <div ref={containerRef} className="page-container-content">
        {/* 汇总卡 */}
        <div className="mb-4 grid grid-cols-1 gap-4 sm:grid-cols-3">
          {cards.map((c) => (
            <div
              key={c.label}
              className="rounded-xl border border-solid border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900"
            >
              <div className="mb-2 text-sm text-gray-400">{c.label}</div>
              <div className={`text-2xl font-semibold tabular-nums ${c.color}`}>{c.value}</div>
            </div>
          ))}
          <div className="rounded-xl border border-solid border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
            <div className="mb-2 text-sm text-gray-400">{t('summary.quota')}</div>
            {summaryData?.quotaConfigured ? (
              <>
                <Progress percent={quotaPct} status={quotaPct > 80 ? 'exception' : 'normal'} />
                <div className="mt-1 text-xs text-gray-400">
                  {(summaryData.monthTokens ?? 0).toLocaleString()} / {(summaryData.quotaLimit ?? 0).toLocaleString()}
                </div>
              </>
            ) : (
              <div className="text-2xl font-semibold text-gray-400">∞</div>
            )}
          </div>
        </div>

        {/* 流水列表 */}
        <ProTable<UsageRow>
          actionRef={actionRef}
          rowKey="id"
          search={false}
          scroll={{ y: tableScrollY, x: 800 }}
          request={async (params) => {
            try {
              const { current, pageSize } = params;
              const query = new PaginationQuery({
                paging: { page: current || 1, pageSize: pageSize || TABLE.DEFAULT_PAGE_SIZE },
              });
              const res = await fetchListAiUsageLogs(query);
              return { data: res.items || [], total: res.total || 0, success: true };
            } catch (error) {
              console.error('fetch ai usage logs failed:', error);
              return { data: [], total: 0, success: false };
            }
          }}
          columns={columns}
          toolBarRender={false}
        />
      </div>
    </ContentContainer>
  );
}

// frontend/admin/vue-element/src/pages/app/ai/usage/index.vue
<template>
  <div class="app-container h-full flex flex-1 flex-col">
    <!-- 汇总卡 -->
    <el-row :gutter="16" class="mb-4">
      <el-col v-for="m in metricItems" :key="m.label" :xs="24" :sm="8">
        <el-card shadow="hover">
          <div class="metric-label">{{ m.label }}</div>
          <div class="metric-value" :style="{ color: m.color }">{{ m.value }}</div>
          <el-progress
            v-if="m.progress !== undefined"
            :percentage="m.progress"
            :status="m.progress > 80 ? 'exception' : 'success'"
          />
        </el-card>
      </el-col>
    </el-row>

    <!-- 流水列表 -->
    <el-card shadow="hover" class="flex-1">
      <el-table :data="usageRows" size="small" v-loading="loading" border stripe>
        <el-table-column prop="modelName" :label="t('pages.ai_usage.model')" min-width="160" show-overflow-tooltip />
        <el-table-column prop="promptTokens" :label="t('pages.ai_usage.promptTokens')" width="120" />
        <el-table-column prop="completionTokens" :label="t('pages.ai_usage.completionTokens')" width="130" />
        <el-table-column prop="totalTokens" :label="t('pages.ai_usage.totalTokens')" width="110" />
        <el-table-column :label="t('pages.ai_usage.duration')" width="100">
          <template #default="{ row }">{{ row.durationMs || 0 }} ms</template>
        </el-table-column>
        <el-table-column prop="createdAt" :label="t('pages.ai_usage.time')" width="180" />
      </el-table>
      <div class="mt-3 flex justify-end">
        <el-pagination
          v-model:current-page="page"
          :page-size="20"
          layout="total, prev, pager, next"
          :total="total"
          @current-change="loadRows"
        />
      </div>
    </el-card>
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref } from "vue";
import { ElCard, ElCol, ElProgress, ElRow, ElTable, ElTableColumn, ElPagination } from "element-plus";
import { useI18n } from "@/core/i18n";
import { PaginationQuery } from "@/core/transport/rest";
import { apiClient } from "@/api/client";

const { t } = useI18n();

const monthTokens = ref(0);
const monthCalls = ref(0);
const quotaConfigured = ref(false);
const quotaLimit = ref(0);

const usageRows = ref<Record<string, any>[]>([]);
const total = ref(0);
const page = ref(1);
const loading = ref(false);

const metricItems = computed(() => {
  const pct = quotaConfigured.value && quotaLimit.value > 0
    ? Math.min(100, Math.round((monthTokens.value * 100) / quotaLimit.value))
    : undefined;
  return [
    { label: t("pages.ai_usage.monthTokens"), value: monthTokens.value.toLocaleString(), color: "#3b82f6", progress: pct },
    { label: t("pages.ai_usage.monthCalls"), value: monthCalls.value.toLocaleString(), color: "#22d3ee", progress: undefined },
    { label: t("pages.ai_usage.quota"), value: quotaConfigured.value ? quotaLimit.value.toLocaleString() : "∞", color: "#a78bfa", progress: undefined },
  ];
});

async function loadSummary() {
  try {
    const resp = await apiClient.aiUsageLogService.GetUsageSummary({});
    monthTokens.value = resp.monthTokens ?? 0;
    monthCalls.value = resp.monthCalls ?? 0;
    quotaConfigured.value = resp.quotaConfigured ?? false;
    quotaLimit.value = resp.quotaLimit ?? 0;
  } catch (error: any) {
    console.error("load usage summary failed:", error);
  }
}

async function loadRows() {
  loading.value = true;
  try {
    const resp = await apiClient.aiUsageLogService.List(
        new PaginationQuery({ paging: { page: page.value, pageSize: 20 } }).toRawParams(),
      );
    usageRows.value = (resp.items || []) as Record<string, any>[];
    total.value = Number(resp.total || 0);
  } catch (error: any) {
    console.error("load usage rows failed:", error);
  } finally {
    loading.value = false;
  }
}

onMounted(() => {
  loadSummary();
  loadRows();
});
</script>

<style lang="scss" scoped>
.metric-label {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  margin-bottom: 6px;
}

.metric-value {
  font-size: 24px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}
</style>
