// frontend/admin/vue-element/src/pages/app/dashboard/analytics/ai-insights-card.vue
<template>
  <el-card shadow="hover" class="ai-insights-card mb-5">
    <template #header>
      <div class="card-header-tabs">
        <span class="card-title">
          <SvgIcon icon="svg:color_bell" :size="18" class="mr-1" />
          {{ t("pages.dashboard.aiInsights.title") }}
        </span>
        <el-button
          type="primary"
          size="small"
          :loading="insightsLoading"
          @click="handleScan"
        >
          {{ insights ? t("pages.dashboard.aiInsights.rescan") : t("pages.dashboard.aiInsights.scan") }}
        </el-button>
      </div>
    </template>

    <!-- 未扫描空态 -->
    <div v-if="!insights && !insightsLoading" class="empty-tip">
      {{ t("pages.dashboard.aiInsights.empty") }}
    </div>

    <template v-else>
      <!-- 指标带 -->
      <div class="metric-band">
        <div v-for="m in metricItems" :key="m.label" class="metric-block">
          <div class="metric-label">{{ m.label }}</div>
          <div class="metric-value" :style="{ color: m.color }">{{ m.value }}</div>
        </div>
      </div>

      <!-- 中排：登录趋势 mini 图 + 失败率 -->
      <div class="mid-grid">
        <div class="mid-block">
          <div class="block-label">{{ t("pages.dashboard.aiInsights.trend7d") }}</div>
          <AnalyticsTrends :data="trend" />
        </div>
        <div class="mid-block">
          <div class="block-label">{{ t("pages.dashboard.aiInsights.failRate") }}</div>
          <div class="fail-rate" :class="failRate > 20 ? 'is-high' : 'is-ok'">{{ failRate }}%</div>
          <div class="action-bars">
            <div v-for="a in actionBars" :key="a.label" class="action-bar">
              <span class="action-name">{{ a.label }}</span>
              <div class="action-track">
                <div class="action-fill" :style="{ width: a.pct + '%', background: a.color }" />
              </div>
              <span class="action-count">{{ a.count }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- AI 洞察要点（结构化告警，文案按界面语言由 i18n 模板渲染） -->
      <div v-if="alertItems.length > 0" class="alert-list">
        <div v-for="(a, i) in alertItems" :key="i" class="alert-item">
          <span class="alert-bar" :class="'sev-' + a.severity.toLowerCase()" />
          <div>
            <div class="alert-title">
              <el-tag :type="a.tagType" size="small">{{ a.severity }}</el-tag>
              {{ a.title }}
            </div>
            <div class="alert-detail">{{ a.detail }}</div>
          </div>
        </div>
      </div>

      <!-- LLM 总体评估（按请求语言生成） -->
      <div v-if="insights?.summary" class="assessment">
        <div class="block-label">{{ t("pages.dashboard.aiInsights.assessment") }}</div>
        <div class="assessment-text">{{ insights.summary }}</div>
      </div>
    </template>
  </el-card>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import { ElButton, ElCard, ElMessage, ElTag } from "element-plus";
import { useI18n } from "@/core/i18n";
import { apiClient } from "@/api/client";
import AnalyticsTrends from "./analytics-trends.vue";
import type {
  AiInsightAlert,
  AiInsightsResponse,
  LoginTrendResponse,
} from "@/api/generated/admin/service/v1";
import { i18n } from "@/core/i18n";

// 指标/趋势/分布数据由父页面注入（复用页面已有的 dashboard 查询缓存，避免重复请求）
const props = defineProps<{
  overview?: {
    todayLoginCount?: number;
    todayOperationCount?: number;
    userCount?: number;
    roleCount?: number;
  };
  trend?: LoginTrendResponse;
  actions?: { label?: string; count?: number }[];
  statusItems?: { label?: string; count?: number }[];
}>();

const { t } = useI18n();

const insights = ref<AiInsightsResponse>();
const insightsLoading = ref(false);

const metricItems = computed(() => [
  { label: t("pages.dashboard.todayLoginCount"), value: props.overview?.todayLoginCount ?? 0, color: "#3b82f6" },
  { label: t("pages.dashboard.todayOperationCount"), value: props.overview?.todayOperationCount ?? 0, color: "#22d3ee" },
  { label: t("pages.dashboard.userCount"), value: props.overview?.userCount ?? 0, color: "#a78bfa" },
  { label: t("pages.dashboard.roleCount"), value: props.overview?.roleCount ?? 0, color: "#34d399" },
]);

const failRate = computed(() => {
  const items = props.statusItems || [];
  const succ = items.find((s) => s.label === "SUCCESS")?.count || 0;
  const fail = items.find((s) => s.label === "FAILED")?.count || 0;
  return succ + fail > 0 ? Math.round((fail * 100) / (succ + fail)) : 0;
});

const ACTION_COLORS: Record<string, string> = {
  CREATE: "#3b82f6",
  UPDATE: "#22d3ee",
  DELETE: "#ef4444",
  EXPORT: "#a78bfa",
  ASSIGN: "#34d399",
  IMPORT: "#fbbf24",
  OTHER: "#94a3b8",
};

const actionBars = computed(() => {
  const items = props.actions || [];
  const total = items.reduce((sum, a) => sum + (a.count || 0), 0) || 1;
  return items
    .slice()
    .sort((a, b) => (b.count || 0) - (a.count || 0))
    .map((a) => ({
      label: a.label || "-",
      count: a.count || 0,
      pct: Math.round(((a.count || 0) * 100) / total),
      color: ACTION_COLORS[a.label || ""] || "#94a3b8",
    }));
});

const alertItems = computed(() => {
  const alerts = (insights.value?.alerts || []) as AiInsightAlert[];
  return alerts.map((a) => ({
    severity: a.severity || "LOW",
    tagType: (a.severity === "HIGH" ? "danger" : a.severity === "MEDIUM" ? "warning" : "info") as "danger" | "warning" | "info",
    title: renderTemplate(a),
    detail: detailText(a),
  }));
});

/** 告警文案：后端只回结构化事实（type+facts），标题/明细由前端 i18n 模板插值渲染。 */
function renderTemplate(alert: AiInsightAlert): string {
  const templates: Record<string, string> = {
    BRUTE_FORCE: t("pages.dashboard.aiInsights.bruteForceTitle", alert.facts || {}),
    NIGHT_OPS: t("pages.dashboard.aiInsights.nightOpsTitle", alert.facts || {}),
    FAILED_OPS: t("pages.dashboard.aiInsights.failedOpsTitle", alert.facts || {}),
    SENSITIVE_OPS: t("pages.dashboard.aiInsights.sensitiveOpsTitle", alert.facts || {}),
  };
  return templates[alert.type || ""] || alert.type || "";
}

function detailText(alert: AiInsightAlert): string {
  const templates: Record<string, string> = {
    BRUTE_FORCE: t("pages.dashboard.aiInsights.bruteForceDetail", alert.facts || {}),
    NIGHT_OPS: t("pages.dashboard.aiInsights.nightOpsDetail", alert.facts || {}),
    FAILED_OPS: t("pages.dashboard.aiInsights.failedOpsDetail", alert.facts || {}),
  };
  return templates[alert.type || ""] || "";
}

async function handleScan() {
  insightsLoading.value = true;
  try {
    const locale = i18n.global.locale as unknown as { value?: string };
    const lang = locale?.value || "zh-CN";
    insights.value = await apiClient.dashboardService.GetAiInsights({ lang } as any);
  } catch (error: any) {
    console.error("dashboard ai insights failed:", error);
    ElMessage.error(error?.message || t("pages.dashboard.aiInsights.failed"));
  } finally {
    insightsLoading.value = false;
  }
}
</script>

<style lang="scss" scoped>
.card-header-tabs {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.metric-band {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
  margin-bottom: 16px;
}

.metric-block {
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  padding: 8px 12px;
}

.metric-label {
  font-size: 12px;
  color: var(--el-text-color-secondary);
}

.metric-value {
  font-size: 22px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}

.mid-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
  margin-bottom: 16px;
}

.mid-block {
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  padding: 8px 12px;
}

.block-label {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  margin-bottom: 4px;
}

.fail-rate {
  font-size: 26px;
  font-weight: 600;

  &.is-high {
    color: var(--el-color-danger);
  }

  &.is-ok {
    color: var(--el-color-success);
  }
}

.action-bars {
  margin-top: 8px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.action-bar {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}

.action-name {
  width: 64px;
  color: var(--el-text-color-secondary);
}

.action-track {
  flex: 1;
  height: 6px;
  border-radius: 3px;
  overflow: hidden;
  background: rgba(128, 128, 128, 0.15);
}

.action-fill {
  height: 100%;
  border-radius: 3px;
}

.action-count {
  width: 32px;
  text-align: right;
  color: var(--el-text-color-secondary);
}

.empty-tip {
  color: var(--el-text-color-secondary);
  padding: 8px 0;
}

.alert-list {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.alert-item {
  display: flex;
  gap: 10px;
  border: 1px solid var(--el-border-color-lighter);
  border-radius: 8px;
  padding: 10px 12px;
}

.alert-bar {
  width: 4px;
  border-radius: 2px;
  flex-shrink: 0;

  &.sev-high {
    background: var(--el-color-danger);
  }

  &.sev-medium {
    background: var(--el-color-warning);
  }

  &.sev-low {
    background: var(--el-color-primary);
  }
}

.alert-title {
  font-weight: 500;
  margin-bottom: 4px;
  display: flex;
  align-items: center;
  gap: 6px;
}

.alert-detail {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  line-height: 1.6;
}

.assessment {
  margin-top: 12px;
  padding-top: 8px;
  border-top: 1px solid var(--el-border-color-lighter);
}

.assessment-text {
  margin-top: 4px;
  line-height: 1.7;
}
</style>

// frontend/admin/react/src/pages/app/dashboard/components/AiInsightsCard.tsx
import { useState } from 'react';
import { Button, Skeleton, Typography, App } from 'antd';
import { RobotOutlined, ThunderboltOutlined } from '@ant-design/icons';
import { useMutation } from '@tanstack/react-query';
import ReactECharts from 'echarts-for-react';
import { useI18n } from '@/core/i18n';
import { apiClient } from '@/api/client';
import {
  useDashboardOverview,
  useLoginTrend,
  useLoginStatusDistribution,
  useOperationActionDistribution,
} from '@/api/hooks/dashboard';

/** 动作分布横条的语义色（与 SourceDonutChart 色系一致）。 */
const ACTION_COLORS: Record<string, string> = {
  CREATE: '#3b82f6',
  UPDATE: '#22d3ee',
  DELETE: '#ef4444',
  EXPORT: '#a78bfa',
  ASSIGN: '#34d399',
  IMPORT: '#fbbf24',
  OTHER: '#94a3b8',
};

/**
 * AI 数据报告卡片（dashboard）：
 * 图文结构化展示 —— 指标带 + 7 天登录迷你趋势 + 失败率/动作分布 + AI 洞察要点。
 * 统计图由前端结构化渲染（复用页面已有的 query 缓存），LLM 只负责洞察要点文字；
 * 平台用户专属（后端对租户返回 403——解读会把数据外发到模型端点）。
 */
const AiInsightsCard = () => {
  const { t } = useI18n('dashboard');
  const { message } = App.useApp();
  const [insights, setInsights] = useState<string[]>([]);
  const [generatedAt, setGeneratedAt] = useState('');

  const overviewQuery = useDashboardOverview();
  const trendQuery = useLoginTrend(7);
  const actionDistQuery = useOperationActionDistribution();
  const statusDistQuery = useLoginStatusDistribution();

  const insightsMutation = useMutation({
    mutationFn: () => apiClient.dashboardService.GetAiInsights({}),
    onSuccess: (resp) => {
      setInsights(resp.insights ?? []);
      setGeneratedAt(new Date().toLocaleTimeString());
    },
    onError: (error: Error) => {
      console.error('dashboard ai insights failed:', error);
      message.error(error.message || t('aiInsights.failed'));
    },
  });

  const d = overviewQuery.data;
  const trendPoints = trendQuery.data?.points ?? [];
  const actions = (actionDistQuery.data?.items ?? []).slice().sort((a, b) => (b.count ?? 0) - (a.count ?? 0));
  const actionTotal = actions.reduce((sum, a) => sum + (a.count ?? 0), 0) || 1;
  const statusItems = statusDistQuery.data?.items ?? [];
  const succ = statusItems.find((s) => s.label === 'SUCCESS')?.count ?? 0;
  const fail = statusItems.find((s) => s.label === 'FAILED')?.count ?? 0;
  const failRate = succ + fail > 0 ? Math.round((fail * 100) / (succ + fail)) : 0;

  const miniMetrics = [
    { label: t('stats.todayLoginCount'), value: d?.todayLoginCount ?? 0, color: '#3b82f6' },
    { label: t('stats.todayOperationCount'), value: d?.todayOperationCount ?? 0, color: '#22d3ee' },
    { label: t('stats.userCount'), value: d?.userCount ?? 0, color: '#a78bfa' },
    { label: t('stats.roleCount'), value: d?.roleCount ?? 0, color: '#34d399' },
  ];

  const trendOption = {
    grid: { left: 8, right: 8, top: 6, bottom: 18, containLabel: false },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: trendPoints.map((p) => p.date?.slice(5)),
      axisLine: { lineStyle: { color: 'rgba(128,128,128,0.2)' } },
      axisTick: { show: false },
      axisLabel: { show: false },
    },
    yAxis: { type: 'value', splitLine: { show: false }, axisLabel: { show: false } },
    tooltip: { trigger: 'axis' },
    series: [
      {
        type: 'line',
        smooth: true,
        symbol: 'none',
        data: trendPoints.map((p) => p.count),
        lineStyle: { width: 2, color: '#3b82f6' },
        areaStyle: {
          color: {
            type: 'linear', x: 0, y: 0, x2: 0, y2: 1,
            colorStops: [
              { offset: 0, color: 'rgba(59,130,246,0.35)' },
              { offset: 1, color: 'rgba(59,130,246,0.02)' },
            ],
          },
        },
      },
    ],
  };

  return (
    <div
      className={
        'group relative h-full overflow-hidden rounded-xl border border-white/8 ' +
        'bg-[color:var(--ant-color-bg-container)] p-5 transition-all duration-200 ' +
        'hover:border-white/15 hover:shadow-[0_8px_24px_rgba(0,0,0,0.35)]'
      }
    >
      {/* 左上角主色微光，与 StatsCard 同一装饰语言 */}
      <div
        className={
          'pointer-events-none absolute -top-10 -left-10 h-28 w-28 rounded-full ' +
          'bg-gradient-to-br from-blue-500/10 to-transparent opacity-60 blur-2xl'
        }
      />

      {/* 头部：标题 + 生成时间 + 生成按钮 */}
      <div className="relative mb-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-500/12 text-blue-400">
            <RobotOutlined style={{ fontSize: 18 }} />
          </div>
          <div>
            <div className="text-sm font-semibold text-[color:var(--ant-color-text)]">
              {t('aiInsights.title')}
            </div>
            {generatedAt && (
              <div className="text-xs text-[color:var(--ant-color-text-tertiary)]">
                {t('aiInsights.generatedAt', { time: generatedAt })}
              </div>
            )}
          </div>
        </div>
        <Button
          type="primary"
          icon={<ThunderboltOutlined />}
          loading={insightsMutation.isPending}
          onClick={() => insightsMutation.mutate()}
        >
          {insights.length > 0 ? t('aiInsights.regenerate') : t('aiInsights.generate')}
        </Button>
      </div>

      {insightsMutation.isPending && insights.length === 0 ? (
        <Skeleton active paragraph={{ rows: 5 }} />
      ) : insights.length === 0 ? (
        <Typography.Text type="secondary">{t('aiInsights.empty')}</Typography.Text>
      ) : (
        <>
          {/* 指标带 */}
          <div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
            {miniMetrics.map((m) => (
              <div key={m.label} className="rounded-lg border border-solid border-white/8 px-3 py-2">
                <div className="text-xs text-[color:var(--ant-color-text-secondary)]">{m.label}</div>
                <div className="text-xl font-semibold tabular-nums" style={{ color: m.color }}>
                  {m.value.toLocaleString()}
                </div>
              </div>
            ))}
          </div>

          {/* 中排：登录趋势 mini 图 + 失败率/动作分布 */}
          <div className="mb-4 grid grid-cols-1 gap-4 lg:grid-cols-2">
            <div className="rounded-lg border border-solid border-white/8 p-3">
              <div className="mb-1 text-xs text-[color:var(--ant-color-text-secondary)]">
                {t('aiInsights.trend7d')}
              </div>
              <ReactECharts option={trendOption} style={{ height: 110 }} notMerge lazyUpdate />
            </div>
            <div className="rounded-lg border border-solid border-white/8 p-3">
              <div className="mb-2 flex items-baseline justify-between">
                <span className="text-xs text-[color:var(--ant-color-text-secondary)]">
                  {t('aiInsights.failRate')}
                </span>
                <span
                  className="text-lg font-semibold tabular-nums"
                  style={{ color: failRate > 20 ? '#ef4444' : '#34d399' }}
                >
                  {failRate}%
                </span>
              </div>
              <div className="space-y-2">
                {actions.map((a) => {
                  const pct = Math.round(((a.count ?? 0) * 100) / actionTotal);
                  return (
                    <div key={a.label} className="flex items-center gap-2">
                      <span className="w-16 shrink-0 text-xs text-[color:var(--ant-color-text-secondary)]">
                        {a.label}
                      </span>
                      <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-gray-500/15">
                        <div
                          className="h-full rounded-full"
                          style={{ width: `${pct}%`, background: ACTION_COLORS[a.label ?? ''] ?? '#94a3b8' }}
                        />
                      </div>
                      <span className="w-10 shrink-0 text-right text-xs tabular-nums text-[color:var(--ant-color-text-secondary)]">
                        {a.count}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* AI 洞察要点 */}
          <div>
            <div className="mb-2 text-xs text-[color:var(--ant-color-text-secondary)]">
              {t('aiInsights.points')}
            </div>
            <div className="space-y-1.5">
              {insights.map((point, i) => (
                <div key={i} className="flex items-start gap-2 text-sm leading-relaxed">
                  <span
                    className="mt-1.5 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-blue-500"
                  />
                  <span className="text-[color:var(--ant-color-text)]">{point}</span>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
};

export default AiInsightsCard;
