// frontend/admin/vue-element/src/pages/app/notification/template/index.vue
<template>
  <div class="app-container h-full flex flex-1 flex-col">
    <ProPage
      ref="pageRef"
      :config="pageConfig"
      @add="handleAdd"
      @edit="handleEdit"
      @operate="handleOperate"
    >
      <!-- 编码：等宽呈现，强调它是被引用的锚 -->
      <template #code="scope: any">
        <ElTag v-if="scope.row.code" size="small" round effect="plain">
          {{ scope.row.code }}
        </ElTag>
        <span v-else>-</span>
      </template>

      <!-- 启用：停用不是删除，发送方引用它会直接报错 -->
      <template #isEnabled="scope: any">
        <ElTag v-if="scope.row.isEnabled" size="small" round type="success">
          {{ t("pages.notification_template.enabledOn") }}
        </ElTag>
        <ElTag v-else size="small" round>
          {{ t("pages.notification_template.enabledOff") }}
        </ElTag>
      </template>
    </ProPage>

    <!-- 创建/编辑抽屉 -->
    <NotificationTemplateDrawer ref="drawerRef" @success="handleSuccess" />

    <!-- 试渲染：变量集 JSON → 服务端渲染，结果就地展示（看到的字节即发送字节） -->
    <ElDialog
      v-model="renderVisible"
      :title="t('pages.notification_template.renderTitle', { name: renderTarget?.name ?? '' })"
      width="560px"
      align-center
      :close-on-click-modal="false"
      @closed="renderTarget = undefined; renderResult = undefined"
    >
      <ElForm label-width="120px">
        <ElFormItem :label="t('pages.notification_template.varsJson')">
          <ElInput
            v-model="varsJson"
            type="textarea"
            :rows="4"
            :placeholder="t('pages.notification_template.varsJsonPlaceholder')"
          />
          <div class="render-field-tip">{{ t("pages.notification_template.varsJsonHint") }}</div>
        </ElFormItem>
      </ElForm>
      <ElDescriptions v-if="renderResult" :column="1" size="small" border class="render-result">
        <ElDescriptionsItem :label="t('pages.notification_template.renderedTitle')">
          {{ renderResult.title }}
        </ElDescriptionsItem>
        <ElDescriptionsItem :label="t('pages.notification_template.renderedContent')">
          <pre class="render-content">{{ renderResult.content }}</pre>
        </ElDescriptionsItem>
      </ElDescriptions>
      <template #footer>
        <ElButton @click="renderVisible = false">{{ $t("common.button.cancel") }}</ElButton>
        <ElButton type="primary" :loading="rendering" @click="handleRender">
          {{ t("pages.notification_template.renderSubmit") }}
        </ElButton>
      </template>
    </ElDialog>
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import {
  ElButton,
  ElDescriptions,
  ElDescriptionsItem,
  ElDialog,
  ElForm,
  ElFormItem,
  ElInput,
  ElMessage,
  ElMessageBox,
  ElTag,
} from "element-plus";

import ProPage from "@/components/Pro/ProPage/index.vue";
import type { ProPageConfig } from "@/components/Pro/ProPage/types";
import NotificationTemplateDrawer from "./notification-template-drawer.vue";
import type { notificationservicev1_NotificationTemplate as NotificationTemplate } from "@/api/generated/admin/service/v1";
import {
  fetchListNotificationTemplates,
  useDeleteNotificationTemplate,
  useRenderNotificationTemplate,
} from "@/api/composables";
import { PaginationQuery } from "@/core/transport/rest";
import { useI18n } from "@/core/i18n";

const { t } = useI18n();

const pageRef = ref();
const drawerRef = ref();

const { mutateAsync: deleteTemplate } = useDeleteNotificationTemplate();
const { mutateAsync: renderTemplate } = useRenderNotificationTemplate();

const pageConfig = computed<ProPageConfig>(() => ({
  skeleton: true,
  search: {
    grid: true,
    fields: [
      {
        type: "input",
        label: t("pages.notification_template.name"),
        field: "name",
        attrs: { placeholder: t("common.placeholder.input"), clearable: true },
      },
      {
        type: "input",
        label: t("pages.notification_template.code"),
        field: "code",
        attrs: { placeholder: t("common.placeholder.input"), clearable: true },
      },
    ],
  },
  table: {
    listAction: async (query: any) => {
      const { page, pageSize, ...queryParams } = query;
      const result = await fetchListNotificationTemplates(
        new PaginationQuery({
          paging: { page: page || 1, pageSize: pageSize || 20 },
          formValues: {
            name: queryParams.name,
            code: queryParams.code,
          },
        })
      );
      return { items: result.items || [], total: result.total || 0 };
    },
    toolbar: [],
    toolbarRight: ["add"],
    defaultToolbar: ["refresh", "filter"],
    tableAttrs: { border: true, stripe: true },
    emptyActionText: "common.button.add",
    columns: [
      {
        prop: "name",
        label: t("pages.notification_template.name"),
        minWidth: 150,
      },
      {
        prop: "code",
        label: t("pages.notification_template.code"),
        width: 180,
        slotName: "code",
      },
      {
        prop: "titleTemplate",
        label: t("pages.notification_template.titleTemplate"),
        minWidth: 220,
        formatter: (row: NotificationTemplate) => row.titleTemplate || "-",
      },
      {
        prop: "contentTemplate",
        label: t("pages.notification_template.contentTemplate"),
        minWidth: 280,
        formatter: (row: NotificationTemplate) => row.contentTemplate || "-",
      },
      {
        prop: "isEnabled",
        label: t("pages.notification_template.isEnabled"),
        width: 90,
        slotName: "isEnabled",
      },
      {
        prop: "updatedAt",
        label: t("pages.notification_template.updatedAt"),
        width: 170,
        cellType: "date",
        dateFormat: "YYYY-MM-DD HH:mm:ss",
      },
      {
        prop: "action",
        label: t("common.table.action"),
        fixed: "right",
        width: 220,
        cellType: "tool",
        buttons: [
          { name: "edit", label: t("common.button.edit"), icon: "lucide:pen-line" },
          { name: "render", label: t("pages.notification_template.render"), icon: "lucide:eye" },
          // 删除按钮刻意不叫 "delete"：正在被引用的模板删掉后发送方直接报错，后果必须说清
          {
            name: "remove",
            label: t("common.button.delete"),
            icon: "lucide:trash-2",
            attrs: { type: "danger" },
          },
        ],
      },
    ],
  },
}));

function handleAdd() {
  drawerRef.value?.open({ create: true });
}

function handleEdit(row: NotificationTemplate) {
  drawerRef.value?.open({ create: false, row });
}

function handleSuccess() {
  pageRef.value?.refresh();
}

async function handleOperate(data: { name: string; row: NotificationTemplate }) {
  if (data.name === "render") {
    renderTarget.value = data.row;
    varsJson.value = "";
    renderResult.value = undefined;
    renderVisible.value = true;
    return;
  }
  if (data.name !== "remove") return;

  const row = data.row;
  if (!row.id) return;

  try {
    await ElMessageBox.confirm(
      t("pages.notification_template.deleteConfirm"),
      t("common.title.confirm"),
      {
        confirmButtonText: t("common.button.confirm"),
        cancelButtonText: t("common.button.cancel"),
        type: "warning",
        lockScroll: false,
      }
    );
  } catch (error) {
    // 取消是 ElMessageBox 的 reject("cancel")，属正常路径；其余形态（API 误用等）留痕
    if (error !== "cancel" && error !== "close") {
      console.error("delete confirm dialog rejected unexpectedly", error);
    }
    return;
  }

  try {
    await deleteTemplate({ id: row.id });
    ElMessage.success(t("pages.notification_template.deleteSuccess"));
    pageRef.value?.refresh();
  } catch (error: any) {
    // 用户看到的那句翻译不含服务端原因，原始错误必须留在控制台
    console.error("delete notification template failed", error);
    ElMessage.error(error?.message || t("pages.notification_template.deleteFailed"));
  }
}

// === 试渲染 ===
const renderVisible = ref(false);
const rendering = ref(false);
const renderTarget = ref<NotificationTemplate>();
const varsJson = ref("");
const renderResult = ref<{ title: string; content: string }>();

async function handleRender() {
  if (!renderTarget.value?.id) return;

  let variables: Record<string, string> = {};
  const raw = (varsJson.value || "").trim();
  if (raw) {
    try {
      variables = JSON.parse(raw);
    } catch (error: any) {
      console.error("parse template vars json failed", error);
      ElMessage.error(t("pages.notification_template.varsJsonInvalid"));
      return;
    }
  }

  rendering.value = true;
  try {
    // 自定义 RPC（body:"*"）收**扁平**请求体：包一层 { data } 会被 protojson
    // 当未知字段丢掉，接口照样 200、字段全为空
    const resp = await renderTemplate({ id: renderTarget.value.id, variables });
    // 结果就地展示，弹窗保持打开，用户看完手动关闭
    renderResult.value = { title: resp.title ?? "", content: resp.content ?? "" };
  } catch (error: any) {
    console.error("render notification template failed", error);
    ElMessage.error(error?.message || t("pages.notification_template.renderFailed"));
  } finally {
    rendering.value = false;
  }
}
</script>

<style lang="scss" scoped>
.app-container {
  padding: 20px;
  width: 100%;
  min-width: 0;
  flex-shrink: 0;
}

.render-field-tip {
  font-size: 12px;
  line-height: 1.6;
  color: var(--el-text-color-secondary);
  margin-top: 4px;
}

.render-result {
  margin-top: 12px;
}

.render-content {
  margin: 0;
  white-space: pre-wrap;
  max-height: 240px;
  overflow: auto;
  font-family: inherit;
}
</style>

// frontend/admin/react/src/pages/app/notification/template/index.tsx
import { useRef, useState } from 'react';
import type { ActionType, ProColumns } from '@ant-design/pro-components';
import ListTable from '@/components/common/ListTable';
import {
  ModalForm,
  ProFormText,
  ProFormTextArea,
  ProFormSwitch,
} from '@ant-design/pro-components';
import { App, Button, Descriptions, Popconfirm, Tag } from 'antd';
import {
  DeleteOutlined,
  EditOutlined,
  EyeOutlined,
  PlusOutlined,
} from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import type {
  notificationservicev1_CreateNotificationTemplateRequest,
  notificationservicev1_NotificationTemplate as NotificationTemplate,
  notificationservicev1_RenderNotificationTemplateRequest,
  notificationservicev1_UpdateNotificationTemplateRequest,
} from '@/api/generated/admin/service/v1';
import { PaginationQuery } from '@/core';
import { TABLE } from '@/config/constants';
import {
  fetchListNotificationTemplates,
  useCreateNotificationTemplate,
  useDeleteNotificationTemplate,
  useRenderNotificationTemplate,
  useUpdateNotificationTemplate,
} from '@/api/hooks/notification-template';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

/**
 * 通知模板管理（可复用的标题/正文占位模板，{{var}} 占位符）。
 *
 * 发送方以 template_code 引用（SendDirectNotificationRequest.templateCode），
 * 渲染发生在落台账之前——异步载荷装的是渲染结果。建/改模板时服务端会用空变量集
 * 试渲染：模板里只要有占位符、没给值就立刻被拒，坏模板进不了库。
 * 「预览」按钮用给的变量集走服务端 Render，看到的字节即发送字节。
 */

type RenderResult = { title: string; content: string };

const NotificationTemplatePage = () => {
  const { t } = useTranslation('notification-template');
  const actionRef = useRef<ActionType>(null);
  const { message } = App.useApp();
  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);

  const [formOpen, setFormOpen] = useState(false);
  const [formMode, setFormMode] = useState<'create' | 'edit'>('create');
  const [selected, setSelected] = useState<NotificationTemplate | undefined>();
  const [renderTarget, setRenderTarget] = useState<NotificationTemplate | undefined>();
  const [renderResult, setRenderResult] = useState<RenderResult | undefined>();

  const refresh = () => actionRef.current?.reload();

  const createMutation = useCreateNotificationTemplate();
  const updateMutation = useUpdateNotificationTemplate();
  const deleteMutation = useDeleteNotificationTemplate();
  const renderMutation = useRenderNotificationTemplate();

  const handleDelete = async (record: NotificationTemplate) => {
    if (!record.id) return;
    try {
      await deleteMutation.mutateAsync({ id: record.id });
      message.success(t('deleteSuccess'));
      refresh();
    } catch (error: any) {
      // 原始错误必须留在控制台：用户可见的那句翻译不包含服务端的原因
      console.error('delete notification template failed', error);
      message.error(error.message || t('deleteFailed'));
    }
  };

  const handleSubmit = async (values: Record<string, any>) => {
    const data = {
      name: values.name,
      code: values.code,
      titleTemplate: values.titleTemplate,
      contentTemplate: values.contentTemplate,
      isEnabled: !!values.isEnabled,
      remark: values.remark,
    };
    try {
      if (formMode === 'create') {
        const req: notificationservicev1_CreateNotificationTemplateRequest = { data };
        await createMutation.mutateAsync(req);
        message.success(t('createSuccess'));
      } else if (selected?.id) {
        const req: notificationservicev1_UpdateNotificationTemplateRequest = {
          id: selected.id,
          data,
          // code 刻意不进掩码：模板编码是发送方的引用锚，改码等于让所有引用悬空，删旧建新才说得清
          updateMask: 'name,titleTemplate,contentTemplate,isEnabled,remark',
        };
        await updateMutation.mutateAsync(req);
        message.success(t('updateSuccess'));
      }
      setFormOpen(false);
      refresh();
      return true;
    } catch (error: any) {
      console.error('save notification template failed', error);
      message.error(error.message || t('saveFailed'));
      return false;
    }
  };

  const handleRender = async (values: { varsJson?: string }) => {
    if (!renderTarget?.id) return false;
    let variables: Record<string, string> = {};
    const raw = (values.varsJson || '').trim();
    if (raw) {
      try {
        variables = JSON.parse(raw);
      } catch (error: any) {
        console.error('parse template vars json failed', error);
        message.error(t('varsJsonInvalid'));
        return false;
      }
    }
    try {
      const req: notificationservicev1_RenderNotificationTemplateRequest = {
        id: renderTarget.id,
        variables,
      };
      const resp = await renderMutation.mutateAsync(req);
      setRenderResult({ title: resp.title ?? '', content: resp.content ?? '' });
      // 返回 false 让弹窗保持打开：结果就地展示，用户看完手动关闭
      return false;
    } catch (error: any) {
      console.error('render notification template failed', error);
      message.error(error.message || t('renderFailed'));
      return false;
    }
  };

  const columns: ProColumns<NotificationTemplate>[] = [
    {
      title: t('name'),
      dataIndex: 'name',
      width: 160,
    },
    {
      title: t('code'),
      dataIndex: 'code',
      width: 180,
      copyable: true,
      render: (_, record) => <Tag color="geekblue">{record.code || '-'}</Tag>,
    },
    {
      title: t('titleTemplate'),
      dataIndex: 'titleTemplate',
      width: 240,
      ellipsis: true,
    },
    {
      title: t('contentTemplate'),
      dataIndex: 'contentTemplate',
      ellipsis: true,
    },
    {
      title: t('isEnabled'),
      dataIndex: 'isEnabled',
      width: 90,
      render: (_, record) =>
        record.isEnabled ? <Tag color="success">{t('enabledOn')}</Tag> : <Tag>{t('enabledOff')}</Tag>,
    },
    {
      title: t('updatedAt'),
      dataIndex: 'updatedAt',
      width: 170,
      valueType: 'dateTime',
      hideInSearch: true,
    },
    {
      title: t('actions'),
      valueType: 'option',
      width: 240,
      fixed: 'right',
      render: (_, record) => [
        <Button
          key="edit"
          type="link"
          size="small"
          icon={<EditOutlined />}
          onClick={() => {
            setFormMode('edit');
            setSelected(record);
            setFormOpen(true);
          }}
        >
          {t('edit')}
        </Button>,
        <Button
          key="render"
          type="link"
          size="small"
          icon={<EyeOutlined />}
          onClick={() => {
            setRenderTarget(record);
            setRenderResult(undefined);
          }}
        >
          {t('render')}
        </Button>,
        <Popconfirm key="delete" title={t('deleteConfirm')} onConfirm={() => handleDelete(record)}>
          <Button danger type="link" size="small" icon={<DeleteOutlined />}>
            {t('delete')}
          </Button>
        </Popconfirm>,
      ],
    },
  ];

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      <div ref={containerRef} className="page-container-content">
        <ListTable<NotificationTemplate>
          actionRef={actionRef}
          columns={columns}
          request={async (params) => {
            const query = new PaginationQuery({
              paging: { page: params.current || 1, pageSize: params.pageSize || 20 },
              formValues: Object.fromEntries(
                Object.entries(params).filter(([key]) => !['current', 'pageSize'].includes(key)),
              ),
            });
            const response = await fetchListNotificationTemplates(query);
            return { data: response.items || [], total: response.total || 0, success: true };
          }}
          rowKey="id"
          search={{ labelWidth: 'auto', defaultCollapsed: false }}
          pagination={{
            defaultPageSize: TABLE.DEFAULT_PAGE_SIZE,
            showSizeChanger: true,
          }}
          options={{ density: true, fullScreen: true, setting: true, reload: true }}
          toolBarRender={() => [
            <Button
              key="create"
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setFormMode('create');
                setSelected(undefined);
                setFormOpen(true);
              }}
            >
              {t('create')}
            </Button>,
          ]}
          size="middle"
          bordered
          scroll={{ y: tableScrollY, x: 1200 }}
        />
      </div>

      <ModalForm
        title={formMode === 'create' ? t('create') : t('edit')}
        width={620}
        open={formOpen}
        onOpenChange={setFormOpen}
        modalProps={{ destroyOnHidden: true, mask: { closable: false } }}
        submitTimeout={3000}
        onFinish={handleSubmit}
        initialValues={
          formMode === 'create'
            ? { isEnabled: true }
            : { ...selected }
        }
      >
        <ProFormText
          name="name"
          label={t('name')}
          rules={[{ required: true, message: t('requiredName') }, { max: 100, message: t('maxChars', { max: 100 }) }]}
        />
        <ProFormText
          name="code"
          label={t('code')}
          disabled={formMode === 'edit'}
          rules={[
            { required: true, message: t('requiredCode') },
            { pattern: /^[A-Za-z0-9_-]{1,64}$/, message: t('codePattern') },
          ]}
          extra={t('codeHint')}
        />
        <ProFormText
          name="titleTemplate"
          label={t('titleTemplate')}
          placeholder={t('titleTemplatePlaceholder')}
          rules={[{ required: true, message: t('requiredTitleTemplate') }, { max: 500, message: t('maxChars', { max: 500 }) }]}
        />
        <ProFormTextArea
          name="contentTemplate"
          label={t('contentTemplate')}
          placeholder={t('contentTemplatePlaceholder')}
          rules={[{ required: true, message: t('requiredContentTemplate') }, { max: 20000, message: t('maxChars', { max: 20000 }) }]}
          fieldProps={{ rows: 6, showCount: true }}
        />
        <ProFormSwitch name="isEnabled" label={t('isEnabled')} />
        <ProFormTextArea name="remark" label={t('remark')} fieldProps={{ rows: 2 }} />
      </ModalForm>

      <ModalForm<{ varsJson?: string }>
        title={t('renderTitle', { name: renderTarget?.name || '' })}
        width={560}
        open={!!renderTarget}
        onOpenChange={(open) => {
          if (!open) setRenderTarget(undefined);
        }}
        modalProps={{ destroyOnHidden: true }}
        submitTimeout={10000}
        onFinish={handleRender}
      >
        <ProFormTextArea
          name="varsJson"
          label={t('varsJson')}
          placeholder={t('varsJsonPlaceholder')}
          fieldProps={{ rows: 4 }}
          extra={t('varsJsonHint')}
        />
        {renderResult && (
          <Descriptions column={1} size="small" bordered style={{ marginTop: 8 }}>
            <Descriptions.Item label={t('renderedTitle')}>{renderResult.title}</Descriptions.Item>
            <Descriptions.Item label={t('renderedContent')}>
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap', maxHeight: 240, overflow: 'auto' }}>
                {renderResult.content ?? ''}
              </pre>
            </Descriptions.Item>
          </Descriptions>
        )}
      </ModalForm>
    </ContentContainer>
  );
};

export default NotificationTemplatePage;
