// frontend/admin/vue-vben/apps/admin/src/views/app/ai/chat/index.vue
<script lang="ts" setup>
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';

import { Page } from '@vben/common-ui';
import { $t } from '@vben/locales';
import { LucidePlus, LucideTrash2 } from '@vben/icons';

import { message } from 'ant-design-vue';
import { Icon as Iconify } from '@iconify/vue';
import { marked } from 'marked';
import DOMPurify from 'dompurify';

import { PaginationQuery, deleteAiConversation, fetchListAiConversations, fetchListAiKnowledgeBases, fetchListAiMessages, sendAiChat } from '#/api';
import type { aiservicev1_AiKnowledgeBase as AiKnowledgeBase } from '#/api/generated/admin/service/v1';
import { globalSSEClient, SSE_EVENT } from '#/transport/sse';
import type {
  aiservicev1_AiConversation as AiConversation,
  aiservicev1_AiMessage as AiMessage,
} from '#/api/generated/admin/service/v1';

// marked 单行换行按 GFM 处理（聊天场景常见单换行段落）
marked.setOptions({ gfm: true, breaks: true });

function renderMarkdown(content: string): string {
  // AI 回复经 DOMPurify 消毒后再 v-html；LLM 输出不可信，防注入
  return DOMPurify.sanitize(marked.parse(content, { async: false }) as string);
}

// ── 会话 ──────────────────────────────────────────────────────────
const conversations = ref<AiConversation[]>([]);
const activeId = ref<number | undefined>(undefined);

async function loadConversations() {
  try {
    const r = await fetchListAiConversations(
      new PaginationQuery({ paging: { page: 1, pageSize: 100 }, orderBy: ['-last_message_at'] }),
    );
    conversations.value = (r.items || []) as AiConversation[];
    if (activeId.value === undefined && conversations.value.length > 0) {
      activeId.value = conversations.value[0]!.id;
    }
  } catch (error) {
    console.error('load ai conversations failed:', error);
    message.error($t('page.aiChat.fetchFailed'));
  }
}

// ── 消息 ──────────────────────────────────────────────────────────
const messages = ref<AiMessage[]>([]);

async function loadMessages() {
  if (activeId.value === undefined) {
    messages.value = [];
    return;
  }
  try {
    const r = await fetchListAiMessages(
      new PaginationQuery({
        paging: { page: 1, pageSize: 200 },
        formValues: { conversation_id: activeId.value },
        orderBy: ['id'],
      }),
    );
    messages.value = (r.items || []) as AiMessage[];
    scrollToBottom();
  } catch (error) {
    console.error('load ai messages failed:', error);
    message.error($t('page.aiChat.fetchFailed'));
  }
}

watch(activeId, () => {
  streamingText.value = '';
  loadMessages();
});

// ── 流式 ──────────────────────────────────────────────────────────
const streamingText = ref('');
const scrollRef = ref<HTMLElement>();

function scrollToBottom() {
  nextTick(() => {
    scrollRef.value?.scrollTo({ top: scrollRef.value?.scrollHeight ?? 0, behavior: 'smooth' });
  });
}

interface ChatChunk {
  conversationId?: number;
  seq?: number;
  delta?: string;
}

function handleChunk(data: ChatChunk) {
  if (!data || typeof data !== 'object' || !data.conversationId) return;
  // 只渲染当前打开会话的片段；其余会话的 chunk 静默丢弃（响应到达后列表刷新）
  if (data.conversationId !== activeId.value) return;
  streamingText.value += data.delta || '';
  scrollToBottom();
}

onMounted(() => {
  loadConversations();
  loadMessages();
  // 必须按回调引用显式注销：组件重挂载反复 on() 会让回调累加（同 useNotice 的坑）
  globalSSEClient.on<ChatChunk>(SSE_EVENT.AIChatChunk, handleChunk);
});

onBeforeUnmount(() => {
  globalSSEClient.off(SSE_EVENT.AIChatChunk, handleChunk);
});

// ── 知识库选择（RAG：发送时携带 knowledgeBaseId） ─────────────────
const knowledgeBases = ref<AiKnowledgeBase[]>([]);
const knowledgeBaseId = ref<number | undefined>(undefined);

onMounted(() => {
  fetchListAiKnowledgeBases(new PaginationQuery({ paging: { page: 1, pageSize: 100 } }))
    .then((res) => {
      knowledgeBases.value = (res.items || []) as AiKnowledgeBase[];
    })
    .catch((error) => console.error('fetch ai knowledge bases failed:', error));
});

// ── 发送 ──────────────────────────────────────────────────────────
const input = ref('');
const sending = ref(false);

async function handleSend() {
  const content = input.value.trim();
  if (!content || sending.value) return;
  streamingText.value = '';
  sending.value = true;
  scrollToBottom();
  try {
    const resp = await sendAiChat({ conversationId: activeId.value ?? 0, content, knowledgeBaseId: knowledgeBaseId.value ?? 0 });
    input.value = '';
    streamingText.value = '';
    if (resp.conversation?.id) {
      const exists = conversations.value.some((c) => c.id === resp.conversation!.id);
      if (!exists) {
        activeId.value = resp.conversation.id;
        await loadConversations();
      }
    }
    await loadMessages();
  } catch (error) {
    console.error('send ai chat failed:', error);
    message.error(error instanceof Error ? error.message : $t('page.aiChat.chatFailed'));
  } finally {
    sending.value = false;
  }
}

// ── 删除会话 ──────────────────────────────────────────────────────
async function confirmDelete(conv: AiConversation) {
  try {
    await deleteAiConversation(conv.id!);
    message.success($t('page.aiChat.deleteSuccess'));
    if (activeId.value === conv.id) {
      activeId.value = undefined;
      messages.value = [];
    }
    await loadConversations();
  } catch (error) {
    console.error('delete ai conversation failed:', error);
    message.error(error instanceof Error ? error.message : $t('page.aiChat.fetchFailed'));
  }
}

function handleNewConversation() {
  activeId.value = undefined;
  messages.value = [];
  streamingText.value = '';
  loadConversations();
}
</script>

<template>
  <Page auto-content-height>
    <div class="flex h-full min-h-0 gap-4">
      <!-- 左栏：会话列表 -->
      <div class="flex w-64 shrink-0 flex-col rounded-xl border border-solid border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between px-3 py-2">
          <span class="font-semibold">{{ $t('page.aiChat.conversations') }}</span>
          <a-button size="small" type="primary" @click="handleNewConversation">
            <template #icon>
              <LucidePlus />
            </template>
            {{ $t('page.aiChat.newConversation') }}
          </a-button>
        </div>
        <div class="min-h-0 flex-1 overflow-y-auto px-2 pb-2">
          <div v-if="conversations.length === 0" class="py-8 text-center text-gray-400">
            {{ $t('page.aiChat.noConversations') }}
          </div>
          <div
            v-for="conv in conversations"
            :key="conv.id"
            class="group flex cursor-pointer items-center justify-between rounded-lg px-3 py-2 text-sm"
            :class="activeId === conv.id
              ? 'bg-primary/10 text-primary'
              : 'hover:bg-gray-100 dark:hover:bg-gray-800'"
            @click="activeId = conv.id"
          >
            <span class="truncate">{{ conv.title || `#${conv.id}` }}</span>
            <a-popconfirm
              :cancel-text="$t('ui.button.cancel')"
              :ok-text="$t('ui.button.ok')"
              :title="$t('page.aiChat.deleteConversationConfirm')"
              @confirm="confirmDelete(conv)"
            >
              <a-button
                class="hidden group-hover:inline-flex"
                danger
                size="small"
                type="text"
                @click.stop
              >
                <LucideTrash2 />
              </a-button>
            </a-popconfirm>
          </div>
        </div>
      </div>

      <!-- 右栏：消息区 -->
      <div class="flex min-h-0 min-w-0 flex-1 flex-col rounded-xl border border-solid border-gray-200 dark:border-gray-700">
        <div ref="scrollRef" class="min-h-0 flex-1 space-y-4 overflow-y-auto p-4">
          <div
            v-if="messages.length === 0 && !sending"
            class="flex h-full flex-col items-center justify-center gap-2 text-gray-400"
          >
            <Iconify icon="lucide:bot" class="text-5xl" />
            <div class="text-base font-semibold">{{ $t('page.aiChat.emptyTitle') }}</div>
            <div class="text-sm">{{ $t('page.aiChat.emptyDesc') }}</div>
          </div>

          <template v-for="msg in messages" :key="msg.id">
            <!-- 用户消息：右侧纯文本气泡 -->
            <div v-if="msg.role === 'USER'" class="flex flex-row-reverse items-start gap-3">
              <div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-500 text-white">
                <Iconify icon="lucide:user" />
              </div>
              <div class="max-w-[75%] whitespace-pre-wrap break-words rounded-2xl rounded-tr-sm bg-blue-500 px-4 py-2 text-white">
                {{ msg.content }}
              </div>
            </div>
            <!-- AI 消息：左侧 markdown 渲染 -->
            <div v-else class="flex items-start gap-3">
              <div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-500 text-white">
                <Iconify icon="lucide:bot" />
              </div>
              <div class="max-w-[75%] rounded-2xl rounded-tl-sm bg-gray-100 px-4 py-2 dark:bg-gray-800">
                <div class="markdown-body break-words" v-html="renderMarkdown(msg.content || '')" />
                <div
                  v-if="msg.promptTokens || msg.completionTokens"
                  class="mt-1 text-xs text-gray-400"
                  :title="`${msg.modelName || ''} · ${msg.durationMs || 0}ms`"
                >
                  {{ $t('page.aiChat.tokensUsage', { prompt: msg.promptTokens ?? 0, completion: msg.completionTokens ?? 0 }) }}
                </div>
              </div>
            </div>
          </template>

          <!-- 流式占位气泡 -->
          <div v-if="sending" class="flex items-start gap-3">
            <div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-500 text-white">
              <LucideBot />
            </div>
            <div class="max-w-[75%] rounded-2xl rounded-tl-sm bg-gray-100 px-4 py-2 dark:bg-gray-800">
              <div v-if="streamingText" class="markdown-body break-words" v-html="renderMarkdown(streamingText)" />
              <div v-else class="py-1 text-gray-400">…</div>
              <div class="text-xs text-gray-400">{{ $t('page.aiChat.streaming') }}</div>
            </div>
          </div>
        </div>

        <!-- 输入区 -->
        <div class="border-t border-solid border-gray-200 p-3 dark:border-gray-700">
          <div class="mb-2 flex items-center gap-2">
            <span class="shrink-0 text-xs text-gray-400">{{ $t('page.aiChat.knowledgeBase') }}</span>
            <a-select
              v-model:value="knowledgeBaseId"
              allow-clear
              class="!w-56"
              size="small"
              :placeholder="$t('page.aiChat.knowledgeBasePlaceholder')"
              :options="knowledgeBases.map((kb) => ({ label: kb.name || `#${kb.id}`, value: kb.id }))"
            />
          </div>
          <div class="flex items-end gap-2">
            <a-textarea
              v-model:value="input"
              :auto-size="{ minRows: 1, maxRows: 5 }"
              :disabled="sending"
              :placeholder="$t('page.aiChat.inputPlaceholder')"
              class="flex-1"
              @keydown.enter.exact.prevent="handleSend"
            />
            <a-button
              :disabled="!input.trim()"
              :loading="sending"
              type="primary"
              @click="handleSend"
            >
              {{ sending ? $t('page.aiChat.sending') : $t('page.aiChat.send') }}
            </a-button>
          </div>
        </div>
      </div>
    </div>
  </Page>
</template>

<style scoped>
.markdown-body :deep(p) {
  margin: 0 0 0.5em;
}

.markdown-body :deep(p:last-child) {
  margin-bottom: 0;
}

.markdown-body :deep(pre) {
  background: #0d1117;
  color: #e6edf3;
  border-radius: 8px;
  padding: 12px;
  overflow-x: auto;
  margin: 0.5em 0;
}

.markdown-body :deep(code) {
  background: rgb(128 128 128 / 15%);
  border-radius: 4px;
  padding: 1px 4px;
}

.markdown-body :deep(pre code) {
  background: transparent;
  padding: 0;
}

.markdown-body :deep(table) {
  border-collapse: collapse;
  margin: 0.5em 0;
}

.markdown-body :deep(th),
.markdown-body :deep(td) {
  border: 1px solid var(--border);
  padding: 4px 8px;
}
</style>

// frontend/admin/react/src/pages/app/ai/chat/index.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Button, Empty, Input, Popconfirm, Select, Spin, Tooltip, Typography, App } from 'antd';
import {
  DeleteOutlined,
  PlusOutlined,
  SendOutlined,
  UserOutlined,
  RobotOutlined,
} from '@ant-design/icons';
import { useQueryClient } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { aiservicev1_AiConversation, aiservicev1_AiMessage } from '@/api/generated/admin/service/v1';
import { PaginationQuery, globalSSEClient, SSE_EVENT } from '@/core';
import {
  useDeleteAiConversation,
  useListAiConversations,
  useListAiMessages,
  useSendChat,
} from '@/api/hooks/ai-chat';
import { fetchListAiKnowledgeBases } from '@/api/hooks/ai-knowledge';
import type { aiservicev1_AiKnowledgeBase as AiKnowledgeBase } from '@/api/generated/admin/service/v1';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

interface ChatChunk {
  conversationId?: number;
  seq?: number;
  delta?: string;
}

export default function AiChatPage() {
  const { t } = useTranslation('aiChat');
  const { message: antdMessage } = App.useApp();
  const queryClient = useQueryClient();

  // ── 会话列表 ──────────────────────────────────────────────────────
  const conversationsQuery = useListAiConversations(
    new PaginationQuery({ paging: { page: 1, pageSize: 100 }, orderBy: ['-last_message_at'] }),
  );
  const conversations = useMemo(
    () => (conversationsQuery.data?.items ?? []) as aiservicev1_AiConversation[],
    [conversationsQuery.data],
  );

  const [activeId, setActiveId] = useState<number | undefined>(undefined);

  // 首次加载自动选中最近会话
  useEffect(() => {
    if (activeId === undefined && conversations.length > 0) {
      setActiveId(conversations[0].id);
    }
  }, [conversations, activeId]);

  // ── 消息列表 ──────────────────────────────────────────────────────
  const messagesQuery = useListAiMessages(
    new PaginationQuery({
      paging: { page: 1, pageSize: 200 },
      formValues: activeId ? { conversation_id: activeId } : undefined,
      orderBy: ['id'],
    }),
    { enabled: activeId !== undefined },
  );
  const messages = useMemo(
    () => (messagesQuery.data?.items ?? []) as aiservicev1_AiMessage[],
    [messagesQuery.data],
  );

  // ── 知识库选择（RAG：发送时携带 knowledgeBaseId） ─────────────────
  const [knowledgeBases, setKnowledgeBases] = useState<AiKnowledgeBase[]>([]);
  const [knowledgeBaseId, setKnowledgeBaseId] = useState<number | undefined>(undefined);

  useEffect(() => {
    fetchListAiKnowledgeBases(new PaginationQuery({ paging: { page: 1, pageSize: 100 } }))
      .then((res) => setKnowledgeBases((res.items ?? []) as AiKnowledgeBase[]))
      .catch((error: Error) => console.error('fetch ai knowledge bases failed:', error));
  }, []);

  // ── 流式累积 ──────────────────────────────────────────────────────
  const [streamingText, setStreamingText] = useState('');
  const scrollRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = useCallback(() => {
    requestAnimationFrame(() => {
      scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
    });
  }, []);

  // SSE 订阅：本用户流上的 ai_chat_chunk，按会话归组累积
  useEffect(() => {
    const handler = (data: unknown) => {
      const chunk = data as ChatChunk;
      if (!chunk || typeof chunk !== 'object' || !chunk.conversationId) return;
      setStreamingText((prev) => (chunk.delta ? prev + chunk.delta : prev));
    };
    globalSSEClient.on(SSE_EVENT.AIChatChunk, handler);
    return () => {
      globalSSEClient.off(SSE_EVENT.AIChatChunk, handler);
    };
  }, []);

  // 内容变化时滚到底
  useEffect(() => {
    scrollToBottom();
  }, [messages.length, streamingText, scrollToBottom]);

  // ── 发送 ──────────────────────────────────────────────────────────
  const [input, setInput] = useState('');
  const sendMutation = useSendChat({
    onSuccess: (resp) => {
      setInput('');
      setStreamingText('');
      if (resp.conversation?.id) {
        setActiveId(resp.conversation.id);
      }
      queryClient.invalidateQueries({ queryKey: ['listAiConversations'] });
      queryClient.invalidateQueries({ queryKey: ['listAiMessages'] });
    },
    onError: (error: Error) => {
      setStreamingText('');
      antdMessage.error(error.message || t('chatFailed'));
    },
  });

  const handleSend = () => {
    const content = input.trim();
    if (!content || sendMutation.isPending) return;
    // 先本地渲染用户气泡与占位：响应到达后由列表刷新接管
    setStreamingText('');
    sendMutation.mutate({ conversationId: activeId ?? 0, providerId: 0, content, knowledgeBaseId: knowledgeBaseId ?? 0 });
  };

  // ── 删除会话 ──────────────────────────────────────────────────────
  const deleteConversationMutation = useDeleteAiConversation({
    onSuccess: () => {
      antdMessage.success(t('deleteSuccess'));
      setStreamingText('');
      
      queryClient.invalidateQueries({ queryKey: ['listAiConversations'] });
      queryClient.invalidateQueries({ queryKey: ['listAiMessages'] });
    },
    onError: (error: Error) => antdMessage.error(error.message || t('fetchFailed')),
  });

  const handleDeleteConversation = (id: number) => {
    deleteConversationMutation.mutate({ id });
    if (activeId === id) {
      setActiveId(undefined);
    }
  };

  const handleNewConversation = () => {
    setActiveId(undefined);
    setStreamingText('');
    messagesQuery.refetch();
  };

  // ── 渲染 ──────────────────────────────────────────────────────────
  const isStreaming = sendMutation.isPending;

  return (
    <ContentContainer heightMode="fixed">
      <div className="flex h-full min-h-0 gap-4">
        {/* 左栏：会话列表 */}
        <div className="flex w-64 shrink-0 flex-col rounded-xl border border-solid border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between px-3 py-2">
            <Typography.Text strong>{t('conversations')}</Typography.Text>
            <Button type="primary" size="small" icon={<PlusOutlined />} onClick={handleNewConversation}>
              {t('newConversation')}
            </Button>
          </div>
          <div className="min-h-0 flex-1 overflow-y-auto px-2 pb-2">
            {conversations.length === 0 ? (
              <Empty description={t('noConversations')} image={Empty.PRESENTED_IMAGE_SIMPLE} />
            ) : (
              conversations.map((conv) => (
                <div
                  key={conv.id}
                  role="button"
                  tabIndex={0}
                  onClick={() => setActiveId(conv.id)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') setActiveId(conv.id);
                  }}
                  className={`group flex cursor-pointer items-center justify-between rounded-lg px-3 py-2 text-sm ${
                    activeId === conv.id
                      ? 'bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-300'
                      : 'hover:bg-gray-100 dark:hover:bg-gray-800'
                  }`}
                >
                  <span className="truncate">{conv.title || `#${conv.id}`}</span>
                  <Popconfirm
                    title={t('deleteConversation')}
                    description={t('deleteConversationConfirm')}
                    onConfirm={(e) => {
                      e?.stopPropagation();
                      handleDeleteConversation(conv.id!);
                    }}
                    onCancel={(e) => e?.stopPropagation()}
                  >
                    <Button
                      type="text"
                      size="small"
                      danger
                      className="hidden group-hover:inline-flex"
                      icon={<DeleteOutlined />}
                      onClick={(e) => e.stopPropagation()}
                    />
                  </Popconfirm>
                </div>
              ))
            )}
          </div>
        </div>

        {/* 右栏：消息区 */}
        <div className="flex min-h-0 min-w-0 flex-1 flex-col rounded-xl border border-solid border-gray-200 dark:border-gray-700">
          <div ref={scrollRef} className="min-h-0 flex-1 space-y-4 overflow-y-auto p-4">
            {messages.length === 0 && !isStreaming ? (
              <div className="flex h-full flex-col items-center justify-center gap-2 text-gray-400">
                <RobotOutlined className="text-5xl" />
                <Typography.Title level={5} className="!mb-0">
                  {t('emptyTitle')}
                </Typography.Title>
                <Typography.Text type="secondary">{t('emptyDesc')}</Typography.Text>
              </div>
            ) : (
              <>
                {messages.map((msg) => (
                  <MessageBubble key={msg.id} message={msg} />
                ))}
                {isStreaming && (
                  <div className="flex items-start gap-3">
                    <Avatar role="assistant" />
                    <div className="max-w-[75%] rounded-2xl rounded-tl-sm bg-gray-100 px-4 py-2 dark:bg-gray-800">
                      {streamingText ? (
                        <MarkdownContent content={streamingText} />
                      ) : (
                        <Spin size="small" />
                      )}
                      <Typography.Text type="secondary" className="!text-xs">
                        {t('streaming')}
                      </Typography.Text>
                    </div>
                  </div>
                )}
              </>
            )}
          </div>

          {/* 输入区 */}
          <div className="border-t border-solid border-gray-200 p-3 dark:border-gray-700">
            <div className="mb-2 flex items-center gap-2">
              <Typography.Text type="secondary" className="!text-xs shrink-0">
                {t('knowledgeBase')}
              </Typography.Text>
              <Select
                value={knowledgeBaseId}
                onChange={(v) => setKnowledgeBaseId(v)}
                allowClear
                size="small"
                className="min-w-48"
                placeholder={t('knowledgeBasePlaceholder')}
                options={knowledgeBases.map((kb) => ({ label: kb.name ?? `#${kb.id}`, value: kb.id! }))}
              />
            </div>
            <div className="flex items-end gap-2">
              <Input.TextArea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder={t('inputPlaceholder')}
                autoSize={{ minRows: 1, maxRows: 5 }}
                onPressEnter={(e) => {
                  if (!e.shiftKey) {
                    e.preventDefault();
                    handleSend();
                  }
                }}
                disabled={isStreaming}
                className="flex-1"
              />
              <Button
                type="primary"
                icon={<SendOutlined />}
                loading={isStreaming}
                onClick={handleSend}
                disabled={!input.trim()}
              >
                {isStreaming ? t('sending') : t('send')}
              </Button>
            </div>
          </div>
        </div>
      </div>
    </ContentContainer>
  );
}

// ── 子组件 ──────────────────────────────────────────────────────────

function Avatar({ role }: { role: string }) {
  const { t } = useTranslation('aiChat');
  return (
    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-500 text-white">
      {role === 'assistant' ? <RobotOutlined /> : <UserOutlined />}
      <span className="sr-only">{role === 'assistant' ? t('assistant') : t('you')}</span>
    </div>
  );
}

function MessageBubble({ message: msg }: { message: aiservicev1_AiMessage }) {
  const { t } = useTranslation('aiChat');
  const isUser = msg.role === 'USER';

  if (isUser) {
    return (
      <div className="flex flex-row-reverse items-start gap-3">
        <Avatar role="user" />
        <div className="max-w-[75%] whitespace-pre-wrap break-words rounded-2xl rounded-tr-sm bg-blue-500 px-4 py-2 text-white">
          {msg.content}
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-start gap-3">
      <Avatar role="assistant" />
      <div className="max-w-[75%] rounded-2xl rounded-tl-sm bg-gray-100 px-4 py-2 dark:bg-gray-800">
        <MarkdownContent content={msg.content ?? ''} />
        {(msg.promptTokens || msg.completionTokens) && (
          <Tooltip title={`${msg.modelName ?? ''} · ${msg.durationMs ?? 0}ms`}>
            <Typography.Text type="secondary" className="!text-xs">
              {t('tokensUsage', { prompt: msg.promptTokens ?? 0, completion: msg.completionTokens ?? 0 })}
            </Typography.Text>
          </Tooltip>
        )}
      </div>
    </div>
  );
}

function MarkdownContent({ content }: { content: string }) {
  return (
    <div className="prose prose-sm max-w-none break-words dark:prose-invert [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:bg-gray-900 [&_pre]:p-3 [&_pre]:text-gray-100">
      <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
    </div>
  );
}
