// frontend/admin/react/src/pages/app/ai/query/index.tsx
import { useEffect, useRef, useState } from 'react';
import { Button, Input, Table, Tag, Typography, App } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { SendOutlined, ThunderboltOutlined } from '@ant-design/icons';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useI18n } from '@/core/i18n';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';
import { useAskAiQuery, type AskAiQueryHistoryItem, type AskAiQueryParams } from '@/api/hooks/ai-query';
import type { aiservicev1_AiQueryRow } from '@/api/generated/admin/service/v1';

type Round = {
  question: string;
  sql?: string;
  columns?: string[];
  rows?: aiservicev1_AiQueryRow[];
  answer?: string;
  loading: boolean;
};

/** 示例问题（点击直接填入输入框）。 */
const SAMPLE_KEYS = ['sample1', 'sample2', 'sample3'] as const;

/**
 * 智能问数页（平台管理员专属）：自然语言 → 只读 SQL → 结构化结果 → AI 结论。
 * 对话式布局：输入区吸底、消息流自动滚到最新；SQL 原样展示便于核对。
 */
export default function AiQueryPage() {
  const { t, i18n } = useI18n('aiQuery');
  const { message } = App.useApp();
  const [input, setInput] = useState('');
  const [rounds, setRounds] = useState<Round[]>([]);
  const bottomRef = useRef<HTMLDivElement>(null);

  // 新轮次追加/更新时滚到底部
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' });
  }, [rounds]);

  const askMutation = useAskAiQuery({
    onSuccess: (resp) => {
      setRounds((prev) => {
        if (prev.length === 0) return prev;
        const last = prev.length - 1;
        const next = [...prev];
        next[last] = {
          ...next[last]!,
          sql: resp.sql,
          columns: resp.columns ?? [],
          rows: resp.rows ?? [],
          answer: resp.answer ?? '',
          loading: false,
        };
        return next;
      });
    },
    onError: (error: Error) => {
      setRounds((prev) => {
        if (prev.length === 0) return prev;
        const last = prev.length - 1;
        const next = [...prev];
        next[last] = { ...next[last]!, loading: false };
        return next;
      });
      message.error(error.message || t('failed'));
    },
  });

  const handleAsk = () => {
    const question = input.trim();
    if (!question || askMutation.isPending) return;
    // 携带最近 5 轮历史（问题+SQL+结果摘要），供模型消解追问里的指代
    const history: AskAiQueryHistoryItem[] = rounds
      .filter((r) => !r.loading && r.sql)
      .slice(-5)
      .map((r) => ({
        question: r.question,
        sql: r.sql ?? '',
        resultSummary: (r.rows ?? []).slice(0, 3).map((row) => (row.values ?? []).join(' | ')).join('；'),
      }));
    const params: AskAiQueryParams = { question, lang: i18n.language, withAnswer: true, history };
    setRounds((prev) => [...prev, { question, loading: true }]);
    setInput('');
    askMutation.mutate(params);
  };

  return (
    <ContentContainer heightMode="auto" scrollable padding="16px">
      <div className="mx-auto flex max-w-4xl flex-col gap-4 pb-2">
        {/* 标题 + 示例问题（仅首轮前展示） */}
        {rounds.length === 0 && (
          <div className="flex flex-col items-center gap-3 py-10 text-center">
            <ThunderboltOutlined className="text-5xl text-blue-500" />
            <Typography.Title level={4} className="!mb-0">
              {t('title')}
            </Typography.Title>
            <Typography.Text type="secondary">{t('emptyDesc')}</Typography.Text>
            <div className="mt-2 flex flex-wrap justify-center gap-2">
              {SAMPLE_KEYS.map((key) => (
                <Button key={key} size="small" onClick={() => setInput(t(`samples.${key}`))}>
                  {t(`samples.${key}`)}
                </Button>
              ))}
            </div>
          </div>
        )}

        {/* 问答轮次 */}
        {rounds.map((round, i) => (
          <div key={i} className="flex flex-col gap-3">
            {/* 用户问题：右侧气泡 */}
            <div className="flex flex-row-reverse items-start gap-3">
              <div className="max-w-[80%] whitespace-pre-wrap break-words rounded-2xl rounded-tr-sm bg-blue-500 px-4 py-2 text-white">
                {round.question}
              </div>
            </div>

            {/* 结果卡片：左侧 */}
            <div className="flex items-start gap-3">
              <div className="min-w-0 flex-1 rounded-xl border border-solid border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
                {round.loading ? (
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <span className="inline-block h-2 w-2 animate-pulse rounded-full bg-blue-500" />
                    {t('thinking')}
                  </div>
                ) : (
                  <>
                    {round.sql && (
                      <details className="mb-3" open>
                        <summary className="cursor-pointer text-xs text-gray-400">
                          {t('generatedSql')}
                        </summary>
                        <pre className="mt-2 overflow-x-auto rounded-lg bg-gray-900 p-3 text-xs leading-relaxed text-gray-100">
                          {round.sql}
                        </pre>
                      </details>
                    )}

                    {round.columns && round.columns.length > 0 && (
                      <QueryTable columns={round.columns} rows={round.rows ?? []} />
                    )}
                    {round.sql && (round.rows?.length ?? 0) === 0 && (
                      <Typography.Text type="secondary" className="!text-xs">
                        {t('noRows')}
                      </Typography.Text>
                    )}

                    {round.answer && (
                      <div className="mt-3 rounded-lg border border-solid border-blue-200 bg-blue-50 p-3 text-sm leading-relaxed dark:border-blue-900 dark:bg-blue-950">
                        <Tag color="processing" className="mb-1">
                          {t('answerTag')}
                        </Tag>
                        <div className="markdown-body max-w-none overflow-x-auto break-words [&_li]:m-0 [&_p]:mb-1 [&_table]:w-full [&_table]:border-collapse [&_td]:border [&_td]:border-gray-300 [&_td]:px-2 [&_td]:py-1 [&_th]:border [&_th]:border-gray-300 [&_th]:px-2 [&_th]:py-1 [&_th]:bg-gray-100 dark:[&_td]:border-gray-600 dark:[&_th]:bg-gray-800 dark:[&_th]:border-gray-600">
                          <ReactMarkdown remarkPlugins={[remarkGfm]}>{round.answer}</ReactMarkdown>
                        </div>
                      </div>
                    )}
                  </>
                )}
              </div>
            </div>
          </div>
        ))}
        <div ref={bottomRef} />
      </div>

      {/* 输入区（吸底） */}
      <div className="sticky bottom-0 -mx-4 -mb-4 border-t border-solid border-gray-200 bg-white/95 p-4 backdrop-blur dark:border-gray-700 dark:bg-gray-900/95">
        <div className="mx-auto flex max-w-4xl items-end gap-2">
          <Input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onPressEnter={() => handleAsk()}
            placeholder={t('inputPlaceholder')}
            size="large"
            disabled={askMutation.isPending}
            allowClear
          />
          <Button
            type="primary"
            size="large"
            icon={<SendOutlined />}
            loading={askMutation.isPending}
            disabled={!input.trim()}
            onClick={() => handleAsk()}
          >
            {t('ask')}
          </Button>
        </div>
      </div>
    </ContentContainer>
  );
}

/** 查询结果表：以该轮返回的 columns 动态生成列。 */
function QueryTable({
  columns,
  rows,
}: {
  columns: string[];
  rows: aiservicev1_AiQueryRow[];
}) {
  const tableColumns: ColumnsType<{ key: number; cells: string[] }> = columns.map(
    (col, idx) => ({
      title: col,
      dataIndex: ['cells', String(idx)],
      key: col,
      ellipsis: true,
    }),
  );
  const data = rows.map((r, ri) => ({ key: ri, cells: r.values ?? [] }));

  return (
    <Table
      size="small"
      rowKey="key"
      columns={tableColumns}
      dataSource={data}
      pagination={data.length > 10 ? { pageSize: 10, showSizeChanger: false } : false}
      scroll={{ x: 'max-content' }}
    />
  );
}

// frontend/admin/vue-element/src/pages/app/ai/query/index.vue
<template>
  <div class="app-container ai-query-page h-full flex flex-1 flex-col">
    <div class="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-4 overflow-y-auto pb-2">
      <!-- 标题 + 示例问题（仅首轮前展示） -->
      <div v-if="rounds.length === 0" class="flex flex-col items-center gap-3 py-10 text-center">
        <Icon icon="lucide:zap" class="text-5xl text-blue-500" />
        <div class="text-lg font-semibold">{{ t("pages.ai_query.title") }}</div>
        <div class="text-sm text-gray-400">{{ t("pages.ai_query.emptyDesc") }}</div>
        <div class="mt-2 flex flex-wrap justify-center gap-2">
          <ElButton
            v-for="key in sampleKeys"
            :key="key"
            size="small"
            @click="input = t(`pages.ai_query.${key}`)"
          >
            {{ t(`pages.ai_query.${key}`) }}
          </ElButton>
        </div>
      </div>

      <!-- 问答轮次 -->
      <div v-for="(round, i) in rounds" :key="i" class="flex flex-col gap-3">
        <!-- 用户问题：右侧气泡 -->
        <div class="flex flex-row-reverse items-start gap-3">
          <div class="max-w-[80%] whitespace-pre-wrap break-words rounded-2xl rounded-tr-sm bg-blue-500 px-4 py-2 text-white">
            {{ round.question }}
          </div>
        </div>

        <!-- 结果卡片：左侧 -->
        <div class="flex items-start gap-3">
          <div class="min-w-0 flex-1 rounded-xl border border-solid border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
            <div v-if="round.loading" class="flex items-center gap-2 text-sm text-gray-400">
              <span class="inline-block h-2 w-2 animate-pulse rounded-full bg-blue-500" />
              {{ t("pages.ai_query.thinking") }}
            </div>
            <template v-else>
              <details v-if="round.sql" class="mb-3" open>
                <summary class="cursor-pointer text-xs text-gray-400">
                  {{ t("pages.ai_query.generatedSql") }}
                </summary>
                <pre class="mt-2 overflow-x-auto rounded-lg bg-gray-900 p-3 text-xs leading-relaxed text-gray-100">{{ round.sql }}</pre>
              </details>

              <ElTable v-if="round.columns && round.columns.length > 0" :data="tableRows(round)" size="small" border>
                <ElTableColumn
                  v-for="(col, ci) in round.columns"
                  :key="col"
                  :label="col"
                  :prop="String(ci)"
                  show-overflow-tooltip
                >
                  <template #default="{ row }">{{ row.cells[ci] }}</template>
                </ElTableColumn>
              </ElTable>
              <div v-if="round.sql && (round.rows?.length ?? 0) === 0" class="mt-2 text-xs text-gray-400">
                {{ t("pages.ai_query.noRows") }}
              </div>

              <div
                v-if="round.answer"
                class="mt-3 rounded-lg border border-solid border-blue-200 bg-blue-50 p-3 text-sm leading-relaxed dark:border-blue-900 dark:bg-blue-950"
              >
                <ElTag type="primary" size="small" class="mb-1">{{ t("pages.ai_query.answerTag") }}</ElTag>
                <div class="markdown-body break-words" v-html="renderMarkdown(round.answer)" />
              </div>
            </template>
          </div>
        </div>
      </div>
    </div>

    <!-- 输入区（吸底） -->
    <div class="sticky bottom-0 mt-4 border-t border-solid border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
      <div class="mx-auto flex w-full max-w-4xl items-end gap-2">
        <ElInput
          v-model="input"
          type="textarea"
          :autosize="{ minRows: 1, maxRows: 4 }"
          :placeholder="t('pages.ai_query.inputPlaceholder')"
          :disabled="loading"
          @keydown.enter.exact.prevent="handleAsk()"
        />
        <ElButton type="primary" :loading="loading" :disabled="!input.trim()" @click="handleAsk()">
          {{ loading ? t("pages.ai_query.thinking") : t("pages.ai_query.ask") }}
        </ElButton>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { nextTick, ref } from "vue";
import { ElButton, ElInput, ElMessage, ElTable, ElTableColumn, ElTag } from "element-plus";
import { Icon } from "@iconify/vue";
import { marked } from "marked";
import DOMPurify from "dompurify";
import { i18n, useI18n } from "@/core/i18n";
import { apiClient } from "@/api/client";

// marked 单行换行按 GFM 处理
marked.setOptions({ gfm: true, breaks: true });

function renderMarkdown(content: string): string {
  // AI 回复经 DOMPurify 消毒后再 v-html；LLM 输出不可信，防注入
  return DOMPurify.sanitize(marked.parse(content, { async: false }) as string);
}

const { t } = useI18n();

const sampleKeys = ["sample1", "sample2", "sample3"];

interface Round {
  question: string;
  sql?: string;
  columns?: string[];
  rows?: { cells: string[] }[];
  answer?: string;
  loading: boolean;
}

const rounds = ref<Round[]>([]);
const input = ref("");
const loading = ref(false);

function tableRows(round: Round) {
  return (round.rows || []).map((r, i) => ({ id: i, cells: r.cells }));
}

/** 滚到底部（新轮次追加后）。 */
function scrollToBottom() {
  nextTick(() => {
    window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" });
  });
}

/** 告警文案：后端只回结构化事实，LLM 结论走 markdown 渲染，无需模板。 */
async function handleAsk() {
  const question = input.value.trim();
  if (!question || loading.value) return;
  // 携带最近 5 轮历史（问题+SQL+结果摘要），供模型消解追问里的指代
  const history = rounds.value
    .filter((r) => !r.loading && r.sql)
    .slice(-5)
    .map((r) => ({
      question: r.question,
      sql: r.sql || "",
      resultSummary: (r.rows || []).slice(0, 3).map((row) => row.cells.join(" | ")).join("；"),
    }));
  rounds.value.push({ question, loading: true });
  input.value = "";
  loading.value = true;
  scrollToBottom();
  try {
    const locale = i18n.global.locale as unknown as { value?: string };
    const lang = locale?.value || "zh-CN";
    const resp = await apiClient.aiQueryService.Ask({
      question,
      lang,
      withAnswer: true,
      history,
    } as any);
    const last = rounds.value[rounds.value.length - 1];
    if (last) {
      last.sql = resp.sql;
      last.columns = (resp.columns || []) as string[];
      last.rows = (resp.rows || []).map((r) => ({ cells: (r.values || []) as string[] }));
      last.answer = resp.answer || "";
      last.loading = false;
    }
    scrollToBottom();
  } catch (error: any) {
    console.error("ai query failed:", error);
    ElMessage.error(error?.message || t("pages.ai_query.failed"));
    const last = rounds.value[rounds.value.length - 1];
    if (last) last.loading = false;
  }
}
</script>

<style lang="scss" scoped>
.ai-query-page {
  min-height: 0;
}

.markdown-body {
  :deep(p) {
    margin: 0 0 0.5em;
    &:last-child {
      margin-bottom: 0;
    }
  }
  :deep(table) {
    border-collapse: collapse;
    margin: 0.5em 0;
    width: 100%;
  }
  :deep(th),
  :deep(td) {
    border: 1px solid var(--el-border-color);
    padding: 4px 8px;
  }
  :deep(th) {
    background: var(--el-fill-color-light);
  }
}
</style>
