// frontend/admin/vue-vben/apps/admin/src/views/app/system/online_session/index.vue
<script lang="ts" setup>
import type { VxeGridProps } from '#/adapter/vxe-table';

import { h } from 'vue';

import { Page, type VbenFormProps } from '@vben/common-ui';
import { LucideLogOut } from '@vben/icons';

import { notification, type TagProps } from 'ant-design-vue';

import { useVbenVxeGrid } from '#/adapter/vxe-table';
import {
  fetchListOnlineSessions,
  useForceLogoutSession,
} from '#/api';
import type {
  online_sessionservicev1_OnlineSession as OnlineSession,
} from '#/api/generated/admin/service/v1';
import { $t } from '#/locales';

const { mutateAsync: forceLogout } = useForceLogoutSession();

const formOptions: VbenFormProps = {
  collapsed: false,
  showCollapseButton: false,
  submitOnEnter: true,
  schema: [
    {
      component: 'Input',
      fieldName: 'keyword',
      label: $t('page.onlineSession.keyword'),
      componentProps: {
        allowClear: true,
        placeholder: $t('page.onlineSession.keyword'),
      },
    },
  ],
};

const gridOptions: VxeGridProps<OnlineSession> = {
  toolbarConfig: {
    custom: true,
    refresh: true,
    zoom: true,
  },
  height: 'auto',
  pagerConfig: {},
  rowConfig: {
    isHover: true,
    keyField: 'jti',
  },
  stripe: true,

  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        const values = (formValues ?? {}) as Record<string, any>;
        return await fetchListOnlineSessions({
          page: page.currentPage,
          pageSize: page.pageSize,
          keyword: values.keyword || undefined,
        });
      },
    },
  },

  columns: [
    { title: $t('ui.table.seq'), type: 'seq', width: 50 },
    { title: $t('page.onlineSession.username'), field: 'username', minWidth: 120 },
    {
      title: $t('page.onlineSession.tenant'),
      field: 'tenantId',
      width: 90,
      slots: { default: 'tenant' },
    },
    {
      title: $t('page.onlineSession.clientType'),
      field: 'clientType',
      width: 100,
      slots: { default: 'clientType' },
    },
    { title: $t('page.onlineSession.ipAddress'), field: 'ipAddress', minWidth: 130 },
    {
      title: $t('page.onlineSession.userAgent'),
      field: 'userAgent',
      minWidth: 220,
      showOverflow: true,
    },
    {
      title: $t('page.onlineSession.deviceId'),
      field: 'deviceId',
      width: 120,
      formatter: ({ cellValue }) => cellValue || '-',
    },
    {
      title: $t('page.onlineSession.loginAt'),
      field: 'loginAt',
      formatter: 'formatDateTime',
      width: 160,
    },
    {
      title: $t('ui.table.action'),
      field: 'action',
      fixed: 'right',
      slots: { default: 'action' },
      width: 110,
    },
  ],
};

const [Grid, gridApi] = useVbenVxeGrid({ gridOptions, formOptions });

function clientTagColor(clientType?: string): TagProps['color'] {
  return clientType === 'app' ? 'purple' : 'blue';
}

/* 强制下线：确认后吊销该会话的访问/刷新令牌 */
async function handleForceLogout(row: OnlineSession) {
  if (!row.jti || row.userId === undefined) return;

  try {
    await forceLogout({
      clientType: row.clientType,
      userId: row.userId,
      jti: row.jti,
    });
    notification.success({
      message: $t('page.onlineSession.forceLogoutSuccess'),
    });
    await gridApi.reload();
  } catch (error: any) {
    notification.error({
      message: error?.message || $t('page.onlineSession.forceLogoutFailed'),
    });
  }
}
</script>

<template>
  <Page auto-content-height>
    <Grid :table-title="$t('page.onlineSession.moduleName')">
      <template #tenant="{ row }">
        <a-tag v-if="(row.tenantId ?? 0) === 0">
          {{ $t('page.onlineSession.platform') }}
        </a-tag>
        <span v-else>#{{ row.tenantId }}</span>
      </template>
      <template #clientType="{ row }">
        <a-tag :color="clientTagColor(row.clientType)">
          {{
            row.clientType === 'app'
              ? $t('page.onlineSession.clientApp')
              : $t('page.onlineSession.clientAdmin')
          }}
        </a-tag>
      </template>
      <template #action="{ row }">
        <a-popconfirm
          :cancel-text="$t('ui.button.cancel')"
          :ok-text="$t('ui.button.ok')"
          :title="
            $t('page.onlineSession.forceLogoutConfirmDesc', {
              user: row.username || String(row.userId),
            })
          "
          @confirm="handleForceLogout(row)"
        >
          <a-button danger type="link" size="small" :icon="h(LucideLogOut)">
            {{ $t('page.onlineSession.forceLogout') }}
          </a-button>
        </a-popconfirm>
      </template>
    </Grid>
  </Page>
</template>

// frontend/admin/react/src/pages/app/system/online-session/index.tsx
import { useRef } from 'react';
import type { ProColumns, ActionType } from '@ant-design/pro-components';
import ListTable from '@/components/common/ListTable';
import { App, Button, Popconfirm, Space, Tag, Tooltip } from 'antd';
import { DeleteOutlined } from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import type {
  online_sessionservicev1_OnlineSession as OnlineSession,
} from '@/api/generated/admin/service/v1';
import {
  fetchListOnlineSessions,
  useForceLogoutSession,
} from '@/api/hooks/online-session';
import TableExportButton from '@/components/common/TableExportButton';
import { TABLE } from '@/config/constants';
import { useProTableScrollY } from '@/hooks/useProTableScrollY';
import ContentContainer from '@/layouts/components/PageContainer/ContentContainer';

/**
 * 在线用户（在线会话）页面
 * 数据来自 Redis 会话元数据：登录 / 刷新轮换 / MFA 验证通过时写入，
 * 随 refresh token 过期或吊销消失。支持按用户名/IP 搜索与强制下线。
 */
const OnlineSessionPage = () => {
  const { t } = useTranslation('online-session');
  const actionRef = useRef<ActionType>(null);
  const { message } = App.useApp();
  const containerRef = useRef<HTMLDivElement>(null);
  const tableScrollY = useProTableScrollY(containerRef);

  const forceLogoutMutation = useForceLogoutSession({
    onSuccess: () => {
      message.success(t('forceLogoutSuccess'));
      actionRef.current?.reload();
    },
  });

  const handleForceLogout = async (record: OnlineSession) => {
    if (!record.jti || record.userId === undefined) {
      return;
    }
    try {
      await forceLogoutMutation.mutateAsync({
        clientType: record.clientType,
        userId: record.userId,
        jti: record.jti,
      });
    } catch (error: any) {
      message.error(error.message || t('forceLogoutFailed'));
    }
  };

  const columns: ProColumns<OnlineSession>[] = [
    {
      title: t('username'),
      dataIndex: 'username',
      width: 130,
      ellipsis: true,
      hideInSearch: true, // 后端仅支持 keyword 聚合过滤（用户名/IP），单独的 username 搜索不生效
    },
    {
      title: t('tenant'),
      dataIndex: 'tenantId',
      width: 90,
      hideInSearch: true,
      render: (_, record) =>
        (record.tenantId ?? 0) === 0 ? (
          <Tag>{t('platform')}</Tag>
        ) : (
          `#${record.tenantId}`
        ),
    },
    {
      title: t('clientType'),
      dataIndex: 'clientType',
      width: 100,
      hideInSearch: true,
      render: (_, record) =>
        record.clientType === 'app' ? (
          <Tag color="purple">{t('clientApp')}</Tag>
        ) : (
          <Tag color="blue">{t('clientAdmin')}</Tag>
        ),
    },
    {
      title: t('ipAddress'),
      dataIndex: 'ipAddress',
      width: 140,
      ellipsis: true,
      hideInSearch: true, // 同上，IP 过滤并入 keyword
    },
    {
      title: t('userAgent'),
      dataIndex: 'userAgent',
      hideInSearch: true,
      ellipsis: { showTitle: false },
      render: (_, record) => (
        <Tooltip title={record.userAgent || '-'} placement="topLeft">
          <span style={{ color: 'inherit' }}>{record.userAgent || '-'}</span>
        </Tooltip>
      ),
    },
    {
      title: t('deviceId'),
      dataIndex: 'deviceId',
      width: 130,
      hideInSearch: true,
      ellipsis: true,
      render: (_, record) => record.deviceId || '-',
    },
    {
      title: t('loginAt'),
      dataIndex: 'loginAt',
      width: 170,
      valueType: 'dateTime',
      hideInSearch: true,
    },
    {
      // 搜索框只有一个"用户名/IP"关键词，对应后端 keyword 过滤
      title: t('keyword'),
      dataIndex: 'keyword',
      hideInTable: true,
      fieldProps: {
        placeholder: t('keywordPlaceholder'),
      },
    },
    {
      title: t('actions'),
      valueType: 'option',
      width: 110,
      fixed: 'right',
      render: (_, record) => (
        <Space>
          <Popconfirm
            title={t('forceLogoutConfirm')}
            description={t('forceLogoutConfirmDesc', { user: record.username || record.userId })}
            okButtonProps={{ loading: forceLogoutMutation.isPending }}
            onConfirm={() => handleForceLogout(record)}
          >
            <Button danger type="link" size="small" icon={<DeleteOutlined />}>
              {t('forceLogout')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <ContentContainer heightMode="fixed" padding="16px" bottomMargin={0}>
      <div ref={containerRef} className="page-container-content">
        <ListTable<OnlineSession>
          actionRef={actionRef}
          columns={columns}
          request={async (params) => {
            const response = await fetchListOnlineSessions({
              page: params.current || 1,
              pageSize: params.pageSize || 20,
              keyword: (params.keyword as string) || undefined,
            });
            return {
              data: response.items || [],
              total: response.total || 0,
              success: true,
            };
          }}
          toolBarRender={() => [
            <TableExportButton
              key="export"
              fetcher={(q) =>
                fetchListOnlineSessions({
                  page: Number(q.paging?.page) || 1,
                  pageSize: Number(q.paging?.pageSize) || 1000,
                  keyword: (q.formValues?.keyword as string) || undefined,
                })
              }
              columns={columns}
              filename="online-sessions"
            />,
          ]}
          rowKey={(record) => `${record.clientType}-${record.userId}-${record.jti}`}
          search={{
            labelWidth: 'auto',
            defaultCollapsed: false,
          }}
          polling={30}
          pagination={{
            defaultPageSize: TABLE.DEFAULT_PAGE_SIZE,
            showSizeChanger: true,
            showQuickJumper: true,
          }}
          options={{
            density: true,
            fullScreen: true,
            setting: true,
            reload: true,
          }}
          size="middle"
          bordered
          cardBordered={false}
          scroll={{
            y: tableScrollY,
            x: 1200,
          }}
        />
      </div>
    </ContentContainer>
  );
};

export default OnlineSessionPage;
